### ISSUE TITLE
Fatal failure at CVC4/src/./expr/node_builder.h:772

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3695] opened 2020-02-02 12:30 UTC
Hi,
For this formula,
```
(assert (> (exp 70000000) 0))
(check-sat)
```
cvc4 throws out a fatal failure:
```
Fatal failure within void CVC4::NodeBuilder<N>::realloc(size_t) [with unsigned int nchild_thresh = 10; size_t = long unsigned int] at CVC4/src/./expr/node_builder.h:772
Check failure
 toSize > d_nvMaxChildren
attempt to realloc() a NodeBuilder to a smaller/equal size!
Aborted
```

OS: Ubuntu 18.04
Revision: 7583e03

**Comment by 4tXJ7f** [comment] 2020-02-03 07:06
The issue is that we are rewriting `pow(x, c)` where `c` is a constant argument to a multiplication (https://github.com/CVC4/CVC4/blob/master/src/theory/arith/arith_rewriter.cpp#L237-L243). In this case, we have `pow(exp(1), 70000000)` and we exceed the maximum number of children when we try to create the multiplication node. This is unfortunately not straightforward to fix: If we simply don't rewrite `pow` in this case, we get some different issue, likely due to some assumptions in the rest of the code. This is a general problem that we have and I put it on the agenda for one of our CVC4 meetings.

**Comment by nafur** [comment] 2020-08-05 19:00
After #4852, this example now shows a more suitable error:
`(error "The exponent of the POW(^) operator can only be a positive integral constant below 67108864. Exception occurred in:
  (^ (exp 1) 70000000.0)")`
This is what we expect and thus we close this issue.

**Closed by nafur** 2020-08-05 19:00 UTC
