### ISSUE TITLE
Invalid model fatal failure at src/smt/smt_engine.cpp:2148 (uf-ss-totality)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4872] opened 2020-08-11 04:52 UTC
~~~~
(set-logic QF_UFC)
(set-option :uf-ss-totality true)
(declare-sort S0 0)
(declare-const S0-0 S0)
(assert (fmf.card S0-0 1))
(assert (fmf.card S0-0 4))
(check-sat)

~~~~
cvc4 33b96c6565
~~~~
Fatal failure within void CVC4::SmtEngine::checkModel(bool) at /home/peisen/test/tofuzz/CVC4/src/smt/smt_engine.cpp:2148
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (fmf.card S0-0 1)
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted

~~~~

**Comment by 4tXJ7f** [comment] 2020-08-11 04:55
This is likely a duplicate of #4850.

**Comment by rainoftime** [comment] 2020-10-10 13:37
Fixed

**Closed** 2020-10-12 22:56 UTC
Labels: minor
