### ISSUE TITLE
Fatal failure at proof_manager.cpp:286 (proof, fewer-preprocessing-holes)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4338] opened 2020-04-19 08:12 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_NIA)
(set-option :proof true)
(set-option :fewer-preprocessing-holes true)
(declare-const i0 Int)
(declare-const i2 Int)
(assert (! (and (=> (> i2 0) false) (< 72 i2 i0 0)) :named IP_74))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
 ;; In the preprocessor we trust 
(th_let_pf _ (trust_f (iff Fatal failure within void CVC4::ProofManager::traceDeps(CVC4::TNode, CVC4::ExprSet*) at /home/peisen/test/tofuzz/CVC4/src/proof/proof_manager.cpp:286
Internal error detectedCannot trace dependence information back to input assertion:
`(or (>= i2 1) (not (>= i2 73)))'
Aborted (core dumped)

~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:50
`proof` is deprecated. We plan to replace it with a new implementation in the future.

**Comment by ajreynol** [comment] 2020-04-19 13:54
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:54 UTC
