### ISSUE TITLE
set-logic / set-option etc (Bugzilla #668)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#887] opened 2017-08-19 03:11 UTC
**Imported from Bugzilla**
Reporter: *Kshitij*
Status: *NEW*
Severity: *normal*
Assigned to: *Clark Barrett*
Component: *SMT-LIB support*
Milestone: *1.6*
Version: *master*
Platform: *All*
OS: *All*

On 2015-09-02 14:44:38 -0700, Kshitij wrote:
> It appears we do not respect the automata in SMTLIB2 document 100% : we allow
> for set\-option to be called even after set\-logic and declare\-funs.
> 
> Side\-effect: We call setDefaults() when finalOptionsAreSet() is called. Thus if some options are incompatibile with the current logic, the set\-logic command will return "success" at this stage.
> 
> \-\-Kshitij

**Comment by ajreynol** [comment] 2018-10-18 12:46
This appears to be a duplicate of #2613, closing.

**Closed by ajreynol** 2018-10-18 12:46 UTC
Labels: duplicate, feature, normal
