### ISSUE TITLE
--check-models fails on QF_NRA benchmark

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#3003] opened 2019-05-15 22:20 UTC
On the following benchmark, CVC4 fails with `--check-models`:

```
(set-logic QF_NRA)                                                                                                                                                  
(declare-fun _substvar_15_ () Real)                                                                                                                                 
(declare-fun _substvar_17_ () Real)                                                                                                                                 
(assert (let ((?v_1 (<= 0.0 _substvar_15_))) (and ?v_1 (and ?v_1 (and ?v_1 (= (* _substvar_15_ _substvar_15_) (+ 1 (* _substvar_17_ (* _substvar_17_ (- 1)))))))))) 
(check-sat)                                                                                                                                                         
```

**Comment by ajreynol** [comment] 2019-05-15 22:55
This appears to be due to an approximation of an irrational value, if you run --dump-models:
```
(model
(approximation (and (>= _substvar_15_ (/ 209533 524288)) (>= (* (- 1.0) _substvar_15_) (/ (- 15086389) 37748736))))
(define-fun _substvar_15_ () Real (/ 15086389 37748736))
(define-fun _substvar_17_ () Real (/ 150994931 150994944))
)
```
Notice the approximation. 
CVC4 uses these kinds of approximations in a "SAT" response when it, e.g. simultaneously knows that x must be equal to sqrt(2) and must be greater than 1.4. If it can compute (by binary search) that sqrt(2) is greater than 1.4, then it can answer "SAT" without having an exact model.
Issue https://github.com/CVC4/CVC4/issues/2008 is related to this.

**Comment by ajreynol** [comment] 2019-05-15 22:56
Summarizing here: this isn't a critical failure, I'm going to lower this to "minor".  Notice z3 also says "sat" on this one.

**Comment by ajreynol** [comment] 2019-11-04 18:00
This is a duplicate of #2153.

**Closed by ajreynol** 2019-11-04 18:00 UTC
Labels: bug, duplicate, minor
