### ISSUE TITLE
Invalid model for SEQ formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5891] opened 2021-02-11 02:42 UTC
Hi, cv4 ac998a45ae64c58
~~~~
(declare-fun i5 () Int)
(assert (not (seq.prefixof (seq.unit i5) (seq.unit 0))))
(check-sat)
~~~~
~~~~
cvc4 -q --check-models  ../delta.out.smt2 
Fatal failure within void CVC4::smt::CheckModels::checkModel(CVC4::smt::Model*, CVC4::context::CDList<CVC4::NodeTemplate<true> >*, bool) at CVC4/src/smt/check_models.cpp:129
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (not (str.prefixof (seq.unit i5) (seq.unit 0)))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
~~~~

**Comment by ajreynol** [comment] 2021-02-19 02:00
I cannot reproduce this on master.  This appears to have been fixed by https://github.com/CVC4/CVC4/commit/ca9705cf0785e3a81fc25995df0bc3dc76e3bd9f.

**Comment by ajreynol** [comment] 2021-02-19 02:00
I cannot reproduce this on master.  This appears to have been fixed by https://github.com/CVC4/CVC4/commit/ca9705cf0785e3a81fc25995df0bc3dc76e3bd9f.

**Closed by ajreynol** 2021-02-19 02:00 UTC
