### ISSUE TITLE
Generate model error instead of assertion failure for approximate models

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2008] opened 2018-05-29 18:24 UTC
Currently, running with `--check-models` on QF_NRA/meti-tarski/sin/cos/sin-cos-346-b-chunk-0169.smt2 results in an assertion failure:

```
(error "Internal error detected
void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool)
../../../../src/theory/theory_engine.cpp:2275:


THEORY_ARITH has an asserted fact that the model doesn't satisfy.
The fact: (= (* skoSQ3 skoSQ3) 3.0)
Model value: false
")
```

Since the models may be approximate, it can happen that the model does not satisfy the constraints but this should be reported as a model error not an assertion failure (maybe together with the caveat about approximate models).

**Comment by ajreynol** [comment] 2018-06-25 15:47
@4tXJ7f, can you say more about what a "model error" is? Is there a particular kind of exception for this? Or should this be a warning?

**Comment by ajreynol** [comment] 2019-11-04 18:00
This is a duplicate of #2153.

**Comment by ajreynol** [comment] 2019-12-04 02:28
Reopening since this issue actually pertains to a feature that should be fixed: we should throw an error instead of an assertion failure when approximations are used in the model.

**Closed** 2019-12-06 20:23 UTC
Labels: bug, minor
