### ISSUE TITLE
Fatal failure at theory/bv/bitblast/bitblast_strategies_template.h:329 (proof, decision-use-weight)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4354] opened 2020-04-19 09:06 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_ABV)
(declare-fun _substvar_238_ () (Array (_ BitVec 5) Bool))
(set-option :proof true)
(set-option :decision-use-weight true)
(assert (! (= true true false (select _substvar_238_ (bvsrem (_ bv0 5) (bvnand (_ bv22 5) (_ bv22 5)))) true true true) :named IP_130))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within void CVC4::theory::bv::DefaultNandBB(CVC4::TNode, std::vector<_RealType>&, CVC4::theory::bv::TBitblaster<T>*) [with T = CVC4::NodeTemplate<true>; CVC4::TNode = CVC4::NodeTemplate<false>] at /home/peisen/test/tofuzz/CVC4/src/./theory/bv/bitblast/bitblast_strategies_template.h:329
Unimplemented code encountered
Aborted (core dumped
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
