### ISSUE TITLE
--sygus-inference Fatal failure at CVC4/src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp:470

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3648] opened 2020-01-23 09:42 UTC
Hi,
For this formula,
```
(declare-fun a () Real)
(assert (> a 0.000001))
(assert (< (- (sin 1) a) 0.000001))
(check-sat)
```
`cvc4 --sygus-inference` throws out a fatal failure:
```
Fatal failure within virtual bool CVC4::theory::quantifiers::ArithInstantiator::processAssertions(CVC4::theory::quantifiers::CegInstantiator*, CVC4::theory::quantifiers::SolvedForm&, CVC4::Node, CVC4::theory::quantifiers::CegInstEffort) at CVC4/src/theory/quantifiers/cegqi/ceg_arith_instantiator.cpp:470
Check failure
 cmp_bound.isConst()
Aborted
```

OS: Ubuntu 18.04
Revision: fd88b18

**Comment by ajreynol** [comment] 2020-01-23 13:23
This is a duplicate of #3633

**Closed by ajreynol** 2020-01-23 13:23 UTC
Labels: duplicate

**Comment by muchang** [comment] 2020-01-23 13:43
Hi Andrew,

This fatal failure is at line 470, while #3633 is at line 241.
Maybe this one and #3633 were triggering different assertions, and might not be the duplicate. 
Do I understand correctly?

**Comment by ajreynol** [comment] 2020-01-23 14:49
Yes, you're right, I will update the open PR to solve this as well.
