### ISSUE TITLE
theory combination + FMF (Bugzilla #708)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#927] opened 2017-08-19 03:18 UTC
**Imported from Bugzilla**
Reporter: *Andrew Reynolds*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Clark Barrett*
Component: *{Internals} Shared terms/theory combination*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Windows*

On 2016-01-14 18:25:48 -0800, Andrew Reynolds wrote:
> Currently, when finite model finding is enabled, theory combination does not properly handle combinations of Arrays over uninterpreted sorts.
> 
> The core issue is that if you call an uninterpreted type t.getCardinality().isInfinite(), it will say "true", even if finite model finding is turned on.  We decided to do this since t.getCardinality() should be context independent, and hence an infinite cardinality is a conservative guess.  
> 
> So, concerning theory combination, when finite model finding is enabled, we must consider the special case of types that are finite under the assumption that uninterpreted sorts are finite.  This case is handled specially in datatypes, see bool Datatype::isUFinite() line 613 of src/expr/datatype.h.  I believe something similar is necessary in Arrays, and probably Sets.
> 
> After the changes on Jan 14, the regression test/regress/regress0/fmf/agree466.smt2 times out due to the type enumerator running out of values for (Array node$type BOOL).  Use the trace \-t exc\-value, this gives:
> 
> Excluded value for (Array node$type BOOL) : (store ((as const (Array node$type BOOL)) Truth) _@uc\_node\_type\_1 Falsity) due to out of range uninterpreted constant.
> Excluded value for (Array node$type BOOL) : (store (store ((as const (Array node$type BOOL)) Truth) _@uc\_node\_type\_0 Falsity) _@uc\_node\_type\_1 Falsity) due to out of range uninterpreted constant.
> Excluded value for (Array node$type BOOL) : (store ((as const (Array node$type BOOL)) Truth) _@uc\_node\_type\_2 Falsity) due to out of range uninterpreted constant.
> Excluded value for (Array node$type BOOL) : (store (store ((as const (Array node$type BOOL)) Truth) _@uc\_node\_type\_0 Falsity) _@uc\_node\_type\_2 Falsity) due to out of range uninterpreted constant.
> Excluded value for (Array node$type BOOL) : (store (store ((as const (Array node$type BOOL)) Truth) _@uc\_node\_type\_1 Falsity) _@uc\_node\_type\_2 Falsity) due to out of range uninterpreted constant.
> Excluded value for (Array node$type BOOL) : (store (store (store ((as const (Array node$type BOOL)) Truth) _@uc\_node\_type\_0 Falsity) _@uc\_node\_type\_1 Falsity) _@uc\_node\_type\_2 Falsity) due to out of range uninterpreted constant.
> ....

On 2016-01-15 18:08:43 -0800, Andrew Reynolds wrote:
> In my latest commit (1/15), I updated the type enumerators so they will run out of values instead of looping forever.  The failing regression gets this error (as expected):
> 
> virtual void CVC4::theory::TheoryEngineModelBuilder::buildModel(CVC4::Model\*, bool)
> /home/reynolds/cvc4/src/theory/theory\_model.cpp:821:
> 
>   !n.isNull()
> 
> Meaning that it ran out of values for (Array node$type BOOL).

On 2016-03-07 14:07:29 -0800, Andrew Reynolds wrote:
> The regression passes again after commit on March 7, due to a change in array model construction. So this example is fixed, but the correctness of Arrays \+ FMF still needs review.

**Comment by ajreynol** [comment] 2018-06-25 22:10
I'm closing this issue since the regression in question works and it appears that arrays + finite model finding has been working properly.

**Closed by ajreynol** 2018-06-25 22:10 UTC
Labels: feature
