### ISSUE TITLE
Not a 32-bit integer: 4611686018427387903

### ISSUE THREAD

**Issue by backtracking** [CVC4/CVC4#3917] opened 2020-03-04 14:55 UTC
[cvc4-strings-ints.txt](https://github.com/CVC4/CVC4/files/4287914/cvc4-strings-ints.txt)

When running CVC 4 1.7 on the attached input file, with --strings-exp command-line flag,
we get the following error:

$ cvc4-1.7 --lang=smt2 --strings-exp cvc4-strings-ints.txt 
(error "Not a 32-bit integer: 4611686018427387903")

Without that flag, there is no error:
 $ cvc4-1.7 --lang=smt2 cvc4-strings-ints.txt 
unknown
(:reason-unknown incomplete)

**Comment by ajreynol** [comment] 2020-03-04 15:11
Hi, thanks for the benchmark.  I am not able to reproduce this on current CVC4 master (https://github.com/CVC4/CVC4/commit/18fe192c29a9a2c37d1925730af01e906b9888c5). I get:

```
unknown
(:reason-unknown incomplete)
```

It's possible this was fixed in a recent commit, e.g. https://github.com/CVC4/CVC4/pull/3835 fixed an issue with large integers related to strings.

I would recommend updating to the latest development version of cvc4 (binaries are available at https://cvc4.github.io/downloads.html if necessary).

Do let me know if the problem persists.

**Comment by ajreynol** [comment] 2020-03-04 15:18
Also, as an aside, I noticed that the quantified formula that makes this problem hard for cvc4 involves an uninterpreted function `code`.  We actually support this operator as a builtin function in strings (see operator `str.to_code` in the official SMT-LIB theory of unicode strings: http://smtlib.cs.uiowa.edu/theories-UnicodeStrings.shtml), which converts between strings of length one and their code point.  Just FYI in case this makes the encoding any easier.

**Comment by backtracking** [comment] 2020-03-05 08:45
Many thanks for the quick reply and the feedback.
--
Jean-Christophe

**Comment by belolourenco** [comment] 2020-03-05 14:23
[string.txt](https://github.com/CVC4/CVC4/files/4293354/string.txt)

Hi,

I was trying to use the operator `str.to_code` and `str.from_code` with the CVC4 master but I'm getting a parsing error:
```
(error "Parse Error: string.txt:3.28: Symbol 'str.to_code' not declared as a variable

  (assert (= (str.to_code "a") 65))
                           ^
")
```

The operator `code` seems to be fine in both CVC4 master and 1.7, but I don't know what's its counterpart corresponding to `str.from_code`.

**Comment by ajreynol** [comment] 2020-03-05 14:44
The strings standard actually was only officially release a few weeks ago, so we are in the process of being compliant to it.

For now, you can use the option `--lang=smt2.6.1` to make CVC4 conform to the new strings standard (although notice that some operators like `str.replace_all_re` are still not yet supported in CVC4's parser). Regardless, 
CVC4 with --lang=smt2.6.1 accepts both `str.to_code` and `str.from_code`.

We are planning to make this syntax supported by default in the next stable release of CVC4, after which `--lang=smt2.6.1` will not be necessary. For now we are supporting old syntax for many of the string operators by default for the sake of backwards compatibility.

**Comment by belolourenco** [comment] 2020-03-05 14:50
Thanks for clearing that up.

**Comment by ajreynol** [comment] 2020-03-25 04:07
Closing this issue.  Do let me know if you have any further issues with the current version of CVC4.

**Closed by ajreynol** 2020-03-25 04:07 UTC
