### ISSUE TITLE
Strange result for fmf + recursion + arrays

### ISSUE THREAD

**Issue by dddejan** [CVC4/CVC4#1308] opened 2017-11-01 20:39 UTC
@ajreynol 

In the following example, I have a simple recursive definition going down on a parameter n. I was hoping that this could be solved.

```smt2
(set-logic AUFLIA)

(declare-sort element 0)
(declare-fun end () element)
(declare-fun f (element) element)

(define-sort set () (Array element Bool))

(declare-fun empty_set () set)
(assert (forall ((e element)) (not (select empty_set e))))

(define-fun set_contains ((X set) (e element)) Bool (select X e))
(define-fun set_insert ((X set) (e element)) set (store X e true))
(define-fun set_remove ((X set) (e element)) set (store X e false))

(define-fun-rec at_most_n (
  (n Int) (e element) (X set)
) Bool
  (ite (< n 0) false
    (ite (= e end)
      (= X empty_set)
      (and
        (set_contains X e)
        (at_most_n (- n 1) (f e) (set_remove X e))
      )
    )
  )
)

(declare-fun X1 () set)
(declare-fun X2 () set)
(declare-fun x1 () element)
(declare-fun x2 () element)

(assert (distinct end x1 x2))

;; If sat x1 should belong to X1
(assert (at_most_n 1 x1 X1))
;; if sat x2 should belong to X2
(assert (at_most_n 1 x2 X2))

(check-sat)
(get-model)
```

If I run current master CVC4 I get 

```bash
cantor:examples dejan$ ./cvc4 -m --finite-model-find test.smt2 
unknown
(model
; cardinality of element is 3
(declare-sort element 0)
; rep: @uc_element_0
; rep: @uc_element_1
; rep: @uc_element_2
(define-fun end () element @uc_element_0)
(define-fun f ((BOUND_VARIABLE_589 element)) element @uc_element_0)
(define-fun empty_set () (Array element Bool) ((as const (Array element Bool)) false))
(define-fun at_most_n (($x1 Int) ($x2 element) ($x3 (Array element Bool))) Bool (ite (and (= $x1 1) (= @uc_element_1 $x2) (= ((as const (Array element Bool)) false) $x3)) true (and (= $x1 1) (= @uc_element_2 $x2) (= ((as const (Array element Bool)) false) $x3))))
(define-fun X1 () (Array element Bool) ((as const (Array element Bool)) false))
(define-fun X2 () (Array element Bool) ((as const (Array element Bool)) false))
(define-fun x1 () element @uc_element_1)
(define-fun x2 () element @uc_element_2)
)
```

First it says "unknown", but I have a finite domain, so I was hoping you can enumerate models and check them. Are arrays a problem?

Then, in the model I get the arrays X1 and X2 correspond to sets. In a model of the assertions both X1 and X2 should **not** be empty, they should include x1 and x2.

This might on might not be a bug. In any case, guidance would be appreciated.

**Comment by ajreynol** [comment] 2017-11-01 20:50
Hi Dejan, 
Thanks for the benchmark.  To solve this one, you need to use the --fmf-fun option.  This enables the techniques for finite model finding from IJCAR 2016 "Model Finding for Recursive Functions".  By default, --finite-model-find only enables the CADE 2013 algorithm, which doesn't directly deal with recursive functions.

"cvc4 --fmf-fun" gives this response quickly (add --produce-models):

sat
(model
; cardinality of element is 3
(declare-sort element 0)
; rep: @uc_element_0
; rep: @uc_element_1
; rep: @uc_element_2
(define-fun end () element @uc_element_0)
(define-fun f ((BOUND_VARIABLE_1952 element)) element (ite (= @uc_element_0 BOUND_VARIABLE_1952) @uc_element_1 @uc_element_0))
(define-fun empty_set () (Array element Bool) ((as const (Array element Bool)) false))
(define-fun at_most_n ((BOUND_VARIABLE_1969 Int) (BOUND_VARIABLE_1970 element) (BOUND_VARIABLE_1971 (Array element Bool))) Bool true)
(define-fun X1 () (Array element Bool) (store ((as const (Array element Bool)) false) @uc_element_1 true))
(define-fun X2 () (Array element Bool) (store ((as const (Array element Bool)) false) @uc_element_2 true))
(define-fun x1 () element @uc_element_1)
(define-fun x2 () element @uc_element_2)
; cardinality of I_at_most_n is 3
(declare-sort I_at_most_n 0)
; rep: @uc_I_at_most_n_0
; rep: @uc_I_at_most_n_1
; rep: @uc_I_at_most_n_2
)


Is this an expected model for you?  Note that as described in the IJCAR 2016 paper, here, the definition of the recursive function "at_most_n" is only valid for the points where CVC4 determined were relevant (and in this case, all relevant points of at_most_n were interpreted as true).  If you want more information about how to read the models from --fmf-fun, let me know.
Cheers,
Andy

**Comment by dddejan** [comment] 2017-11-01 20:55
I used the wrong option this one indeed works. I have a larger model that still gives me an unexpected result. Let me simplify it and I'll add it here.

**Comment by dddejan** [comment] 2017-11-01 21:08
Ok, here is an expanded version with some extra quantifiers

```smt2
(set-logic AUFLIA)

(declare-sort element 0)
(declare-fun end () element)
(declare-fun f (element) element)

(define-sort set () (Array element Bool))

(declare-fun empty_set () set)
(assert (forall ((e element)) (not (select empty_set e))))

(define-fun set_contains ((X set) (e element)) Bool (select X e))
(define-fun set_insert ((X set) (e element)) set (store X e true))
(define-fun set_remove ((X set) (e element)) set (store X e false))

(define-fun set_union ((X set) (Y set) (Z set)) Bool
  (forall ((e element))
    (= (select Z e)
       (or (select X e) (select Y e))
    )
  )
)

(define-fun set_disjoint ((X set) (Y set)) Bool
  (forall ((e element))
    (not (and (select X e) (select Y e)))
  )
)


(define-fun set_separate ((X set) (Y set) (Z set)) Bool
  (and
    (set_union X Y Z)
    (set_disjoint X Y)
  )
)

(define-fun-rec at_most_n (
  (n Int) (e element) (X set)
) Bool
  (ite (< n 0) false
    (ite (= e end)
      (= X empty_set)
      (exists ((Y set))
        (and
          (set_separate Y (set_insert empty_set e) X )
          (at_most_n (- n 1) (f e) Y)
        )
      )
    )
  )
)

(declare-fun X1 () set)
(declare-fun X2 () set)
(declare-fun x1 () element)
(declare-fun x2 () element)

(assert (distinct end x1 x2))

;; If sat x1 should belong to X1
(assert (at_most_n 1 x1 X1))
;; if sat x2 should belong to X2
(assert (at_most_n 1 x2 X2))

(check-sat)
(get-model)
```

The result I get is 

```bash
cantor:examples dejan$ ./cvc4 -m --fmf-fun test.smt2 
unknown
(model
; cardinality of element is 3
(declare-sort element 0)
; rep: @uc_element_0
; rep: @uc_element_1
; rep: @uc_element_2
(define-fun end () element @uc_element_0)
(define-fun f ((BOUND_VARIABLE_2196 element)) element @uc_element_0)
(define-fun empty_set () (Array element Bool) (store (store (store ((as const (Array element Bool)) true) @uc_element_0 false) @uc_element_1 false) @uc_element_2 false))
(define-fun at_most_n ((BOUND_VARIABLE_2209 Int) (BOUND_VARIABLE_2210 element) (BOUND_VARIABLE_2211 (Array element Bool))) Bool true)
(define-fun X1 () (Array element Bool) (store (store (store ((as const (Array element Bool)) false) @uc_element_0 true) @uc_element_1 true) @uc_element_2 true))
(define-fun X2 () (Array element Bool) (store (store (store ((as const (Array element Bool)) false) @uc_element_0 true) @uc_element_1 true) @uc_element_2 true))
(define-fun x1 () element @uc_element_1)
(define-fun x2 () element @uc_element_2)
; cardinality of I_at_most_n is 2
(declare-sort I_at_most_n 0)
; rep: @uc_I_at_most_n_0
; rep: @uc_I_at_most_n_1
)
```

Above you can see that "f" maps everything to "end". The model of X1 and X2, as sets, have size 3, which is impossible.

It does say "unknown", but I'm still wondering what's going on.

Sorry for distracting with these...

**Comment by ajreynol** [comment] 2017-11-01 21:22
Ah, I see.  So the problematic part of this problem is the definition of at_most_n, in particular the "exists" here:

(define-fun-rec at_most_n (
  (n Int) (e element) (X set)
) Bool
       ...
      (exists ((Y set))
       ...
      )
    )
  )
)

The issue is that a constraint involving at_most_n might be negated.  This leads to universal quantification on set, which is (Array element Bool), then finite model finding is not possible currently in CVC4.
To resolve this, you could do Skolemization up front:

(declare-fun at_most_n_else_witness (Int element set) set)
(define-fun-rec at_most_n (
  (n Int) (e element) (X set)
) Bool
  (ite (< n 0) false
    (ite (= e end)
      (= X empty_set)
        (and
          (set_separate (at_most_n_else_witness n e X) (set_insert empty_set e) X )
          (at_most_n (- n 1) (f e) (at_most_n_else_witness n e X))
        )
    )
  )
)

Although notice this is not equivalent *only if* all occurrences of (at_most_n ...) occur positively in your input.  cvc4 --fmf-fun solves with this definition quickly with this model:

sat
(model
; cardinality of element is 3
(declare-sort element 0)
; rep: @uc_element_0
; rep: @uc_element_1
; rep: @uc_element_2
(define-fun end () element @uc_element_0)
(define-fun f ((BOUND_VARIABLE_2409 element)) element (ite (= @uc_element_0 BOUND_VARIABLE_2409) @uc_element_1 @uc_element_0))
(define-fun empty_set () (Array element Bool) (store (store (store ((as const (Array element Bool)) true) @uc_element_0 false) @uc_element_1 false) @uc_element_2 false))
(define-fun at_most_n_else_witness (($x1 Int) ($x2 element) ($x3 (Array element Bool))) (Array element Bool) (ite (and (= $x1 1) (= @uc_element_2 $x2) (= (store (store ((as const (Array element Bool)) true) @uc_element_0 false) @uc_element_1 false) $x3)) (store (store (store ((as const (Array element Bool)) true) @uc_element_0 false) @uc_element_1 false) @uc_element_2 false) (ite (and (= $x1 1) (= @uc_element_1 $x2) (= (store ((as const (Array element Bool)) false) @uc_element_1 true) $x3)) (store (store (store ((as const (Array element Bool)) true) @uc_element_0 false) @uc_element_1 false) @uc_element_2 false) (store ((as const (Array element Bool)) false) @uc_element_1 true))))
(define-fun at_most_n ((BOUND_VARIABLE_2427 Int) (BOUND_VARIABLE_2428 element) (BOUND_VARIABLE_2429 (Array element Bool))) Bool true)
(define-fun X1 () (Array element Bool) (store ((as const (Array element Bool)) false) @uc_element_1 true))
(define-fun X2 () (Array element Bool) (store (store ((as const (Array element Bool)) true) @uc_element_0 false) @uc_element_1 false))
(define-fun x1 () element @uc_element_1)
(define-fun x2 () element @uc_element_2)
; cardinality of I_at_most_n is 3
(declare-sort I_at_most_n 0)
; rep: @uc_I_at_most_n_0
; rep: @uc_I_at_most_n_1
; rep: @uc_I_at_most_n_2
)

Although you'd have to double check if the Skolemization step above preserves the original semantics.

**Comment by dddejan** [comment] 2017-11-01 21:27
Can we use the relevancy decision heuristic to make sure it's never negated?

**Comment by ajreynol** [comment] 2017-11-01 21:29
Yes, that is enabled by default and is often key to making --fmf-fun work.  I'm surprised it didn't suffice for your original example (I'll investigate a bit...).

**Comment by ajreynol** [comment] 2017-11-01 21:36
Ah, I know why. The reason is because there is a recursive call beneath the existential.  The constraints the IJCAR 2016 algorithm adds to ensure that recursive function calls are made carries the quantified variables we are under, effectively meaning we end up with a top-level constraint that is intuitively:

forall Y : set. [ ensure that we expand the appropriate recursive calls to (at_most_n (- n 1) (f e) Y) ]

The short explanation is that the IJCAR 2016 algorithm isn't as precise as it can be in the case.  This is something I might be able to fix if you're interested (say if the Skolemization suggestion isn't enough).

**Comment by ajreynol** [comment] 2017-11-07 20:19
Closing this and opening #1336.

**Closed by ajreynol** 2017-11-07 20:19 UTC
Labels: feature, minor
