### ISSUE TITLE
cvc4 crashes with incorrect flags

### ISSUE THREAD

**Issue by pjljvandelaar** [CVC4/CVC4#3350] opened 2019-10-03 13:20 UTC
As a user, I sometimes need help about flags.
So I typed
```
cvc4 --help --tlimit
```
Surprisingly, cvc4 crashed with these flags.

Note that when one calls cvc4 as follows
```
cvc4 --tlimit
```
and even
```
cvc4 --tlimit --help
```
cvc4 does not crash, but one gets
```
CVC4 Error:
Error in option parsing: option `--tlimit' missing its required argument

Please use --help to get help on command-line options.
```

**Comment by 4tXJ7f** [comment] 2019-10-03 16:28
I cannot seem to reproduce the crash here (using `master`):

```
$ bin/cvc4 --help --tlimit                         
CVC4 Error:                                                                 
Error in option parsing: option `--tlimit' missing its required argument    
                                                                            
Please use --help to get help on command-line options.                                
```             

What's the output with your version of CVC4? Which version are you using?

Side note: as far as I know, we currently don't support getting information on a specific command (except for commands that offer different choices, where CVC4 offers `--command help` to explain the different choices). One way to get some information on the different commands is to call `cvc4 --help` and then searching for the command that you need help on.

**Comment by 4tXJ7f** [comment] 2020-06-02 08:41
With the nightly Windows build from May 29, I cannot seem to reproduce this issue anymore (with CVC4 1.7, I seem to get a crash), so it looks like this has been fixed. We've had some recent changes in how options are parsed and it looks like that may have done the trick. @pjljvandelaar I am closing this issue for now but please reopen it if it persists for you.

**Closed by 4tXJ7f** 2020-06-02 08:41 UTC
