### ISSUE TITLE
:dt-binary-split :refine-conflicts :sygus-inference fatal failure at src/theory/datatypes/sygus_extension.cpp:1585

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4098] opened 2020-03-15 07:44 UTC
Hi,
For this formula:
```
(set-option :dt-binary-split true)
(set-option :refine-conflicts true)
(set-option :sygus-inference true)
(declare-fun a () Int)  
(declare-fun b () Int) 
(declare-fun g () Int) 
(declare-fun c () Int)   
(declare-fun f () Int)     
(declare-fun d () Int) 
(declare-fun h () Int) 
(declare-fun i () Int) 
(assert (let ((e 0)) (and (>= (- a) 72 b 4) 
(xor (not (>= 0 2)) (not (>= (- h) (/ 7 a) (- c d))))       
(or (>= f 2)) (or (>= 5 (- i g) 2))))) 
(check-sat)
```
CVC4  throws out a fatal failure:
```
Fatal failure within void CVC4::theory::datatypes::SygusExtension::check(std::vector<CVC4::NodeTemplate<true> >&) at src/theory/datatypes/sygus_extension.cpp:1585
Check failure

 false

Aborted
```

OS: Ubuntu 18.04
Commit: 442ab0c

**Comment by ajreynol** [comment] 2020-03-15 13:46
`refine-conflicts` will be deleted, duplicate of #4008.

**Closed by ajreynol** 2020-03-15 13:46 UTC
