### ISSUE TITLE
Wrong model with --arrays-weak-equiv? (Bugzilla #791)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1004] opened 2017-08-19 04:39 UTC
**Imported from Bugzilla**
Reporter: *Hoang Le*
Status: *NEW*
Severity: *minor*
Assigned to: *Clark Barrett*
Component: *Arrays*
Milestone: *---*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[test.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/426_test.smt2)_ (This query corresponds to the path to assert(0); in https://github.com/klee/klee/blob/master/test/Feature/ExprLogging.c, ID 426)

On 2017-04-11 08:23:41 -0700, Hoang Le wrote:
> Created attachment 426
> This query corresponds to the path to assert(0); in https://github.com/klee/klee/blob/master/test/Feature/ExprLogging.c
> 
> A bit on the background: I'm using CVC4 with KLEE, default CVC4 is much slower than other solvers, so I have looked up the options used for QF\_ABV in SMTCOMP 2016, where CVC4 performed pretty well. With \-\-arrays\-weak\-equiv the performance is noticeably better, but sometimes the produced model seems to be wrong.
> 
> For the attached SMT2 query: 
> ./cvc4 test.smt2 \-\-check\-models is okay 
> but
> ./cvc4 test.smt2 \-\-arrays\-weak\-equiv \-\-check\-models produces:
> 
> CVC4 threw an "unexpected" exception.
> terminate called after throwing an instance of 'CVC4::InternalErrorException'
>   what():  Internal error detected
> void CVC4::TheoryEngine::checkTheoryAssertionsWithModel()
> ../../../../src/theory/theory\_engine.cpp:2223:
> 
>   
> THEORY\_BV has an asserted fact that the model doesn't satisfy.
> The fact: (let ((\_let\_0 (store (store unnamed (\_ bv1 32) (\_ bv97 8)) (concat (select idx.3 (\_ bv3 32)) (concat (select idx.3 (\_ bv2 32)) (concat (select idx.3 (\_ bv1 32)) (select idx.3 (\_ bv0 32))))) (\_ bv0 8)))) (let ((\_let\_1 (concat ((\_ extract 5 0) (select idx.0 (\_ bv3 32))) (concat (select idx.0 (\_ bv2 32)) (concat (select idx.0 (\_ bv1 32)) (concat (select idx.0 (\_ bv0 32)) (\_ bv0 2))))))) (let ((\_let\_2 (concat ((\_ extract 7 7) (select unnamed (\_ bv0 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv0 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv0 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv0 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv0 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv0 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv0 32))) ((\_ extract 7 7) (select unnamed (\_ bv0 32)))))))))))) (let ((\_let\_3 (concat ((\_ extract 5 0) (select idx.2 (\_ bv3 32))) (concat (select idx.2 (\_ bv2 32)) (concat (select idx.2 (\_ bv1 32)) (concat (select idx.2 (\_ bv0 32)) (\_ bv0 2))))))) (let ((\_let\_4 (concat ((\_ extract 7 7) (select unnamed (\_ bv3 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv3 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv3 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv3 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv3 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv3 32))) (concat ((\_ extract 7 7) (select unnamed (\_ bv3 32))) ((\_ extract 7 7) (select unnamed (\_ bv3 32)))))))))))) (let ((\_let\_5 (store (store (store (store (store (store (store (store const\_arr1 \_let\_1 (select unnamed (\_ bv0 32))) (bvadd \_let\_1 (\_ bv3 32)) \_let\_2) (bvadd \_let\_1 (\_ bv2 32)) \_let\_2) (bvadd \_let\_1 (\_ bv1 32)) \_let\_2) \_let\_3 (select unnamed (\_ bv3 32))) (bvadd \_let\_3 (\_ bv3 32)) \_let\_4) (bvadd \_let\_3 (\_ bv2 32)) \_let\_4) (bvadd \_let\_3 (\_ bv1 32)) \_let\_4))) (\= (concat (select \_let\_5 (\_ bv51 32)) (concat (select \_let\_5 (\_ bv50 32)) (concat (select \_let\_5 (\_ bv49 32)) (select \_let\_5 (\_ bv48 32))))) (concat (select \_let\_0 (\_ bv3 32)) (concat (select \_let\_0 (\_ bv2 32)) (concat (select \_let\_0 (\_ bv1 32)) (\_ bv104 8)))))))))))
> Model value: false
> 
> Aborted (core dumped)

On 2017-04-11 13:56:12 -0700, Clark Barrett wrote:
> \-\-arrays\-weak\-equiv is not compatible with models.  This is a known issue.  However, we should fail more gracefully, so I'm leaving this bug open.

On 2017-06-30 20:20:11 -0700, Clark Barrett wrote:
> test

**Comment by 4tXJ7f** [comment] 2020-06-01 00:02
This is a duplicate of #2007. I am marking this issue as a duplicate since the newer issue's title is more to the point.

**Closed by 4tXJ7f** 2020-06-01 00:02 UTC
Labels: minor
