### ISSUE TITLE
Fatal failure at proof/theory_proof.cpp:671 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4361] opened 2020-04-19 11:35 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_AUFNIA)
(declare-fun i0 () Int)
(set-option :proof true)
(declare-const i1 Int)
(declare-const arr (Array Int Int))
(assert (! (= (> (select (store arr i0 i1) 0) i1) true true (= arr (store arr 0 i1)) true true) :named IP_54))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
(satlem _ _ (ast _ _ _ .a3 (\ .l7 (asf _ _ _ .a2 (\ .l4 Fatal failure within virtual void CVC4::LFSCTheoryProofEngine::printTheoryLemmas(const IdToSatClause&, std::ostream&, std::ostream&, CVC4::ProofLetMap&) at /home/peisen/test/tofuzz/CVC4/src/proof/theory_proof.cpp:671
Check failure

 recipe.wasRewritten(missingAssertion->negate())

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
