### ISSUE TITLE
Fatal failure at proof/resolution_bitvector_proof.cpp:246 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4356] opened 2020-04-19 09:20 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_BV)
(declare-fun _substvar_93_ () (_ BitVec 1))
(declare-fun _substvar_95_ () (_ BitVec 1))
(declare-fun _substvar_111_ () (_ BitVec 1))
(set-option :proof true)
(declare-const bv_6-0 (_ BitVec 6))
(assert (! (= #b010111 #b010111 bv_6-0) :named IP_2))
(assert (! (= _substvar_95_ _substvar_93_ _substvar_111_ ((_ extract 0 0) bv_6-0) (bvsrem (bvcomp (_ bv0 1) (_ bv0 1)) ((_ extract 0 0) bv_6-0))) :named IP_12))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
..
(@ letBvc0 (bvc b0 (bvc b1 (bvc b0 (bvc b1 (bvc b1 (bvc b1 bvn))))))
(@ letBvc1 (bvc b1 bvn)
(@ letBvc2 (bvc b0 bvn)

 ;; Printing the global let mapFatal failure within virtual void CVC4::proof::ResolutionBitVectorProof::finalizeConflicts(std::vector<CVC4::Expr>&) at /home/peisen/test/tofuzz/CVC4/src/proof/resolution_bitvector_proof.cpp:246
Unreachable code reached
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
