### ISSUE TITLE
Fatal failure at theory/bv/bitblast/bitblast_strategies_template.h:857 (proof, decision-use-weight)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4349] opened 2020-04-19 08:48 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_AUFBV)
(set-option :proof true)
(set-option :decision-use-weight true)
(declare-const arr (Array (_ BitVec 8) Bool))
(assert (! (select (store arr (_ bv133 8) (bvslt (_ bv0 8) ((_ zero_extend 0) (_ bv133 8)))) (_ bv133 8)) :named IP_44))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within void CVC4::theory::bv::DefaultZeroExtendBB(CVC4::TNode, std::vector<_RealType>&, CVC4::theory::bv::TBitblaster<T>*) [with T = CVC4::NodeTemplate<true>; CVC4::TNode = CVC4::NodeTemplate<false>] at /home/peisen/test/tofuzz/CVC4/src/./theory/bv/bitblast/bitblast_strategies_template.h:857
Unimplemented code encountered
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:52
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:52 UTC
