### ISSUE TITLE
Fatal failure at proof/arith_proof.cpp:962 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4348] opened 2020-04-19 08:46 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_NRA)
(set-option :proof true)
(declare-const r8 Real)
(declare-const r9 Real)
(declare-const r15 Real)
(assert (! (<= r8 0.0 0.0 0.0 8306.0) :named IP_26))
(assert (! (> r8 (* r9 r15) 27958.72) :named IP_34))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
..
;  Linear Polynomial Proof Conversions
  (@ pf_aff.l6 (aff_>_from_term _ _ _ _ 
    (is_aff_- _ _ _ _ _ 
      (is_aff_+ _ _ _ _ _ 
        (is_aff_mul_c_L _ _ _ (~ 1/1) (is_aff_var_real r8))Fatal failure within static void CVC4::LFSCArithProof::printLinearMonomialNormalizer(std::ostream&, const Node&) at /home/peisen/test/tofuzz/CVC4/src/proof/arith_proof.cpp:962
Unreachable code reachedInvalid operation NONLINEAR_MULT in linear monomial
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:52
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:52 UTC
