### ISSUE TITLE
Fatal failures at src/smt/term_formula_removal.cpp:71

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#5739] opened 2021-01-05 07:55 UTC
```
[700] % cvc4 -q --check-unsat-cores small.smt2
Fatal failure within CVC4::theory::TrustNode CVC4::RemoveTermFormulas::run(CVC4::Node, std::vector<CVC4::theory::TrustNode>&, std::vector<CVC4::NodeTemplate<true> >&, bool) at /local/suz-local/software/CVC4/src/smt/term_formula_removal.cpp:71
Check failure

 processed.find(trn.getProven()) == processed.end()

Aborted
[701] % cat small.smt2
(declare-fun a () Float32)
(declare-fun b () (_ BitVec 32))
(assert (forall ((c (_ BitVec 32))) (not (xor (= a (fp ((_ extract 31
  31) c) ((_ extract 30 23) c) ((_ extract 22 0) c))) (= (_ bv0 32)
  (bvxnor (_ bv134217728 32) ((_ extract 31 0) (bvor (_ bv8388608 64)
  (bvand (_ bv8388607 64) ((_ sign_extend 32) c)))))) (bvsge ((_
  zero_extend 32) (bvand (_ bv2147483647 32) c)) (_ bv2139095040 64))
  (not (= (_ bv0 32) (bvand (_ bv2147483647 32) c))) (not (= (bvsmod
  (_ bv1 32) (bvadd (bvashr c (_ bv23 32)) (_ bv4294967169 32))) (_
  bv0 32)))))))
(assert (= (_ bv0 32) (bvmul (_ bv64 32) b)))
(check-sat)
[702] % 
```
Or
```
[724] % cvc4 -q small.smt2
Fatal failure within CVC4::theory::TrustNode CVC4::RemoveTermFormulas::run(CVC4::Node, std::vector<CVC4::theory::TrustNode>&, std::vector<CVC4::NodeTemplate<true> >&, bool) at /local/suz-local/software/CVC4/src/smt/term_formula_removal.cpp:71
Check failure

 processed.find(trn.getProven()) == processed.end()

Aborted
[725] % 
[725] % cat small.smt2
(set-option :seed 4)
(assert
 (forall ((b (_ BitVec 32)) (c (_ BitVec 32)) (d (_ BitVec 32)) (a (_ BitVec 32)))
  (xor (and (= (bvurem b c) d) (= (bvnand b c) a)) (bvsge a d))))
(check-sat)
[726] % 
```
Or
```
[572] % cvc4 -q small.smt2
Fatal failure within CVC4::theory::TrustNode CVC4::RemoveTermFormulas::run(CVC4::Node, std::vector<CVC4::theory::TrustNode>&, std::vector<CVC4::NodeTemplate<true> >&, bool) at /local/suz-local/software/CVC4/src/smt/term_formula_removal.cpp:71
Check failure

 processed.find(trn.getProven()) == processed.end()

Aborted
[573] % cat small.smt2
(assert
 (not
  (exists
   ((a (_ BitVec 32))
    (b (_ BitVec 32))
    (c (_ BitVec 32))
    (d (_ BitVec 32))
    (e (_ BitVec 32)))
   (distinct (bvashr c b) (bvlshr d a) e))))
(check-sat)
[574] % 
```
Commit: e0dfc0a

**Comment by martin-cs** [comment] 2021-01-05 23:37
@muchang please check if this is a duplicate of https://github.com/CVC4/CVC4/issues/5728

**Comment by muchang** [comment] 2021-01-06 08:17
Thanks, @martin-cs. it seems to be a duplicate. I will close this issue.

**Comment by muchang** [comment] 2021-01-20 13:49
The last two test cases can still trigger the assertion failure, while #5728 cannot. So I reopen this issue.

**Closed** 2021-01-20 15:56 UTC
