### ISSUE TITLE
Occasional failure with portfolio build (Bugzilla #826)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1039] opened 2017-08-19 04:46 UTC
**Imported from Bugzilla**
Reporter: *Andres Noetzli*
Status: *NEW*
Severity: *major*
Assigned to: *Andres Noetzli*
Component: *Bitvectors*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

On 2017-06-17 08:53:34 -0700, Andres Noetzli wrote:
> On benchmarks such as QF\_BV/Sage2/bench\_6147.smt2 , the portfolio build (competition version) is occasionally failing (less than every 100 tries, I'd say). I was trying to reproduce the issue in a debug build to get a stack trace but was not successful. It seems like a threading issue and is quite likely connected with the occasional Travis failure that we have.

**Comment by aniemetz** [comment] 2018-06-20 23:29
Duplicate of #990

**Closed by aniemetz** 2018-06-20 23:29 UTC
Labels: major
