### ISSUE TITLE
Fatal failure at bitblast_strategies_template.h:188

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4090] opened 2020-03-15 04:06 UTC
Hi,
For this formula:
~~~~
(set-logic QF_ABV)
(set-option :synth-rr-prep true)
(set-option :bv-div-zero-const false)
(set-option :segv-spin true)
(set-option :bv-lazy-reduce-extf true)
(set-option :sygus-inference true)
(set-option :strict-triggers true)
(set-option :fmf-empty-sorts true)
(set-option :sygus-fair-max true)
(set-option :sygus-stream true)
(set-option :cbqi-use-inf-int true)
(set-option :sep-min-refine false)
(declare-const v0 Bool)
(declare-const v1 Bool)
(declare-const v2 Bool)
(declare-const v3 Bool)
(declare-const v4 Bool)
(declare-const v5 Bool)
(declare-const v6 Bool)
(declare-const v7 Bool)
(declare-const v8 Bool)
(declare-const v9 Bool)
(declare-const v10 Bool)
(declare-const bv_11-0 (_ BitVec 11))
(declare-const v11 Bool)
(declare-const v12 Bool)
(declare-const v13 Bool)
(declare-const v14 Bool)
(declare-const v15 Bool)
(declare-const v16 Bool)
(declare-const v17 Bool)
(declare-const v18 Bool)
(declare-const v19 Bool)
(declare-const v20 Bool)
(declare-const v21 Bool)
(declare-const v22 Bool)
(assert (or v8 v8 v8 v8))
(assert (or v8))
(assert (or (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6)))
(assert (or v8 v8 v8 v8 v8 (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6)))
(assert (or (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6)))
(assert (or v8 v8 (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) v8))
(assert (or (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6)))
(assert (or (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6)))
(assert (or (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6)))
(assert (or v8 (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) v8 v8 (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) v8 (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) v8 (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) v8 (= (bvuge (bvshl bv_11-0 bv_11-0) bv_11-0) v12 v6) v8))
(check-sat)
~~~~

CVC4 throws out a fatal failure:
~~~~
Fatal failure within void CVC4::theory::bv::UndefinedTermBBStrategy(CVC4::TNode, std::vector<_RealType>&, CVC4::theory::bv::TBitblaster<T>*) [with T = CVC4::NodeTemplate<true>; CVC4::TNode = CVC4::NodeTemplate<false>] at /home/peisen/test/tofuzz/CVC4/src/./theory/bv/bitblast/bitblast_strategies_template.h:188
Unreachable code reached
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: 3e7c4419ac

**Comment by ajreynol** [comment] 2020-03-15 13:57
Are the options and benchmark minimized here?

**Comment by zhendongsu** [comment] 2020-03-15 14:22
#4097 has a much smaller repro

**Comment by ajreynol** [comment] 2020-03-18 20:25
Marking duplicate of #4097.

**Closed by ajreynol** 2020-03-18 20:25 UTC
Labels: more information needed
