### ISSUE TITLE
Switching option bitblast from eager to lazy produces segfault.

### ISSUE THREAD

**Issue by aniemetz** [CVC4/CVC4#1196] opened 2017-10-03 22:57 UTC
Setting option bitblast to lazy after it has been set to eager produces a segfault. I added the following testcase to the system tests on branch bbsetoptsegv of my CVC4 fork  (see https://github.com/aniemetz/CVC4/commit/cfcc22ec3ef7cc8d5a8cbe0a0e3109acaeff07c7):

```
#include "smt/smt_engine.h"
using namespace std;
using namespace CVC4;                                                           

int main() {
  ExprManager em;
  SmtEngine smt(&em);

  smt.setOption("bitblast", SExpr("eager"));
  smt.setOption("bitblast", SExpr("lazy"));

  Expr x = em.mkVar("x", em.mkBitVectorType(2));
  Expr y = em.mkVar("y", em.mkBitVectorType(2));
  Expr zx = em.mkExpr (kind::BITVECTOR_CONCAT, x, y);
  Expr zy = em.mkExpr (kind::BITVECTOR_CONCAT, y, x);
  Expr eq = em.mkExpr(kind::DISTINCT, zx, zy);
  smt.assertFormula (eq);
  Result res = smt.checkSat ();
                                                                                
  return 0;
}
```
I can not reproduce this behavior with smt2 input.

**Comment by ajreynol** [comment] 2018-10-16 17:32
Perhaps close due to #2621?

**Comment by aniemetz** [comment] 2018-10-16 17:34
Did you check if the above file stile produces a segfault? If not, then it is fixed.

**Comment by ajreynol** [comment] 2018-10-16 20:20
I can confirm this is fixed now.

**Closed by ajreynol** 2018-10-16 20:20 UTC
Labels: bug
