### ISSUE TITLE
Fatal failures at src/theory/uf/equality_engine_iterator.cpp:104

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4370] opened 2020-04-21 10:07 UTC
Hi,
For the following formula:
~~~~
(declare-const v6 Bool)
(declare-const i4 Int)
(declare-const i7 Int)
(declare-const i10 Int)
(declare-const i11 Int)
(declare-fun st0 () (Set Int))
(declare-fun st1 () (Set Int))
(declare-fun st3 () (Set Int))
(declare-fun st4 () (Set Int))
(declare-fun st5 () (Set Int))
(declare-fun st7 () (Set Int))
(declare-fun st8 () (Set Int))
(declare-fun st12 () (Set Int))
(declare-const i12 Int)
(declare-const v19 Bool)
(declare-const i16 Int)
(declare-const i17 Int)
(declare-const v71 Bool)
(assert (> (card (intersection (union st7 st1) st1)) 0))
(assert (! (or (subset st1 st7) (subset st7 st4) (subset st3 st5)) :named IP_216))
(check-sat-assuming ((! (or v71 (= (- (abs i11)) 402) (=> v6 (<= 731 396))) :named IP_112) (! (or (or (subset (union (union st7 st1) st1) st7) (> (- i4 33 i4 0) 0) (= (xor true (distinct 24 (abs 449)) true true (> 85 396)) (<= 469 33) true false (< 731 396)) (< (* i17 i16 i4 (* (abs i11) (- i4 33 i4 0) i12 i7 i12)) 182) (subset st7 (intersection (intersection st4 st0) st12)) (subset (union (union st3 st8) st8) st5) (> 85 396) false (=> true false) false false) v19 (> 986 i10)) :named IP_116)))
~~~~

CVC4 throws out a fatal failure at equality_engine.cpp:2387 (--sets-ext)
~~~~
Fatal failure within CVC4::theory::eq::EqClassIterator& CVC4::theory::eq::EqClassIterator::operator++() at /home/peisen/test/tofuzz/CVC4/src/theory/uf/equality_engine.cpp:2387
Check failure

 d_start == d_ee->getEqualityNode(d_current).getFind()

Aborted (core dumped)

~~~~

OS: Ubuntu 16.04
Commit: ad7907adf

>

**Comment by nafur** [comment] 2020-07-23 16:06
It seems this issue has been fixed in the meantime:
```
$ bin/cvc4 --sets-ext test.smt2 
test.smt2:1.13: No set-logic command was given before this point.
test.smt2:1.13: CVC4 will make all theories available.
test.smt2:1.13: Consider setting a stricter logic for (likely) better performance.
test.smt2:1.13: To suppress this warning in the future use (set-logic ALL).
sat
```

**Comment by nafur** [comment] 2020-07-23 17:01
Issue is still there on current master with the following input:
```
(declare-fun st1 () (Set Int))
(declare-fun st7 () (Set Int))
(assert (> 0 (card (intersection st1 (union st7 st1)))))
(assert (subset st1 st7))
(check-sat)
```

**Comment by rainoftime** [comment] 2020-09-24 10:48
At commit 3075a8e20dba
~~~~
$ ./cvc4 --strings-exp -q xx.smt2
Fatal failure within void CVC4::theory::eq::EqualityEngine::addTriggerPredicate(CVC4::TNode) at /home/peisen/test/tofuzz/CVC4/src/theory/uf/equality_engine.cpp:1741
Check failure

 d_congruenceKinds.tst(predicate.getKind())
No point in adding non-congruence predicates
Aborted

$ cat xx.smt2
(declare-datatypes ((a 0)) (((b))))
(define-fun v () (Seq Bool) (as seq.empty (Seq Bool)))
(declare-fun e () (Seq a))
(define-fun w () Int (seq.len e))
(define-fun x () (Seq a) (seq.extract e 1 (- w 1)))
(define-fun i () (Seq a) (seq.extract x 1 (- (seq.len x) 1)))
(define-fun y () (Seq Bool) (ite (= 0 (seq.len i)) v (seq.unit true)))
(define-fun m () (Seq Bool) (seq.++ (seq.unit false) y))
(define-fun n () (Seq Bool) (ite (= 0 (seq.len x)) v m))
(define-fun o () (Seq Bool) (seq.++ (seq.unit false) n))
(define-fun p () (Seq Bool) (ite (= 0 w) v o))
(define-fun s () (Seq Bool) (seq.extract p 1 (- (seq.len p) 1)))
(define-fun u () (Seq Bool) (seq.extract s 1 (- (seq.len s) 1)))
(assert (not (seq.nth u 0)))
(check-sat)
~~~~

**Comment by ajreynol** [comment] 2021-03-10 15:52
The sequence benchmark above no longer is an issue on master.

**Comment by ajreynol** [comment] 2021-03-21 12:50
I did not mean to close this issue, I meant that the one benchmark involving sequences is not an issue now, but the others are.  Regardless, this is now a duplicate of the new one, I've linked the two.

**Comment by rainoftime** [comment] 2021-03-21 13:09
At bdc92b3
~~~~
(declare-fun st3 () (Set String))
(declare-fun st9 () (Set String))
(assert (is_singleton (intersection st3 st9)))
(assert (< 1 (card (intersection st3 st9))))
(assert (is_singleton st9))
(check-sat)
~~~~

**Closed** 2021-04-06 12:29 UTC
