### ISSUE TITLE
Fatal failure at proof/arith_proof.cpp:922 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4351] opened 2020-04-19 08:52 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_AUFNIA)
(declare-fun _substvar_13_ () (Array Bool Int))
(declare-fun _substvar_16_ () Int)
(set-option :proof true)
(declare-const i13 Int)
(assert (! (>= _substvar_16_ 424 i13 (select _substvar_13_ true) 501) :named IP_6))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
;  Linear Polynomial Proof Conversions
  (@ pf_aff.l6 (aff_>=_from_term _ _ _ 
    (is_aff_- _ _ _ _ _ 
        (is_aff_mul_c_L _ _ _ (~ 1/1) (is_aff_var_int i13))
      (is_aff_const (~ 424/1))) (pf_reified_arith_pred _ _ (tighten_not_>=_IntInt _ _ _ _ (check_neg_of_greatest_integer_below_int (~ 424) 425) .l6)))
  (@ pf_aff.l11 (aff_>=_from_term _ _ _ 
    (is_aff_- _ _ _ _ _ Fatal failure within static void CVC4::LFSCArithProof::printLinearPolynomialNormalizer(std::ostream&, const Node&) at /home/peisen/test/tofuzz/CVC4/src/proof/arith_proof.cpp:922
Unreachable code reachedInvalid operation SELECT in linear polynomial
Aborted (core dumped)

~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:52
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:52 UTC
