### ISSUE TITLE
Fatal failure at proof/proof_manager.cpp:610 (proof, dt-stc-ind)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4359] opened 2020-04-19 09:48 UTC
Hi,
For the following formula:
~~~~
(set-logic UFNIA)
(set-option :proof true)
(set-option :dt-stc-ind true)
(declare-const i2 Int)
(assert (! (not (exists ((q0 Bool) (q1 Bool) (q2 Int)) (distinct q2 (mod 21 i2)))) :named IP_2))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
Fatal failure within virtual void CVC4::LFSCProof::toStream(std::ostream&) const at /home/peisen/test/tofuzz/CVC4/src/proof/proof_manager.cpp:610
Check failure

 atom == utils::mkTrue()

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
