### ISSUE TITLE
--fp-exp fatal failure at CVC4/src/util/floatingpoint.cpp:444 

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3622] opened 2020-01-20 18:11 UTC
Hi,
For this formula,
```
(declare-fun a () (_ FloatingPoint 47 53))
(assert (fp.eq a a))
(check-sat)
```
`cvc4 --fp-exp` throws out an fatal failure:
```
Fatal failure within static void CVC4::symfpuLiteral::traits::precondition(const prop&) at CVC4/src/util/floatingpoint.cpp:444
Check failure
 p
Aborted
```

OS: Ubuntu 18.04
Revision: c3bc4ac

**Comment by aniemetz** [comment] 2020-02-03 21:59
Duplicate of #3623.

**Closed by aniemetz** 2020-02-03 21:59 UTC
Labels: duplicate
