### ISSUE TITLE
CVC4 throws AssertionException with --incremental --tlimit (Bugzilla #797)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1010] opened 2017-08-19 04:40 UTC
**Imported from Bugzilla**
Reporter: *Daniel Larraz*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Cristian Mattarei*
Component: *Miscellaneous*
Milestone: *---*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[ccp17.lus.bmc.1.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/432_ccp17.lus.bmc.1.smt2)_ (SMT problem to reproduce the issue, ID 432)

On 2017-05-05 15:37:28 -0700, Daniel Larraz wrote:
> Created attachment 432
> SMT problem to reproduce the issue
> 
> Hello,
> 
> If I run CVC4 (cvc4 \-\-incremental \-\-tlimit\=10) with the attached file, and I get the following error:
> 
> CVC4 threw an "unexpected" exception.
> terminate called after throwing an instance of 'CVC4::AssertionException'
>   what():  Assertion failure.
> void CVC4::ResourceManager::beginCall()
> ../../../../../src/util/resource\_manager.cpp:215:
> 
>   d\_cumulativeTimer.on()
> 
> Same problem with \-\-tear\-down\-incremental\=1 \-\-tlimit\=10.
> 
> I know \-\-tlimit\-per makes more sense in incremental mode, but the error just showed up.
> 
> Best,
> Daniel

**Comment by ajreynol** [comment] 2019-08-28 22:06
Marking duplicate of #2908.

**Closed by ajreynol** 2019-08-28 22:06 UTC
Labels: duplicate, feature
