### ISSUE TITLE
Invalid model for QF_LRA formula (theory_engine.cpp:2283) (check-models, finite-model-find)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4467] opened 2020-05-05 14:13 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_LRA)
(set-option :finite-model-find true)
(declare-fun _substvar_19_ () Real)
(declare-fun _substvar_26_ () Real)
(assert (>= _substvar_26_ (/ 0.0 0.0) _substvar_19_ 54081.0))
(check-sat)
~~~~

CVC4 throws out a fatal failure:
~~~~
Fatal failure within void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool) at /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:2283
Internal error detectedTHEORY_ARITH has an asserted fact that the model doesn't satisfy.
The fact: (>= (+ (* (- 1.0) _substvar_19_) (divByZero 0.0)) 0.0)
Model value: false

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ad7907adf

**Comment by 4tXJ7f** [comment] 2020-05-31 21:39
This issue is a duplicate of #4462. Please see my [comment](https://github.com/CVC4/CVC4/issues/4462#issuecomment-636532236) on that issue for more details.

**Closed by 4tXJ7f** 2020-05-31 21:39 UTC
