### ISSUE TITLE
Fatal failure at theory/bv/bitblast/bitblast_strategies_template.h:890 (proof, decision-use-weight)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4358] opened 2020-04-19 09:35 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_ABV)
(set-option :proof true)
(set-option :decision-use-weight true)
(declare-const arr (Array (_ BitVec 12) Bool))
(assert (! (select (store arr (_ bv0 12) (= ((_ rotate_right 1) #x1d2) (_ bv0 12) #x1d2)) (_ bv0 12)) :named IP_52))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
 Fatal failure within void CVC4::theory::bv::DefaultRotateRightBB(CVC4::TNode, std::vector<_RealType>&, CVC4::theory::bv::TBitblaster<T>*) [with T = CVC4::NodeTemplate<true>; CVC4::TNode = CVC4::NodeTemplate<false>] at /home/peisen/test/tofuzz/CVC4/src/./theory/bv/bitblast/bitblast_strategies_template.h:890
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
