### ISSUE TITLE
Model validation crash

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3425] opened 2019-11-01 08:51 UTC
Hi,
here is a formula on which  cvc4 with `--check-models` option crashes
```
(set-logic NRA)
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(declare-fun e () Real)
(declare-fun f () Real)
(declare-fun g () Real)
(declare-fun h () Real)
(declare-fun i () Real)
(declare-fun j () Real)
(assert (= (< (/ 0 (- i 2)) f) (= d 2)))
(assert (< (+ g (* 100 (- a i) (- a i)) (* (+ 100 j) (/ b e) h (- i a))) 0))
(assert (> g 0))
(assert (> 0 (/ c j)))
(check-sat)
```

```
Fatal failure within void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool) at /home/windomin/solver_binaries/cache/CVC4/src/theory/theory_engine.cpp:2229
Internal error detectedTHEORY_ARITH has an asserted fact that the model doesn't satisfy.
The fact: (= a (+ (* 2.0 i) (* (/ 1 100) kf_7) (* h termITE_5) (* (/ 1 100) (* h j termITE_5))))
Model value: false
```
OS: Ubuntu 18.04
Revision: eaca3c1

**Comment by ajreynol** [comment] 2019-11-03 22:27
Thanks for the benchmark. This is a duplicate of #2153.

**Closed** 2019-11-03 22:28 UTC
Labels: duplicate
