### ISSUE TITLE
bitblast=eager segfault

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#2467] opened 2018-09-14 23:28 UTC
This file produces a segfault with current master:

```
(set-logic QF_BV)
(set-option :bitblast "eager")
(check-sat)
```

**Comment by aniemetz** [comment] 2018-10-10 20:36
This is a duplicate of #1196.

**Closed by aniemetz** 2018-10-10 20:36 UTC
Labels: bug

**Comment by ajreynol** [comment] 2018-10-16 17:32
This is fixed with #2621.
