### ISSUE TITLE
Assertion error at src/theory/strings/core_solver.cpp:1374 on string formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5610] opened 2020-12-06 09:16 UTC
Hi, for the following formula,
cvc4 a3395c1
~~~~
(declare-fun str5 () String)
(declare-fun str6 () String)
(declare-fun str10 () String)
(declare-fun str11 () String)
(assert (not (= str6 str5)))
(assert (xor true true true (distinct "" str6 (str.++ (str.from_int (str.len (str.++ str10 str11))) (str.++ str11 "tCEuUoROixKOUo" "wuPPPbRfGeDdhIafLoGcubFWViLfPaiooaekchLBSfgSaprsJijOvY"))) (str.prefixof (str.++ "tCEuUoROixKOUo" "wuPPPbRfGeDdhIafLoGcubFWViLfPaiooaekchLBSfgSaprsJijOvY") (str.++ str5 (str.++ (str.from_int (str.len (str.++ str10 str11))) (str.++ "tCEuUoROixKOUo" "wuPPPbRfGeDdhIafLoGcubFWViLfPaiooaekchLBSfgSaprsJijOvY"))))))
(check-sat)
~~~~
~~~~
./cvc4 -i -q --strings-exp --check-models xx.smt2
Fatal failure within void CVC4::theory::strings::CoreSolver::processSimpleNEq(CVC4::theory::strings::NormalForm&, CVC4::theory::strings::NormalForm&, unsigned int&, bool, unsigned int, std::vector<CVC4::theory::strings::CoreInferInfo>&, CVC4::TypeNode) at /home/CVC4/src/theory/strings/core_solver.cpp:1374
Check failure

 nfiv.size() == nfjv.size()

Aborted
~~~~

**Comment by nafur** [comment] 2020-12-07 12:09
```
(declare-fun r () String)
(declare-fun tr () String)
(declare-fun t () String)
(assert (not (= tr r)))
(assert (= (str.prefixof "b" (str.++ r (str.++ (str.from_int (str.len (str.++
  tr t))) "b"))) (= tr (str.++ (str.from_int (str.len (str.++ tr t))) (str.++
  t "b")))))
(check-sat)
```

**Comment by ajreynol** [comment] 2020-12-08 16:19
This is a very tricky issue, caused by the use of substitute for symbolic lemmas traversing arithmetic symbols, which leads to an I_NORM_S inference being ineffective, leading to a term being marked as congruent when congruence does not apply, and hence leading to normal forms that are not truly normalized.  A fix is to make this line: https://github.com/CVC4/CVC4/blob/master/src/theory/strings/inference_manager.cpp#L199 not traverse over symbols that strings is not doing congruence over (e.g. arithmetic).

**Closed** 2021-02-10 15:11 UTC
