### ISSUE TITLE
Sygus problems for NIA logic

### ISSUE THREAD

**Issue by iwob** [CVC4/CVC4#1197] opened 2017-10-04 01:05 UTC
Hello,
I have a problem to solve which requires NIA instead of LIA. I'm aware that Sygus competition does not have a track for this logic and that this logic is currently not accepted by CVC4 for sygus problems. Is this a "fundamental" constraint of the algorithm you use, or rather a simple blockade on the level of language grammar? If the former, then this issue should be closed, and if the latter, then you can treat it as a feature request. :) Thank you for your attention.

**Comment by ajreynol** [comment] 2017-10-11 15:32
Thanks for the suggestion.

The short answer is that we can provide heuristic support for NIA + SyGuS, but with no guarantees.  I have removed the front-end restrictions so that this is possible in pull request #1226.

Both modes of synthesis (--cegqi-si=all and --cegqi-si=none) I mentioned earlier can potentially work with non-linear, although again no guarantees since NIA is undecidable.  If you use SyGuS+NIA, I would currently recommend additionally using the option:

--nl-ext-tplanes

which enables some heuristic methods for non-linear that should help increase the success rate.

My initial impression is that the single-invocation "fast" synthesis algorithm should work relatively well if the non-linear is in the variables, and not the functions-to-synthesize, in other words, we can probably handle this:
(constraint (= (f x) (* t t)))
but will have lower success rates on things like this:
(constraint (= (* (f x) (f x)) t))

Regardless, this is new territory, I would be interested to hear your experience with this. 

This will be available once pull request #1226 is merged to master.

**Comment by iwob** [comment] 2017-10-12 00:03
Thank you very much for the work on this issue and suggestion of useful options. As you say heuristic support for NIA is the best one can hope for since it is undecidable. However, in many practical applications it will be solved quickly, I think.

I will test this on my problem once the PR is merged.

**Comment by ajreynol** [comment] 2017-10-12 20:51
The PR is merged now, let me know how it goes.

**Closed by ajreynol** 2017-10-12 20:51 UTC
Labels: feature, normal

**Comment by iwob** [comment] 2017-10-14 18:09
It seems your nightly builds stopped being produced (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/).

**Comment by timothy-king** [comment] 2017-10-15 00:00
Opened #1248 for the nightly builds.

**Comment by iwob** [comment] 2017-10-17 22:33
Unfortunately, CVC4 returns unknown for my problem. I attach below the script in case you are interested or want to check something. The problem is basically to find any confirmation measure - encoded are the minimal required conditions. There are many correct answers, for example -b * c + d * a.

```
(set-logic NIA)

(synth-fun rsconf ((a Int) (b Int) (c Int) (d Int)) Int
    ((Start Int (a b c d
        (+ Start Start)
        (- Start Start)
        (* Start Start))))
)

(define-fun ElementsSum () Int 32)

(declare-var a Int)
(declare-var b Int)
(declare-var c Int)
(declare-var d Int)

(constraint (>= a 0))
(constraint (>= b 0))
(constraint (>= c 0))
(constraint (>= d 0))
(constraint (= (+ a b c d) ElementsSum))



(define-fun condition ((a Int)(b Int)(c Int)(d Int)) Int 
    (- (* a ElementsSum) (* (+ a b) (+ a c)))
)

(constraint (=> (> (condition a b c d) 0)
                (> (rsconf a b c d) 0)))

(constraint (=> (< (condition a b c d) 0)
                (< (rsconf a b c d) 0)))

(constraint (=> (= (condition a b c d) 0)
                (= (rsconf a b c d) 0)))

(check-synth)
```

**Comment by ajreynol** [comment] 2017-10-17 22:48
Thanks for the problem. 

The problem you sent is probably not what you intended.  The issue is that a,b,c,d are interpreted as universal variables.  So in other words, the conjecture you are asking is:
"Find a function rsconf such that for all a,b,c,d, we have that a>=0 and b>=0 ...."
This is infeasible no matter what "..." is, since CVC4 finds it does not hold for a = -1. 

What you may have intended is something like this, where notice I've turned the constraints into preconditions for others.

...

(set-logic NIA)

(synth-fun rsconf ((a Int) (b Int) (c Int) (d Int)) Int
    ((Start Int (a b c d
        (+ Start Start)
        (- Start Start)
        (* Start Start))))
)

(define-fun ElementsSum () Int 32)

(declare-var a Int)
(declare-var b Int)
(declare-var c Int)
(declare-var d Int)

(define-fun precondition ((a Int)(b Int)(c Int)(d Int)) Bool
  (and (>= a 0) (>= b 0) (>= c 0) (>= d 0) (= (+ a b c d) ElementsSum)))

(define-fun condition ((a Int)(b Int)(c Int)(d Int)) Int 
    (- (* a ElementsSum) (* (+ a b) (+ a c)))
)

(constraint (=> (and (precondition a b c d) (> (condition a b c d) 0))
                (> (rsconf a b c d) 0)))

(constraint (=> (and (precondition a b c d) (< (condition a b c d) 0))
                (< (rsconf a b c d) 0)))

(constraint (=> (and (precondition a b c d) (= (condition a b c d) 0))
                (= (rsconf a b c d) 0)))

(check-synth)

...

For this problem, CVC4 answers this, in ~66 seconds on my machine:

unsat
(define-fun rsconf ((a Int) (b Int) (c Int) (d Int)) Int (- (* a d) (* c b)))

**Comment by ajreynol** [comment] 2017-10-17 22:51
Btw, do feel free to send other benchmarks (say if you had a representative set from your application), since I could potentially add these to regression tests I use when updating the SyGuS solver.  As there are no non-linear + SyGuS regression currently, this would be great to have.

**Comment by iwob** [comment] 2017-10-17 23:21
You are right,  thank you for pointing out the error in my task specification.

The story is that I was talking with a colleague and we were wondering, how SMT solvers could help him with his work. He is currently searching for confirmation measures with certain properties. I thought that Sygus format may allow him to easily describe the mathematical structure of the measures (grammar) and constraints they should be subject to. This specification was the very first test, if Sygus tools could be used for this. Perhaps in the future there will be more benchmarks. This benchmark can be easily made into a series by changing ElementsSum. I'm not sure, if higher values make the problem more difficult.

On a side note, it turns out that what my colleague would really want is to find all measures over the certain grammar (with limited recursion depth) that meet some constraints, and not only a single such measure. Does CVC4 supports something like this? And if not, do you maybe know a tool that will readily do this? If such a tool doesn't exist I think I will just write one, since this is basically verification for programs enumerated over a certain grammar.

**Comment by ajreynol** [comment] 2017-10-17 23:57
Actually, you're in luck, I added this feature just a week ago.

The option to use is "--sygus-stream". With this option, CVC4 will output/"stream" multiple solutions to your conjecture (which it searches for in order of increasing term size).

However, the part that is missing is to tell CVC4 to abort when it reaches a certain term size, but this should be easy to add. (I've opened #1261).

**Comment by iwob** [comment] 2017-10-18 00:21
It seems I really am. If this option guarantees that all such functions are found, then this is exactly what is needed.

**Comment by ajreynol** [comment] 2017-10-18 00:26
It guarantees that "essentially" all functions will be found (up to a bound).  However, it will not enumerate some functions that it finds are equivalent to others, e.g. it will not enumerate both:

(define-fun rsconf ((a Int) (b Int) (c Int) (d Int)) Int (- (* a d) (* c b)))
and
(define-fun rsconf ((a Int) (b Int) (c Int) (d Int)) Int (- (* d a) (* c b)))

Btw, forgot to mention, the option --sygus-stream is not compatible with --cegqi-si=all.

**Comment by iwob** [comment] 2017-10-18 00:35
That's even better, because we are interested in the semantics, not syntax. But I guess there will be some less trivial semantically redundant expressions, which we will have to filter out afterwards. I have code for checking this, but maybe I'm so lucky that there is already an option for this?

By the way I noticed that CVC4 wraps results in let expressions. Is there an option to turn this off?

**Comment by ajreynol** [comment] 2017-10-18 01:48
To turn off let printing, you can use --default-dag-thresh=0.

**Comment by ajreynol** [comment] 2017-10-18 01:50
Btw, the solutions from SyGuS should not contain redundant operations, I would be interested if you could simplify them further, since this would mean my search algorithms were non-ideal :)

**Comment by iwob** [comment] 2017-10-18 17:39
If I find something I will let you know. :)

I also noticed something interesting while trying to solve my benchmark with different options. CVC4 with the parameters below solves this problem fast (in ~60s):
```./cvc4-2017-10-18-x86_64-linux-opt --lang=sygus --nl-ext-tplanes  rsconf.sl```

while with the following it uses increasingly more memory and seems to run indefinitely (after 5 minutes memory usage was around 4 GB):
```./cvc4-2017-10-18-x86_64-linux-opt --lang=sygus --nl-ext-tplanes  --cegqi-si=all rsconf.sl```

**Comment by ajreynol** [comment] 2017-10-18 22:29
Right, the --cegqi-si=all option has not (yet) been adapted to non-linear, so this isn't too surprising.
