### ISSUE TITLE
Solution soundness issue QF_FP formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5524] opened 2020-11-25 05:02 UTC
Hi, for the following formula,
~~~~
(set-logic QF_FP)
(declare-fun fpv5 () Float32)
(assert (fp.eq (fp.mul RTP fpv5 fpv5) ((_ to_fp 8 24) RTN 0.04)))
(check-sat)
~~~~
cvc4 25762974521 yields `sat`, but z3 gives `unsat`.
cvc4 gives the following model.
However, after feeding the model to z3, it still yields `unsat`.
~~~~
(define-fun fpv5 () (_ FloatingPoint 8 24) (fp #b0 #b01111100 #b10011001100110011001101))
~~~~

----
Update: MathSAT5 also yields `unsat`

**Comment by martin-cs** [comment] 2020-11-27 22:19
Hi @rainoftime ,

I'm having a hard time reproducing this issue.  I have tried the 1.8 release and the most recent nightly http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-11-20-x86_64-linux-opt from last week.  Both of them return `unsat`.

Can you reproduce this on other versions / builds?  Do you have reason to suspect the particular version you are working with?  How is it configured and built?

**Comment by martin-cs** [comment] 2020-11-27 23:28
Only a handful of things were merged after the 20th Nov but before the 25th.  This window does include some of @aniemetz 's refactorings of the handling of floating-point constants.

@rainoftime Please can you post the output of your problematic version running:
```
(set-option :produce-models true)
(set-logic QF_FP)
(declare-fun fpv5 () Float32)
(declare-fun conv () Float32)
(assert (= ((_ to_fp 8 24) RTN 0.04) conv))
(declare-fun prod () Float32)
(assert (= prod (fp.mul RTP fpv5 fpv5)))
;(assert (fp.eq prod conv))
(check-sat)
(get-model)
```

I think `conv` should be `(fp #b0 #b01111010 #b01000111101011100001010)`.

**Comment by rainoftime** [comment] 2020-11-28 01:15
I used the last commit.


@martin-cs After running the instance you put, the output is 
~~~~
sat
(
(define-fun fpv5 () (_ FloatingPoint 8 24) (fp #b0 #b00000000 #b00000000000000000000000))
(define-fun conv () (_ FloatingPoint 8 24) (fp #b0 #b01111010 #b01000111101011100001011))
(define-fun prod () (_ FloatingPoint 8 24) (fp #b0 #b00000000 #b00000000000000000000000))
)
~~~~

**Comment by martin-cs** [comment] 2020-11-28 18:31
Thanks for running that.  It looks like an off-by-one error in conversion of rational to float.  I will investigate further.

**Comment by aniemetz** [comment] 2020-12-02 18:36
Looks like my refactor did break something (I checked out the commit previous to the refactor and it answers unsat). I'll investigate.

**Comment by aniemetz** [comment] 2020-12-02 20:50
Pinpointed the culprit commit: 6a02b2e28ee8d0560c923eaf0073c2fdce8fbfa2

**Closed** 2020-12-02 23:34 UTC
