### ISSUE TITLE
Fatal failure at proof/proof_manager.cpp:582 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4362] opened 2020-04-19 12:38 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_NIA)
(assert false)
(check-sat)
(get-proof)
~~~~

When running 
~~~~
cvc4 --check-proofs fname.smt2
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
Fatal failure within virtual void CVC4::LFSCProof::toStream(std::ostream&) const at /home/peisen/test/tofuzz/CVC4/src/proof/proof_manager.cpp:582
Check failure

 !d_satProof->proofConstructed()

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:50
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:50 UTC
