### ISSUE TITLE
Segmentation faults in incremental mode

### ISSUE THREAD

**Issue by daniel-larraz** [CVC4/CVC4#2401] opened 2018-08-28 20:27 UTC
CVC4 crashes with a segmentation fault when I run it in incremental mode with the attached [SMT2 problems](https://github.com/CVC4/CVC4/files/2329746/Segfaults.zip).

**Comment by 4tXJ7f** [comment] 2018-09-01 02:34
@ajreynol and I have been able to track the segfault back to ITE compression. While we are working on a fix, you can disable it with `--no-simp-ite-compress` (disabling this option may result in worse performance with deeply nested ITEs).

**Comment by daniel-larraz** [comment] 2018-09-01 02:36
Thanks for the info!

**Comment by daniel-larraz** [comment] 2018-09-12 16:52
I made some experiments to check: 1) how disabling ITE compression affects the results over Kind 2 benchmarks, 2) if segfaults do really not occur when the option is disabled:

1) The number of Invalid instances solved is the same, but it takes longer (732s vs 493s). For Valid problems, it gains 1 instance, but it loses 13.

2) This is harder to check because the segfaults only happen when I use some specific CVC4 binaries. I could reproduce it when running Kind 2 with a locally compiled version of CVC4 based on git master version 94e3d283. If I change Kind 2 so that CVC4-94e3d283 is run with `--no-simp-ite-compress`, the segfaults do not occur.

**Comment by ajreynol** [comment] 2020-03-18 20:38
Downgrading to minor since we don't enable this technique by default anymore.

**Comment by spamdaemon** [comment] 2020-06-15 14:55
I was asked by my employer to look into this issue, to see if it was fixed. We need to be certain that we can enable compression. Even though I could not reproduce the issue with the test files on master, I believe that the underlying issue may be not be fixed and I suspect compress just turns on a latent bug somewhere else. 
I'll share my findings here, and hopefully they'll be of use to you.

I configured the code as follows, in order to make debugging simpler:
```
./configure --prefix=/home/str/projects/CVC4/local --disable-thread-support --enable-static-binary --with-build=debug --disable-assertions
```

I started a git bisect and determined that the most recent bad commit was 1752aeb263a986bf437bb04029474b41987450d2, followed by the good commit 4e4068f1d29ddc1ffe0bde8e6f2cf3094fd6bd40, which fixes the issue, but seems unrelated to the problem. If that good commit is expected to fix this issue, I would suggest closing this issue.


Working with commit 1752aeb263a986bf437bb04029474b41987450d2 and test file `microwave06.lus.bmc.1.smt2`  (provided by the submitter), and turning on assertions, the code asserted in  `src/theory/theory_engine.cpp:1450`:
```
    Assert(d_propEngine->isSatLiteral(literal));
```

With assertions disabled, the code core dumps here:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000c11cab in CVC4::prop::CnfStream::getLiteral (this=this@entry=0x191bcd0, node=...) at ../../../../src/prop/cnf_stream.cpp:266
266	  SatLiteral literal = d_nodeToLiteralMap[node];
```

One way to fix the issue is to update ite_utilities.cpp as follows:
```
diff --git a/src/preprocessing/util/ite_utilities.cpp b/src/preprocessing/util/ite_utilities.cpp
index 66d9151df..f31afc578 100644
--- a/src/preprocessing/util/ite_utilities.cpp
+++ b/src/preprocessing/util/ite_utilities.cpp
@@ -358,9 +358,9 @@ Node ITECompressor::push_back_boolean(Node original, Node compressed)
     d_compressed[compressed] = skolem;
 
     Node iff = skolem.eqNode(rewritten);
-    d_assertions->push_back(iff);
+    d_assertions->push_back(skolem);
     ++(d_statistics.d_skolemsAdded);
-    return skolem;
+    return iff;
   }
 }
```
Not knowing enough about the assumptions made with ordering of assertions in the assertions array, I would have expected that the order of the `iff` and `skolem` nodes in that array should not matter.

Another way to fix this is to just return the rewritten node and not create the `skolem` node at all. 

I'm attaching a smaller testcase based on the `microwave06.lus.bmc.1.smt2` test case provided by the submitter. 
[fail.smt2.gz](https://github.com/CVC4/CVC4/files/4780911/fail.smt2.gz). Note, in order to get this working I had modify the code to always compress, since the number of nodes is too small. 
Also, a single small change, causes the test to pass.

Btw, enabling compression in the good commit seems to cause a substantial increase in runtime in the provided test cases. It does seem to make no difference on master, at least with these test cases.

**Comment by ajreynol** [comment] 2020-06-16 18:02
@spamdaemon Thanks for looking into this.  ITE compression is an experimental feature in CVC4, so it may indeed have bugs, as you have noticed.  Regardless, if you'd like to submit further PRs for fixes like the changed mentioned above, you are welcome to.

**Comment by nafur** [comment] 2021-02-24 14:19
As @ajreynol said, ITE compression is experimental and we thus close this issue. If there is still interest, please feel free to submit a PR.

**Closed by nafur** 2021-02-24 14:19 UTC
Labels: bug, minor
