### ISSUE TITLE
Fatal failure at theory/bv/bitblast/bitblast_strategies_template.h:897 (proof, decision-use-weight)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4346] opened 2020-04-19 08:40 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_ABV)
(set-option :proof true)
(set-option :decision-use-weight true)
(declare-const arr-4411560102834551175_8212927909086610610-0 (Array (_ BitVec 10) Bool))
(assert (! (and true true true true false (select arr-4411560102834551175_8212927909086610610-0 (bvsrem (_ bv0 10) ((_ rotate_left 2) (_ bv693 10)))) true true true true) :named IP_32))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within void CVC4::theory::bv::DefaultRotateLeftBB(CVC4::TNode, std::vector<_RealType>&, CVC4::theory::bv::TBitblaster<T>*) [with T = CVC4::NodeTemplate<true>; CVC4::TNode = CVC4::NodeTemplate<false>] at /home/peisen/test/tofuzz/CVC4/src/./theory/bv/bitblast/bitblast_strategies_template.h:897
Unimplemented code encountered
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:53
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:53 UTC
