### ISSUE TITLE
NULL pointer dereference (related to justification heuristic)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5187] opened 2020-10-02 02:26 UTC
Hi, for the following formula,
cvc nightly build throws a NPD
~~~~
$ /cvc4-2020-10-01-x86_64-linux-opt --strings-exp -i xx.smt2
unsat
unsat
unsat
unsat
CVC4 suffered a segfault.
Offending address is 0x10
Looks like a NULL pointer was dereferenced.
Aborted
$ cat xx.smt2
(set-logic QF_AUFNIA)
(declare-fun _substvar_77_ () Int)
(declare-fun _substvar_82_ () Int)
(declare-const v11 Bool)
(declare-const arr (Array Bool Int))
(push 1)
(declare-const i3 Int)
(declare-const i5 Int)
(assert (= (* 469 _substvar_77_) (div 174 (div 81 81))))
(push 1)
(assert (< 0 (* i5 i3 469 (select (store arr true 81) v11) (+ _substvar_82_ 174 81))))
(push 1)
(push 1)
(check-sat)
(pop 1)
(pop 1)
(push 1)
(check-sat)
(push 1)
(check-sat)
(pop 1)
(pop 1)
(check-sat)
(pop 1)
(pop 1)
(check-sat)
~~~~

**Comment by nafur** [comment] 2020-10-02 07:36
```
(set-logic QF_ANIA)
(declare-const b Bool)
(declare-const a (Array Bool Int))
(declare-const i Int)
(push)
(assert (= (* 2 i) (div 2 (div 2 1))))
(assert (< 0 (* (+ i 2) (select (store a true 1) b))))
(check-sat)
(pop)
(check-sat)
```
triggers
```
Fatal failure within CVC4::decision::JustificationHeuristic::SearchResult CVC4::decision::JustificationHeuristic::findSplitterRec(CVC4::TNode, CVC4::prop::SatValue) at /home/gereon/cvc4_master/src/decision/justification_heuristic.cpp:501
Check failure

 d_decisionEngine->hasSatLiteral(node)

Aborted (core dumped)
```

**Comment by rainoftime** [comment] 2020-10-02 07:39
Related  https://github.com/CVC4/cvc4-projects/issues/160

**Comment by ajreynol** [comment] 2020-10-02 12:44
`--strings-exp` implies several options, including triggering `--decision=justification`.  Notice that both issues are fixed with additionally adding `--decision=internal`.

**Comment by nafur** [comment] 2021-02-25 12:09
This particular example no longer fails since b0dd5a3adc67d72a08ca9d8d3de208840a1001a3. Note, though, that this commit changed how we deal with division, but does not touch the justification heuristic, presumably merely hiding the underlying issue.
As we have more issues that still trigger the same assertion, we close this issue and add the initial input as a regression.

**Closed** 2021-02-25 13:34 UTC
