### ISSUE TITLE
Fatal failure at theory/bv/bitblast/bitblast_strategies_template.h:335 (proof, decision-use-weight)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4355] opened 2020-04-19 09:13 UTC
Hi,
For the following formula:
~~~~
(set-logic ABV)
(set-option :proof true)
(set-option :decision-use-weight true)
(declare-const arr (Array (_ BitVec 9) Bool))
(assert false)
(assert (! (xor true true true (= true true true true true (select arr (bvsmod #b101000010 (bvnor #b101000010 #b101000010))) true true true) true true true) :named IP_29))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within void CVC4::theory::bv::DefaultNorBB(CVC4::TNode, std::vector<_RealType>&, CVC4::theory::bv::TBitblaster<T>*) [with T = CVC4::NodeTemplate<true>; CVC4::TNode = CVC4::NodeTemplate<false>] at /home/peisen/test/tofuzz/CVC4/src/./theory/bv/bitblast/bitblast_strategies_template.h:335
Unimplemented code encountered
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
