### ISSUE TITLE
FloatingPoint: RoundingMode not available for Java

### ISSUE THREAD

**Issue by kfriedberger** [CVC4/CVC4#3060] opened 2019-06-16 13:49 UTC
We are using CVC4 (recent version 2d478849d704f44f2a1f584dbc98d3731ca4e6ee) with Swig 3.0.8 and OpenJDK 1.8.0.

I have detected some FloatingPoint related methods in CVC4 and thus I am trying to create a FloatingPoint expression. 
How far is the support for FloatingPoints? Is it stable enough for production? 
Currently I am failing due to possibly missing methods in the Java API.
Do I need to enable some flags while building CVC4 to get the corresponding methods?

If the questions above are cleared, could you give a hint on the following parts:
- How can I create a FloatingPointRoundingMode? There is no method `mkConst(RoundingMode rm)` in ExprManager (I read this method somewhere in the documentation).
- Which RoundingModes for FloatingPoint operations are supported in CVC4? How can I instantiate them (from Java)?
- How can I instantiate a FloatingPoint constant expression for a `double` value (from Java)? Do I need to provide a proper BitVector or Rational for this?
- How can I instantiate a FloatingPoint constant expression for `NaN` or `Inf` (from Java)?
- Is there a possibility to round a given FloatingPoint expression to Integer expression (or comparable BitVector expression), according to a given RoundingMode?

Thanks in advance for answering.

**Comment by 4tXJ7f** [comment] 2019-06-19 02:27
@kfriedberger Thank you for bringing this to our attention. We were actually missing support for the theory of floating-point numbers in the Java API. I've created a pull request (#3063) that fixes the issue. The pull request includes an example that should cover most of your questions. It is currently not possible to create a `FloatingPoint` constant from a `double`, you have to either create it from a bit-vector (as shown in the example) or a `Rational`.

Once the pull request has been merged (or once you pulled my branch), you have to run `contrib/get-symfpu`, reconfigure CVC4 with the `--symfpu` flag and recompile to get floating-point support. The support for the theory of floating-point numbers is fairly stable for common bit-widths (single precision and double precision floats). Some uncommon bit-widths will result in assertion failures because SymFPU does not support all bit-widths yet.

Please let me know if you have any other questions.

**Comment by martin-cs** [comment] 2019-06-19 17:22
On Sun, 2019-06-16 at 06:49 -0700, Karlheinz Friedberger wrote:
> We are using CVC4 (recent version
> 2d478849d704f44f2a1f584dbc98d3731ca4e6ee) with Swig 3.0.8 and OpenJDK
> 1.8.0.
> 
> I have detected some FloatingPoint related methods in CVC4

Yes!  If you want more details we presented a paper at ETAPS about this
a few months ago.  If you have a hard time getting ahold of it, let me
know.


>  and thus I am trying to create a FloatingPoint expression. 
> How far is the support for FloatingPoints?

At the time of writing it was the most correct and probably the best
performing solver for Float32 and Float64.  I hope other solvers have
made progress since then; I hope they have.

For other formats, there are some known bugs.  At the moment none of
these are known to give incorrect results but some operations in some
formats will result in assertion failures.


>  Is it stable enough for production? 

For Float32 and Float64 I would say yes.


> Currently I am failing due to possibly missing methods in the Java
> API.
> Do I need to enable some flags while building CVC4 to get the
> corresponding methods?

You need to give configure.sh the --symfpu option and also have a copy
of symfpu ( contrib/get-symfpu will get one for you ) to get any
Floating-Point support.


I don't know much about the Java API but it seems Andres has already
addressed much of that.

> If the questions above are cleared, could you give a hint on the
> following parts:
> - How can I create a FloatingPointRoundingMode? There is no method
> `mkConst(RoundingMode rm)` in ExprManager (I read this method
> somewhere in the documentation).
> - Which RoundingModes for FloatingPoint operations are supported in
> CVC4? How can I instantiate them (from Java)?

All five that are in the standard; RTP, RTN, RTZ, RNE, RNA.


> - How can I instantiate a FloatingPoint constant expression for a
> `double` value (from Java)? Do I need to provide a proper BitVector
> or Rational for this?

In SMT-LIB the recommended way is to use BitVectors which can be
extracted directly from the in-memory representation.  I would suggest
against using rationals as rounding can give some unexpected behaviour.


> - How can I instantiate a FloatingPoint constant expression for `NaN`
> or `Inf` (from Java)?
> - Is there a possibility to round a given FloatingPoint expression to
> Integer expression (or comparable BitVector expression), according to
> a given RoundingMode?

There are two options for rounding to BitVector, one to give signed
bit-vectors and one to give unsigned BitVectors.  There is no direct
round to Integers but there is a conversion to Real and a Float->Float
round to integer.

> Thanks in advance for answering. 

Sorry for the lag.

**Comment by kfriedberger** [comment] 2019-06-19 18:53
Thank you very much for your detailed answer.
I will definitly take a look at all those parts in the next days.

**Comment by 4tXJ7f** [comment] 2019-06-22 05:30
I've just merged #3063. Please let me know if there are any other issue that you have with the floating-point API.

**Comment by 4tXJ7f** [comment] 2019-06-28 07:01
Since the PR has been merged, I'll close the issue for now. @kfriedberger if you have other issues with floating-point support in the API, please reopen the issue or open a new one. Thanks!

**Closed by 4tXJ7f** 2019-06-28 07:01 UTC
Labels: improvement
