### ISSUE TITLE
sygus-inference fatal failure at src/theory/theory_model_builder.cpp:1235

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3994] opened 2020-03-10 04:23 UTC
Hi,
For this formula:
```
(declare-datatypes ((a 0)) (((b (c Int) (d a)) (j))))
(declare-fun e (Int) Bool)
(declare-fun f () (Set a))
(declare-fun i () a)
(assert (forall ((g Int) (h a)) (= (member (b g h) f) (e g))))
(assert (member (b 1 j) f))
(assert (member i f))
(check-sat)
```
CVC4 --sygus-inference throws out a fatal failure:
```
[679] % cvc4 --quiet --sygus-inference small.smt2
Fatal failure within CVC4::Node CVC4::theory::TheoryEngineModelBuilder::normalize(CVC4::theory::TheoryModel*, CVC4::TNode, bool) at src/theory/theory_model_builder.cpp:1235
Check failure
 retNode.getKind() == kind::APPLY_UF || !retNode.getType().isFirstClass() || retNode.isConst()
Aborted
[680] % 
[680] % cat small.smt2
(declare-datatypes ((a 0)) (((b (c Int) (d a)) (j))))
(declare-fun e (Int) Bool)
(declare-fun f () (Set a))
(declare-fun i () a)
(assert (forall ((g Int) (h a)) (= (member (b g h) f) (e g))))
(assert (member (b 1 j) f))
(assert (member i f))
(check-sat)
```

OS: Ubuntu 18.04
Commit: 5cbc35e

**Comment by ajreynol** [comment] 2020-03-10 13:31
Appears to be due to the use of APPLY_SELECTOR in SyGuS grammars.  These need to be expanded to their total versions.

Then, the root cause is that an assertion is too strict.

**Comment by ajreynol** [comment] 2020-03-25 19:48
CVC4 answers unknown for this benchmark with sygus-inference now, closing this issue.

**Closed by ajreynol** 2020-03-25 19:48 UTC
Labels: minor
