### ISSUE TITLE
Fatal failure at proof/theory_proof.cpp:1111 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4350] opened 2020-04-19 08:50 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_UFNIA)
(set-option :proof true)
(declare-const i5 Int)
(declare-const i16 Int)
(assert (! (= 704 (- i16 704 42 i5) 0) :named IP_1))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
Fatal failure within virtual void CVC4::TheoryProof::printTheoryLemmaProof(std::vector<CVC4::Expr>&, std::ostream&, std::ostream&, const ProofLetMap&) at /home/peisen/test/tofuzz/CVC4/src/proof/theory_proof.cpp:1111
Check failure

 !lastLemma.isNull()

Aborted (core dumped
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:52
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:52 UTC
