### ISSUE TITLE
Assertion failure

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3414] opened 2019-10-28 13:01 UTC
Hi,
the following formula will trigger an assertion failure in CVC4

```
(declare-fun a () Int)
(declare-fun b () String)
(declare-fun c () Int)
(declare-fun d () Bool)
(declare-fun e () Int)
(declare-fun f () Bool)
(assert
  (=
    (not (= (div a e) (- 1)))
    (= c 0)
  )
)
(assert (= c (- 1) d))
(assert d)
(assert
  (=
    f
    (not (= e (- 1)))
  )
)
(assert
  (ite f (= (str.substr b 0 0) "ptrackp=") (= (div a c) (- 1)))
)
(check-sat) 
```

```
CVC4::theory::arith::Comparison::Comparison(CVC4::TNode)
/home/windomin/solver_binaries/cache/CVC4/src/theory/arith/normal_form.cpp:689:

  isNormalForm()
")

```

Revision: 3af2dfe (compiled with assertions)
OS: Ubuntu 18.04

**Comment by ajreynol** [comment] 2019-10-28 15:14
This is due to `(assert (= c (- 1) d))` being not well typed.  Ideally we should exit gracefully instead of an assertion failure.  I'm marking this a duplicate of #3287, which reported a similar issue.

**Closed by ajreynol** 2019-10-28 15:14 UTC
Labels: minor
