### ISSUE TITLE
Assertion failure when using incremental mode

### ISSUE THREAD

**Issue by dailler** [CVC4/CVC4#1671] opened 2018-03-19 10:21 UTC
Hello,

I tried to play with incremental mode of CVC4 recently. On one of my tests, I get an assertion failure:
"
CVC4 threw an "unexpected" exception.
terminate called after throwing an instance of 'CVC4::AssertionException'
  what():  Assertion failure.
void CVC4::ResourceManager::beginCall()
../../../../../src/util/resource_manager.cpp:215:

  d_cumulativeTimer.on()
"

I am using this version of CVC4:
"
This is CVC4 version 1.5
compiled with GCC version 5.4.0 20160609
on Jul 10 2017 10:02:12
"

I tried to reduce the error file. Here are both the original and the reduced files:
[reduced_error.txt](https://github.com/CVC4/CVC4/files/1824556/reduced_error.txt)
[error.txt](https://github.com/CVC4/CVC4/files/1824557/error.txt)

**Comment by timothy-king** [comment] 2018-03-19 19:47
This no longer reproduces on head for error.txt or reduced_error.txt: 3b6ef254e92ab0918db05a0c6084baa8892a2183 . Can you use a more up to date version? Where did you get the version you are using?

Side note:
Head spins forever guessing models on both versions of this problem, but this is not very unexpected. I believe that the axiom sqr_sum entails sqr(x : Int) = x*x.
```
;; sqr_sum
(assert
   (forall ((x Int) (y Int))
   (= (sqr (+ x y))
 	   (+ (+ (sqr x) (* (* 2 x) y)) (sqr y)))))
```
This might present some problems for answering `sat` instead of `unknown` (hence the spinning). Might want to ask @ajreynol. You might want to try using a macro for sqr using define-function. The following is solved at head in ~0.05s.
```
(set-logic AUFBVDTNIRA)
(set-option :incremental true)
(define-fun sqr ((x Int)) Int (* x x))
(assert (not (forall ((z1 Int)) (<= 1 (sqr z1)))))
(check-sat)
```

**Comment by dailler** [comment] 2018-03-20 09:55
Indeed I was using a bad version of CVC4. I tried to download the version of March 19th (from http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable) :
"This is CVC4 version 1.6-prerelease [git master 36512d36 (with modifications)]"

I realize that I omitted to give the commandline I was using which is:
``cvc4 --tlimit=1000 error.txt``

I get:
``CVC4 Error:
internal error: unhandled language LANG_AUTO in AntlrInput::newInput``

If I add the argument --lang=smt2, I still get the assertion failure:
``cvc4 --tlimit=1000 --lang=smt2 reduced_error.txt``

I get:

```
unknown
unknown
(error "Assertion failure.
void CVC4::ResourceManager::beginCall()
../../../../../src/util/resource_manager.cpp:216:

  d_cumulativeTimer.on()
")
```

Can you reproduce ?

> You might want to try using a macro for sqr using define-function. 

I'll try to see if it is possible to do that and to investigate if it is more efficient. Thanks for the advice.

**Comment by timothy-king** [comment] 2018-03-20 16:51
`cvc4 --tlimit=1000 error.txt` is missing `--lang=smt2`. That error message can be cleaned up, but the behavior is expected. You need to either end the file with .smt2 or override the input language with `--lang=`

`cvc4 --tlimit=1000 --lang=smt2 reduced_error.txt` reproduces quickly. The `--tlimit=1000` makes the error message not too surprising. Maybe someone else can take this up.

> I'll try to see if it is possible to do that and to investigate if it is more efficient. Thanks for the advice.

I found a mistake in my pencil and paper proof sketch for `sqr_sum |= sqr(1)=1` so I no longer think the axiom defines sqr to be x*x uniquely. I think now that this can be parameterized w.r.t. the value of `sqr(1)`. `sqr_sum` entails that if `sqr(1) = a`, then `sqr(x) = x*(x + a - 1)`. This is still definable using a macro and an extra free variable for `a`.

**Comment by ajreynol** [comment] 2019-08-28 21:30
Marking duplicate of #2908.

**Closed by ajreynol** 2019-08-28 21:30 UTC
Labels: bug, duplicate
