### ISSUE TITLE
Fatal failure at proof/cnf_proof.cpp:176 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4339] opened 2020-04-19 08:15 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_NIA)
(set-option :proof true)
(declare-const i1 Int)
(assert (! (= (- i1 33 i1 (- 33 i1 67 67 35) (- 33 i1 67 67 35)) (mod (mod 33 i1) 33)) :named IP_47))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
Fatal failure within CVC4::LemmaProofRecipe CVC4::CnfProof::getProofRecipe(const std::set<CVC4::NodeTemplate<true> >&) at /home/peisen/test/tofuzz/CVC4/src/proof/cnf_proof.cpp:176
Check failure

 d_lemmaToProofRecipe.find(lemma) != d_lemmaToProofRecipe.end()

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:50
Duplicate of #4337.

**Closed** 2020-04-19 13:50 UTC
Labels: duplicate
