### ISSUE TITLE
--dump-unsat-cores prints empty unsat core

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1073] opened 2017-09-05 20:37 UTC
Nicola Beauger reported that running CVC4 with

`cvc4 --dump-unsat-cores unsatcore.smt2`

prints an empty unsat core:

```
unsat
(
)
```
However, if the SMT-LIB command (get-unsat-core) is used instead of --dump-unsat-cores, the output is as expected:

```
unsat
(
hyp2
goal
)
```
The corresponding SMT2 file is here: [unsatcore.smt2.txt](https://github.com/CVC4/CVC4/files/1278822/unsatcore.smt2.txt)

**Comment by 4tXJ7f** [comment] 2017-09-05 20:38
This is a duplicate of #1072 .

**Closed** 2017-09-05 20:39 UTC
