### ISSUE TITLE
ccp benchmark slow (relative to yices) (Bugzilla #536)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#755] opened 2017-08-19 02:47 UTC
**Imported from Bugzilla**
Reporter: *Morgan Deters*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Tim King*
Component: *Arithmetic*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[ccp14-preprocessed.ec.cvc](http://cvc4.cs.stanford.edu/bugzilla_attachments/198_ccp14-preprocessed.ec.cvc)_ (KIND input, preprocessed, ID 198)

On 2013-09-30 20:12:18 -0700, Morgan Deters wrote:
> Created attachment 198
> KIND input, preprocessed
> 
> For this problem (unlike the metros ones), the UFLIA heuristic settings tend to do a bit better.  For the 10\-query benchmark attached (which has already been preprocessed to pure LIA), the times are:
> 
> Baseline (master, only \-i, QF\_UFLIA): 54 sec
> Baseline (master, only \-i, QF\_LIA): 88 sec
> 
> My KIND branch (only \-i, QF\_UFLIA): 10 sec
> My KIND branch (only \-i, QF\_LIA): 16 sec
> 
> My KIND branch is up to date with master and is available at https://github.com/mdeters/cvc4/tree/kind
> 
> There are a few extra rewrites in my branch (but a lot of the crazier stuff is turned off by default).  I still need to narrow down (for this particular instance) what works better relative to master.

On 2013-10-04 16:35:24 -0700, Tim King wrote:
> Morgan, Could you attach the input before preprocessing?  I'd like to see the ite structure.
> 
> \-\-Tim

**Comment by ajreynol** [comment] 2018-10-18 12:43
The benchmark posted here is post-ITE removal, so it's hard to say what the cause of the slowdown.

In the latest Kind performance testing, we've found that aggressive ITE simplifications lead to better performance.

I'm closing this issue.

**Closed by ajreynol** 2018-10-18 12:43 UTC
Labels: performance
