### ISSUE TITLE
Fatal failure at prop/cnf_stream.cpp:282 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4340] opened 2020-04-19 08:17 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_AUFNIA)
(set-option :proof true)
(declare-const v3 Bool)
(declare-const v7 Bool)
(declare-const i14 Int)
(assert (! (distinct (>= i14 43) v7 v3 false true) :named IP_4))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
(decl_atom Fatal failure within CVC4::prop::SatLiteral CVC4::prop::CnfStream::getLiteral(CVC4::TNode) at /home/peisen/test/tofuzz/CVC4/src/prop/cnf_stream.cpp:282
Check failure

 d_nodeToLiteralMap.contains(node)
Literal not in the CNF Cache: (= (>= i14 43) v7)

Aborted (core dumped)

~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:53
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:53 UTC
