### ISSUE TITLE
Hang on "ALL" instance and the tlimit option does not work

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#3939] opened 2020-03-07 17:03 UTC
Hi,
For this formula,
[tlimit.txt](https://github.com/CVC4/CVC4/files/4302181/tlimit.txt)

When executing
~~~~
./cvc4 --tlimit=3000 fname
~~~~
cvc4-nightly (http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/unstable/cvc4-2020-03-07-x86_64-linux-opt) hands for several minutes and `tlimit` does not work.

The options are minimized as
~~~~
(set-logic ALL)
(set-option :incremental true)
~~~~

**Comment by ajreynol** [comment] 2020-03-08 14:06
Thanks for the report.  We are working on being more accurate for timeouts, indeed cvc4 does not respect time limit in some cases.

This issue is a duplicate of https://github.com/CVC4/cvc4-projects/issues/62, closing for now.

**Closed by ajreynol** 2020-03-08 14:06 UTC
Labels: duplicate
