### ISSUE TITLE
Assertion failure in InstMatchGenerator

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2030] opened 2018-06-01 18:03 UTC
We get the following assertion failure on AUFNIRA/FFT/z3.667166.smt2 when running with `--trigger-sel=max --full-saturate-quant` (currently minimizing the benchmark):

```
(error "Assertion failure.
virtual int CVC4::theory::inst::InstMatchGenerator::getNextMatch(CVC4::Node, CVC4::theory::inst::InstMatch&, CVC4::theory::QuantifiersEngin
e*, CVC4::theory::inst::Trigger*)
../../../../src/theory/quantifiers/ematching/inst_match_generator.cpp:424:

  d_eq_class.isNull()
")
```

**Comment by 4tXJ7f** [comment] 2018-06-01 18:13
Alright, here's the minimized input:

```
(set-logic AUFNIRA)
(declare-fun _substvar_11_ () Int)
(declare-sort S2 0)
(declare-sort S5 0)
(declare-sort S6 0)
(declare-sort S12 0)
(declare-sort S13 0)
(declare-sort S25 0)
(declare-sort S30 0)
(declare-fun f7 (S5 Int) S2)
(declare-fun f8 () S5)
(declare-fun f9 (S6 S2) Int)
(declare-fun f10 () S6)
(declare-fun f21 (S12 S2) S13)
(declare-fun f49 (S25 S13) S12)
(declare-fun f62 (S30 Int) S6)
(declare-fun f108 () S25)
(declare-fun f119 () S30)
(declare-fun f137 () S12)
(assert (= (f9 (f62 f119 1) (f7 f8 2)) 1))
(assert (forall ((?v0 S2) (?v1 S2) (?v2 S2)) (let ((?v_0 (f9 f10 ?v0))) (=> (< 0 ?v_0) (= (f21 (f49 f108 (f21 f137 (f7 f8 (* ?v_0 _substvar_11_)))) (f7 f8 0)) (f21 (f49 f108 (f21 f137 ?v1)) ?v2))))))
(check-sat)
```

**Comment by ajreynol** [comment] 2018-06-02 18:51
The assertion is too strong when we use relational triggers, I will need to fix this.  This is not critical, I'm marking minor for now.

**Comment by 4tXJ7f** [comment] 2018-06-09 00:42
There seem to be similar assertion failures in other places (AUFLIA/20170829-Rodin/smt4656377037970455797.smt2):
```
(error "Assertion failure.
void CVC4::theory::inst::InstMatchGeneratorMulti::processNewInstantiations(CVC4::theory::QuantifiersEngine*, CVC4::theory::inst::Trigger*, CVC4::theory::inst::InstMatch&, int&, CVC4::theory::inst::InstMatchTrie*, int, int, int, bool) 
../../../../src/theory/quantifiers/ematching/inst_match_generator.cpp:872:

  !qe->inConflict()
")
```

And (AUFBVDTLIA/20172804-Barrett/rec-fun-ijcar2016/wo-wdf/wo_fd_vcs_wdf/2.5-cvc4-HeapSort.scala-25.smt2):
```
(error "Assertion failure.
void CVC4::theory::QuantifiersEngine::check(CVC4::theory::Theory::Effort)
../../../../src/theory/quantifiers_engine.cpp:618:

  !d_conflict
")
```

**Comment by 4tXJ7f** [comment] 2019-06-01 05:27
I am still seeing the assertion failure mentioned in my last comment on AUFBVDTLIA/20172804-Barrett/rec-fun-ijcar2016/wo-wdf/wo_fd_vcs_wdf/2.5-cvc4-HeapSort.scala-25.smt2.

**Comment by ajreynol** [comment] 2019-08-15 16:31
I cannot reproduce this in current master (3600 seconds on debug times out for the above benchmark).

I do remember making some changes to prevent that assertion failure. I'm closing this issue.

**Closed by ajreynol** 2019-08-15 16:31 UTC
Labels: bug, minor
