### ISSUE TITLE
(default) Solution soundness issue on QF_AUFLIRA formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#5058] opened 2020-09-10 23:55 UTC
Hi, for the following formula
~~~~
(set-logic QF_AUFLIRA)
(declare-fun _substvar_191_ () (Array (Array Bool Bool) (Array Bool Bool)))
(declare-const v2 Bool)
(declare-const arr0 (Array Bool Bool))
(declare-const arr1 (Array (Array Bool Bool) (Array Bool Bool)))
(assert (= arr1 (store arr1 (store arr0 false v2) arr0) _substvar_191_ arr1))
(push 1)
(assert v2)
(assert (= false false false false (= arr1 arr1 (store arr1 (store arr0 false v2) arr0) arr1) false))
(check-sat)
~~~~
cvc4 a8939854b88a4 yields `sat`, but z3 gives `unsat`.

`cvc4 --check-models` shows:
~~~~
Fatal failure within void CVC4::SmtEngine::checkModel(bool) at /home/CVC4-Release/src/smt/smt_engine.cpp:1743
Internal error detectedSmtEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (let ((_let_0 (store arr0 false v2))) (let ((_let_1 (store arr1 _let_0 arr0))) (and (= arr1 _let_1) (= _let_1 _substvar_191_) (= _substvar_191_ arr1))))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted
~~~~

**Comment by rainoftime** [comment] 2020-09-13 15:34
Another non-incremental formula
~~~~
(set-logic QF_AUFNIRA)
(declare-const arr-4288260026874202574_-5888426203393595543-0 (Array Bool Real))
(declare-sort S0 0)
(declare-const arr-4850304371031819733_-7794334710891084498-0 (Array (Array Bool Real) S0))
(assert (distinct (select arr-4850304371031819733_-7794334710891084498-0 arr-4288260026874202574_-5888426203393595543-0) (select arr-4850304371031819733_-7794334710891084498-0 (store arr-4288260026874202574_-5888426203393595543-0 true 740.0))))
(assert (= (store arr-4288260026874202574_-5888426203393595543-0 true 740.0) arr-4288260026874202574_-5888426203393595543-0 arr-4288260026874202574_-5888426203393595543-0 arr-4288260026874202574_-5888426203393595543-0))
(check-sat)
~~~~

**Comment by nafur** [comment] 2020-09-14 12:18
Seems to be a duplicate of #4237 as it minimizes to
```
(declare-const a (Array Bool Real))
(declare-sort S 0)
(declare-const b (Array (Array Bool Real) S))
(assert (distinct (select b a) (select b (store a true 1))))
(check-sat)
```
with
```
Fatal failure within void CVC4::theory::arrays::ArrayInfo::addIndex(CVC4::Node, CVC4::TNode) at /home/gereon/cvc4_master/src/theory/arrays/array_info.cpp:137
Check failure

 !i.getType().isArray()"
```

**Comment by rainoftime** [comment] 2020-09-14 13:09
To https://github.com/CVC4/CVC4/issues/4237

**Closed** 2020-09-14 13:09 UTC
