### ISSUE TITLE
Sygus problem involving uninterpreted function

### ISSUE THREAD

**Issue by ychen306** [CVC4/CVC4#3257] opened 2019-09-05 16:03 UTC
I am trying to get the sygus solver to synthesize a function that uses (universally quantified) uinterpreted function, and it throws the error "operator does not have function type". Is this supported?

**Comment by ajreynol** [comment] 2019-09-05 16:06
The combination of sygus and uninterpreted functions is not fully supported, although some examples should work. If you send me the example, I can take a look at why you are getting that error and if there is any options in CVC4 that can be used to support it.

**Comment by ychen306** [comment] 2019-09-05 16:50
```
(declare-fun uf ((_ BitVec 32) (_ BitVec 32)) (_ BitVec 32))

(synth-fun foo ((x (BitVec 32))
                (y (BitVec 32))) (BitVec 32) 
 ((Start (BitVec 32) ((uf Arg Arg)))
  (Arg (BitVec 32) (x y))))

(declare-var x (BitVec 32))
(declare-var y (BitVec 32))

(constraint (= (foo x y) (uf x y)))

(check-synth)```

**Comment by ajreynol** [comment] 2019-09-05 21:27
This example isn't currently supported in CVC4 unfortunately.

The issue is that having `uf` in the grammar makes it so that solutions for `foo` are not closed terms.  That is, we generally insist that solutions are closed, so the body of `foo` should have only free variables `x` and `y`.

For some more details on UF+SyGuS, notice that the use of uninterpreted functions in the SyGuS language has updated in version 2.0.  You can see:
https://sygus.org/assets/pdf/SyGuS-IF_2.0.pdf
for details, see the section "Uninterpreted Functions" on page 11. In particular, the `declare-fun` command is now forbidden. The plan is to support universal function variables using function as a first-class type, meaning your example could be written:
```
(declare-var uf (-> (_ BitVec 32) (_ BitVec 32) (_ BitVec 32)))

(synth-fun foo ((x (BitVec 32))
                (y (BitVec 32))) (BitVec 32) 
 ((Start (BitVec 32) ((uf Arg Arg)))
  (Arg (BitVec 32) (x y))))

(declare-var x (BitVec 32))
(declare-var y (BitVec 32))

(constraint (= (foo x y) (uf x y)))

(check-synth)
```

CVC4 supports the above syntax for function types.  However, the restriction that the grammar for `foo` can only contain free variables `x,y` remains.

Alternatively, if `uf` was declared as another function-to-synthesize, this would require the "forward declaration" feature of sygus, see the keyword "fwd-decls" from https://sygus.org/assets/pdf/SyGuS-IF_2.0.pdf.  CVC4 does not yet support a synthesis algorithm for this fragment, although may be added as a feature in the future.

**Comment by ajreynol** [comment] 2019-09-11 14:34
Closing this issue, do let us know if you have further questions.

**Closed by ajreynol** 2019-09-11 14:34 UTC
Labels: question

**Comment by remysucre** [comment] 2021-03-12 20:37
Hello, I found this issue after running into the same problems with uninterpreted functions in the grammar. Is there a fundamental limitation in the SyGuS algorithm that precludes UF from the grammar, or is this more a matter of implementation?

**Comment by ajreynol** [comment] 2021-03-12 21:04
Use of higher-order features is allowable in some contexts.  Consider this example from our regressions: 
https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/sygus/ho-sygus.sy
for which cvc4 can produce a solution `y -> (lambda ((x Int)) (z (+ x 1))`.

However, for the benchmark in this issue, the fundamental problem is that it is defining the grammar for one function-to-synthesize in terms of another function-to-synthesize (when viewing `uf` as a function to synthesize).  This indeed is a limitation of the current SyGuS algorithms implemented in CVC4.  

It would be relatively straightforward to extend CVC4 for such problems, but would take a fair amount of implementation effort.  If there is enough interest in this feature, we could add support for this.

**Comment by remysucre** [comment] 2021-03-13 18:42
Please let me know if I should start a separate issue. 

First, I ran that test and it did not return the solution you showed. Instead it returns:
```
(define-fun f ((y (-> Int Int)) (z Int)) Int (let ((_let_1 (y 1))) (let ((_let_2 (y 2))) (ite (and (= z 1) (not (= _let_1 _let_2))) _let_2 _let_1))))
```

Second, in my application I don't need to synthesize `uf`, but I want a solution to `foo` that uses `uf`, as in: 

```
; EXPECT: (define-fun foo ((x Int) (y Int)) (uf x y))
; COMMAND-LINE: --lang=sygus2 --sygus-out=status --uf-ho
(set-logic ALL)

(declare-var uf (-> Int Int Int))

(synth-fun foo ((x Int) (y Int)) Int
 ((App Int) (Arg Int))
 ((App Int ((uf Arg Arg)))
  (Arg Int (x y))))

(declare-var x Int)
(declare-var y Int)

(constraint (= (foo x y) (uf x y)))

(check-synth)
```

**Comment by remysucre** [comment] 2021-03-13 18:49
In addition, the following program immediately returns `unknown`, and I would like a solution `(define f ((x Int)) (uf x))`
```
; EXPECT: (define-fun f ((x Int)) (uf x))
; COMMAND-LINE: --lang=sygus2 --uf-ho
(set-logic ALL)

(synth-fun f ((x Int)) Int)

(declare-var uf (-> Int Int))
(declare-var x Int)

(constraint (= (f x) (uf x)))

(check-synth)
```

**Comment by ajreynol** [comment] 2021-03-15 14:29
When cvc4 says "unknown" for a sygus problem, the problem likely has no solution.

In your examples above, note that `(declare-var uf (-> Int Int))` declares a *universal* variable `uf`.  Your examples are asking whether there is a function `f` that behaves like *every* function, which of course, is infeasible.

Moreover, the grammar in the first example is actually malformed since it includes `uf` on the RHS of a grammar rule, which would make `uf` a free variable in a solution for `f`.  

We should make cvc4 give better error/warning messages for example like the ones above.
FYI @abdoo8080.

**Comment by remysucre** [comment] 2021-03-15 16:51
> it includes `uf` on the RHS of a grammar rule, which would make `uf` a free variable in a solution for f.

That is in fact what I intended: I want to synthesize a function that uses `uf`. In [Rosette](https://github.com/emina/rosette) I can express it as follows: 

```
#lang rosette

(require rosette/lib/angelic)

(define-symbolic x y integer?)
(define-symbolic uf (~> integer? integer? integer?))

(define (??term depth)
  (if (= 0 depth)
      (choose* x y)
      ((choose* + * uf) (??term (- depth 1))
                        (??term (- depth 1)))))

(define sketch (??term 2))

(define M (synthesize
           #:forall (list x y uf)
           #:guarantee (assert (= sketch (* 2 (uf x y))))))
```
Which returns: 
```
> (evaluate sketch M)
(+ (app uf x y) (app uf x y))
```
In general, having uninterpreted functions in the grammar is helpful when an operator doesn't map directly to an operator in an existing theory, in which case one can specify the semantics of the operator with assertions. For example, [here](https://github.com/remysucre/pier/blob/42a4e613d1e552a421181b4f84e7c5ce4b81742d/centrality.rkt#L52) I specify the semantics of the distance function `D` with the triangle equality. In my application I also use uninterpreted functions (e.g. `(-> Int Int Bool)`) to represent relations. 

Is there a way to express such use cases in CVC4?

**Comment by ajreynol** [comment] 2021-03-15 18:28
To clarify the issue, your solution would be malformed if given conjecture:
`exists f. forall uf. P`
you gave a solution for `f` that involved `uf`.

In other words, you should *not* use `(declare-var uf ...)` for what you are trying to do, as this is declaring `uf` as a universal variable in your constraint.

The reason for why the SyGuS language does not permit uninterpreted functions is due to this very confusion in semantics.  A SyGuS conjecture is a *closed* formula (no free variables) of the form:
`exists f1 ... fn. forall x1 ... xn. P`
A solution is assignment to f1 ... fn that makes the above formula valid.  Now, introducing a new uninterpreted function `uf`, the question is how do the above semantics account for it? I think you are asking to treat `uf` as a free (existential) function.  Notice that this means the problem is equivalent to:
`exists uf. exists f1 ... fn. forall x1 ... xn. P`.
Thus, the way that this could be formulated (while maintaining the standard semantics) is to say `uf` is another function-to-synthesize. 

Let me know if that makes sense or if you have a different intended semantics for `uf`.

What is missing in CVC4 is a way of handling grammars that refer to other functions-to-synthesize.  This is possible to add, but will require a bit of engineering effort.

**Comment by ajreynol** [comment] 2021-03-15 18:33
> First, I ran that test and it did not return the solution you showed. Instead it returns:

Try option `--uf-ho --sygus-si=none`.  By default, CVC4 will use heuristics that generate larger solutions quickly when no grammar is provided.

**Comment by remysucre** [comment] 2021-03-15 19:42
> A SyGuS conjecture is a closed formula (no free variables) of the form:
> `exists f1 ... fn. forall x1 ... xn. P`

I think this is the gist of the problem. What I want is probably something like: 
`forall uf . exists f1 ... fn . forall x1 ... xn. P`
And now I see the 2 quantifier alternations are problematic. 
In rosette I can push the quantifier on `uf` inside and have `exists b1 ... bn . forall uf x1 ... xn. P`, because `b1 ... bn` are boolean holes instead of closed terms over the grammar, so they don't need to refer to `uf`.

**Comment by remysucre** [comment] 2021-03-15 19:53
Actually, typing the above immediately made me think of a solution by skolemizing: 

```
; EXPECT: (define-fun foo ((x Int) (y Int)) (uf x y))
; COMMAND-LINE: --lang=sygus2 --sygus-out=status --uf-ho
(set-logic ALL)

(synth-fun foo ((x Int) (y Int) (uf (-> Int Int Int))) Int
 ((App Int) (Arg Int))
 ((App Int ((uf Arg Arg)))
  (Arg Int (x y))))

(declare-var x Int)
(declare-var y Int)
(declare-var uf (-> Int Int Int))

(constraint (= (foo x y uf) (uf x y)))

(check-synth)
``` 
And it now returns `(define-fun foo ((x Int) (y Int) (uf (-> Int Int Int))) Int (uf x y))` which is what I want!

**Comment by ajreynol** [comment] 2021-03-15 19:55
Aha, yes, and actually this is reminiscent of the https://github.com/CVC4/CVC4/blob/master/test/regress/regress1/sygus/ho-sygus.sy example. If `uf` is an argument of the function-to-synthesize, this should be handled already.

Do let me know if you run into any issues.

**Comment by remysucre** [comment] 2021-03-15 19:57
Thank you, this has been very helpful!
