### ISSUE TITLE
Assertion failure when checking the model of NRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3411] opened 2019-10-27 19:45 UTC
Hi,
For this formula,
```
(set-logic NRA)
(declare-fun a () Real)
(declare-fun b () Real)
(assert (= (/ 0 (+ 1 (* a a b))) 0))
(check-sat)
```
CVC4 will throw out an assertion violation:
```
(error "Assertion failure
void CVC4::theory::TheoryEngineModelBuilder::debugCheckModel(CVC4::theory::TheoryModel*)
/home/suz/software/CVC4/src/theory/theory_model_builder.cpp:878:
  tm->getValue(*eqc_i) == rep
run with -d check-model::rep-checking for details")
```
when check-models is on:
```
cvc4 --check-models file.smt2
```

OS: Ubuntu 18.04
Revision: 2493601

**Comment by ajreynol** [comment] 2019-11-04 18:01
Thanks for the benchmark, this is a duplicate of #2153.

Currently the models produced by the non-linear solver violate some of the assertions in CVC4's model validating code.

**Closed by ajreynol** 2019-11-04 18:01 UTC
