### ISSUE TITLE
New feature requested - simplification

### ISSUE THREAD

**Issue by PaulMeng** [CVC4/CVC4#1077] opened 2017-09-07 14:17 UTC
A trivial simplification example could be removing redundant expressions from a formula. E.g, given a formula `a = b /\ a = b /\ b = c`, simplification would return a new formula `a = b /\ b = c`.

Simplification could be applied on a formula within or without a context. Suppose we have the following declarations and constraints asserted in a context:

`a : Int;
b : Int;
c : Int;
a = b;
b = c;`

Simplifying the formula `a = b /\ b = c` within the above context would yield "true" or "empty", whereas without context it would return the original formula.

**Comment by ajreynol** [comment] 2019-08-28 21:37
This is a duplicate of #2702.

**Closed by ajreynol** 2019-08-28 21:37 UTC
Labels: duplicate, feature
