### ISSUE TITLE
Fatal failure at proof/arith_proof.cpp:936 (proof, use-soi)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4345] opened 2020-04-19 08:39 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_AUFLRA)
(set-option :proof true)
(set-option :use-soi true)
(declare-const r2 Real)
(declare-const r13 Real)
(declare-const arr (Array Real Real))
(declare-const r21 Real)
(assert (! (< r2 0.0 (- (select arr 0.0) r21 583666.0 583666.0 625.0) r13 r2) :named IP_8))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
;  Linear Polynomial Proof Conversions
  (@ pf_aff.l6 (aff_>_from_term _ _ _ _ 
    (is_aff_- _ _ _ _ _ 
      (is_aff_+ _ _ _ _ _ 
        (is_aff_var_real r21)Fatal failure within static void CVC4::LFSCArithProof::printLinearMonomialNormalizer(std::ostream&, const Node&) at /home/peisen/test/tofuzz/CVC4/src/proof/arith_proof.cpp:936
Check failure

 (n[0].getKind() == kind::CONST_RATIONAL && (n[1].getKind() == kind::VARIABLE || n[1].getKind() == kind::SKOLEM))
node (* (- 1.0) (select arr 0.0)) is not a linear monomial CONST_RATIONAL SELECT

~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:53
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:53 UTC
