### ISSUE TITLE
Fatal failure at src/expr/node_manager.cpp:632

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#5663] opened 2020-12-13 02:02 UTC
```
[507] % cvc4 small.smt2
Fatal failure within std::vector<CVC4::TypeNode> CVC4::NodeManager::mkMutualDatatypeTypes(const std::vector<CVC4::DType>&, const std::set<CVC4::TypeNode>&, uint32_t) at src/expr/node_manager.cpp:632
Check failure
 resolver != nameResolutions.end()
cannot resolve type Int; it's not among the datatypes being defined
Aborted
[508] % 
[508] % cat small.smt2
(set-logic QF_NRA)
(declare-datatypes ((Node 0)) (((node (data Int)))))
[509] %
```
Commit: a49efc8

**Comment by ajreynol** [comment] 2020-12-13 17:38
This is actually a duplicate of the issue raised in https://github.com/CVC4/CVC4/issues/5150

We should give a proper error message where datatypes are not well defined (Int is not declared in the logic here).

**Closed by ajreynol** 2020-12-13 17:38 UTC
Labels: duplicate
