### ISSUE TITLE
Fatal failure at expr/expr_template.cpp:413 (proof, decision-use-weight)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4352] opened 2020-04-19 09:02 UTC
Hi,
For the following formula:
~~~~
(set-logic ABV)
(declare-fun _substvar_41_ () (Array (_ BitVec 9) Bool))
(set-option :proof true)
(set-option :decision-use-weight true)
(assert false)
(assert (! (select _substvar_41_ (bvsdiv (_ bv0 9) (bvshl (_ bv386 9) (_ bv386 9)))) :named IP_24))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within CVC4::Expr CVC4::Expr::operator[](unsigned int) const at /home/peisen/test/tofuzz/CVC4/src/expr/expr_template.cpp:413
Check failure

 i >= 0 && i < d_node->getNumChildren()
Child index out of bounds
Aborted (core dumped)

~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:52
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:52 UTC

**Comment by rainoftime** [comment] 2020-04-19 14:19
Why duplicate?

**Comment by ajreynol** [comment] 2020-04-19 14:35
The solution to all of these issues is to replace the implementation of our `proof` option, which is in progress.
