### ISSUE TITLE
another small regression on master (Bugzilla #810)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1023] opened 2017-08-19 04:43 UTC
**Imported from Bugzilla**
Reporter: *Florian Schanda*
Status: *NEW*
Severity: *minor*
Assigned to: *Andrew Reynolds*
Component: *Quantifiers*
Milestone: *---*
Version: *master*
Platform: *All*
OS: *All*

Original attachment names and IDs:
- _[attempt_3.adb_74_22_assert.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/445_attempt_3.adb_74_22_assert.smt2)_ (used to be unsat, now times out, ID 445)
- _[textio-get_line.adb_145_28_assert.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/446_textio-get_line.adb_145_28_assert.smt2)_ (another example, ID 446)
- _[five_more_regressions.tar.gz](http://cvc4.cs.stanford.edu/bugzilla_attachments/447_five_more_regressions.tar.gz)_ (five more regressions for the new quantifiers, ID 447)

On 2017-05-17 06:26:06 -0700, Florian Schanda wrote:
> Created attachment 445
> used to be unsat, now times out
> 
> Hi Andrew,
> 
> Attached is a VC that used to [92d78a10a] go through fairly fast (unsat), but now I can't find any combination of flags that work. I have tried on current\-ish master [3271242a].
> 
> Any ideas?

On 2017-05-17 06:40:31 -0700, Florian Schanda wrote:
> Created attachment 446
> another example

On 2017-05-17 09:16:42 -0700, Andrew Reynolds wrote:
> Hi Florian,
> 
> The default implementation of multi\-triggers in E\-matching changed in:
> 
> https://github.com/CVC4/CVC4/commit/bf682b92e2bddcd490604f8a65c440b9c4c2f2f9
> 
> To revert to the old version, use \-\-multi\-trigger\-cache.
> 
> Although I expect that the new version (without \-\-multi\-trigger\-cache) should be superior overall (the new version is a net \+186 benchmark gain on SMT LIB).  Let me know if this isn't the case for your benchmarks.
> 
> Btw, what command line options were working for you in [92d78a10a] ?
> 
> Cheers,
> Andy

On 2017-05-18 00:50:50 -0700, Florian Schanda wrote:
> Created attachment 447
> five more regressions for the new quantifiers
> 
> Indeed \-\-multi\-trigger\-cache does seem to fix these. I've attached a bunch more of these benchmarks (all from our public testsuite so feel free to include/share/redistribute) where the new approach doesn't work as well as the old one.

**Comment by ajreynol** [comment] 2018-08-03 16:22
Closing this issue. AFAIK, these benchmarks went solved -> unsolved, while a larger number went unsolved -> solved. The cause was the update to the new implementation of multi-triggers, which can be reproduced by --multi-trigger-cache if necessary.

**Closed by ajreynol** 2018-08-03 16:22 UTC
Labels: minor, performance
