### ISSUE TITLE
Assertion failure in minisat for QF_NRA benchmarks (Bugzilla #827)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1040] opened 2017-08-19 04:46 UTC
**Imported from Bugzilla**
Reporter: *Andres Noetzli*
Status: *NEW*
Severity: *enhancement*
Assigned to: *Andrew Reynolds*
Component: *Arithmetic*
Milestone: *1.6*
Version: *master*
Platform: *PC*
OS: *Linux*

Original attachment names and IDs:
- _[assertion.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/458_assertion.smt2)_ (Example, ID 458)

On 2017-06-18 00:26:51 -0700, Andres Noetzli wrote:
> Created attachment 458
> Example
> 
> For two of the QF\_NRA benchmarks, CVC4 is failing with the following failure:
> 
> cvc4\-assertions: ../../../../../../src/prop/minisat/simp/SimpSolver.cc:170: bool CVC4::Minisat::SimpSolver::addClause\_(CVC4::Minisat::vec<CVC4::Minisat::Lit>&, bool, CVC4::ClauseId&): Assertion \`!isEliminated(var(ps[i]))' failed.
> Aborted
> 
> I am attaching a minified example. To reproduce, use \-\-nl\-ext \-\-nl\-ext\-tplanes flags.

On 2017-06-18 00:29:42 -0700, Andres Noetzli wrote:
> Stack trace:
> 
> \# 0  0x0000000001ba6578 in raise ()
> \# 1  0x0000000001ba67da in abort ()
> \# 2  0x0000000001b9999b in \_\_assert\_fail\_base ()
> \# 3  0x0000000001b999fe in \_\_assert\_fail ()
> \# 4  0x00000000010802a6 in CVC4::Minisat::SimpSolver::addClause\_(CVC4::Minisat::vec<CVC4::Minisat::Lit>&, bool, unsigned int&) ()
> \# 5  0x000000000101c172 in CVC4::prop::MinisatSatSolver::addClause(std::vector<CVC4::prop::SatLiteral, std::allocator<CVC4::prop::SatLiteral> >&, bool) ()
> \# 6  0x0000000000cc1697 in CVC4::prop::CnfStream::assertClause(CVC4::NodeTemplate<false>, std::vector<CVC4::prop::SatLiteral, std::allocator<CVC4::prop::SatLiteral> >&) ()
> \# 7  0x0000000000cc6d31 in CVC4::prop::TseitinCnfStream::convertAndAssertImplies(CVC4::NodeTemplate<false>, bool) ()
> \# 8  0x0000000000cc71bd in CVC4::prop::TseitinCnfStream::convertAndAssert(CVC4::NodeTemplate<false>, bool) ()
> \# 9  0x0000000000cc83b7 in CVC4::prop::TseitinCnfStream::convertAndAssert(CVC4::NodeTemplate<false>, bool, bool, CVC4::ProofRule, CVC4::NodeTemplate<false>) ()
> \# 10 0x0000000000ccd27a in CVC4::prop::PropEngine::assertLemma(CVC4::NodeTemplate<false>, bool, bool, CVC4::ProofRule, CVC4::NodeTemplate<false>) ()
> \# 11 0x0000000000658280 in CVC4::TheoryEngine::lemma(CVC4::NodeTemplate<false>, CVC4::ProofRule, bool, bool, bool, CVC4::theory::TheoryId) ()
> \# 12 0x0000000000658cef in CVC4::TheoryEngine::EngineOutputChannel::lemma(CVC4::NodeTemplate<false>, CVC4::ProofRule, bool, bool, bool) ()
> \# 13 0x00000000006386a7 in CVC4::theory::ExtTheory::sendLemma(CVC4::NodeTemplate<true>, bool) ()
> \# 14 0x000000000063d55e in CVC4::theory::ExtTheory::doInferencesInternal(int, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > > const&, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > >&, bool, bool) ()
> \# 15 0x000000000063df77 in CVC4::theory::ExtTheory::doInferences(int, std::vector<CVC4::NodeTemplate<true>, std::allocator<CVC4::NodeTemplate<true> > >&, bool)
>     ()
> \# 16 0x0000000000dba7e7 in CVC4::theory::arith::NonlinearExtension::check(CVC4::theory::Theory::Effort) ()
> \# 17 0x00000000007002d6 in CVC4::theory::arith::TheoryArithPrivate::check(CVC4::theory::Theory::Effort) ()
> \# 18 0x0000000000659b29 in CVC4::TheoryEngine::check(CVC4::theory::Theory::Effort) ()
> \# 19 0x0000000000ccfb2c in CVC4::prop::TheoryProxy::theoryCheck(CVC4::theory::Theory::Effort) ()
> \# 20 0x00000000010169c7 in CVC4::Minisat::Solver::propagate(CVC4::Minisat::Solver::TheoryCheckType) ()
> \# 21 0x0000000001016bc3 in CVC4::Minisat::Solver::search(int) ()
> \# 22 0x0000000001017e49 in CVC4::Minisat::Solver::solve\_() ()
> \# 23 0x0000000001087988 in CVC4::Minisat::SimpSolver::solve\_(bool, bool) ()
> \# 24 0x000000000101c558 in CVC4::prop::MinisatSatSolver::solve() ()
> \# 25 0x0000000000cce461 in CVC4::prop::PropEngine::checkSat() ()
> \# 26 0x000000000057f5ad in CVC4::SmtEngine::check() ()
> \# 27 0x0000000000582355 in CVC4::SmtEngine::checkSatisfiability(CVC4::Expr const&, bool, bool) ()
> \# 28 0x0000000000583093 in CVC4::SmtEngine::checkSat(CVC4::Expr const&, bool) ()
> \# 29 0x00000000005335fe in CVC4::CheckSatCommand::invoke(CVC4::SmtEngine\*) ()
> \# 30 0x0000000000537a4f in CVC4::Command::invoke(CVC4::SmtEngine\*, std::ostream&) ()
> \# 31 0x000000000041c06b in CVC4::main::smtEngineInvoke(CVC4::SmtEngine\*, CVC4::Command\*, std::ostream\*) ()
> \# 32 0x000000000041e934 in CVC4::main::CommandExecutor::doCommandSingleton(CVC4::Command\*) ()
> \# 33 0x0000000000423757 in runCvc4(int, char\*\*, CVC4::Options&) ()
> \# 34 0x0000000000403916 in main ()

On 2017-06-18 07:32:23 -0700, Andrew Reynolds wrote:
> My first impression of this bug is the following:
> 
> \* During preprocess, the literal (\= b 1.0) is eliminated since it only occurs positively.
> \* Later, the non\-linear extension adds lemma of the form:
> (\=> (and (\= b 1.0) (\= e 1.0)) (\= (\* b e) 1.0))
> which is
> (or (not (\= b 1.0)) (not (\= e 1.0)) (\= (\* b e) 1.0))
> 
> This may trigger an assertion failure since initially all occurrences of (\= b 1.0) were positive but now we are introducing a clause where it is negative.
> 
> I'm not sure how to fix this.
> 
> Perhaps the assertion is too strong?

On 2017-06-18 12:13:02 -0700, Andres Noetzli wrote:
> Hm, I am not sure. The problem is that we don't have assertions enabled, so during the competition it does not get triggered. Do you think that we should enable the assertion code for the competition? I ran the benchmarks for a couple of minutes without assertions but did not get an answer.

On 2017-06-18 20:58:58 -0700, Andrew Reynolds wrote:
> I don't think the assertion is critical to correctness.  I would not enable the assertion in the competition.

**Comment by ajreynol** [comment] 2018-05-27 18:38
Now a duplicate of #1998, closing this one.

**Closed by ajreynol** 2018-05-27 18:38 UTC
Labels: minor, refactor
