### ISSUE TITLE
Suboptimal solution to SyGuS problem

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#2911] opened 2019-03-31 21:45 UTC
I'm not sure if this would actually be considered a bug or not, but it does seem suboptimal.  I've attached a zip file with two files, test1.sl and test2.sl.  The only difference between the two files is line 24.  In test1.sl, it has two constants, 3 and 9, as possible Int's.  In test2.sl, these are removed.

Running `cvc4 test1.sl` prints:
`(define-fun substring ((x1 StringWrap) (x2 Int) (x3 Int)) StringWrap (ite (> 3 (- x3 3)) (ite (> 3 x2) (ite (> 3 (- 3 x2)) (StringWrap (str.substr (str x1) x2 x2)) (StringWrap (str.substr (str x1) x2 x3))) (StringWrap "W")) (ite (> 3 (- 9 x3)) (StringWrap (str.substr (str x1) x2 (- 9 x3))) (StringWrap " "))))`

Running `cvc4 test2.sl` prints the considerably simpler:
`(define-fun substring ((x1 StringWrap) (x2 Int) (x3 Int)) StringWrap (StringWrap (str.substr (str x1) x2 (- x3 x2))))`

To my mind, ideally the solution found for test2.sl would be found from both files.

(Running either file with --no-sygus-pbe gives the solution found for test2.sl.)

[test.zip](https://github.com/CVC4/CVC4/files/3027180/test.zip)

**Comment by ajreynol** [comment] 2019-03-31 21:49
Indeed, this is expected behavior.

The PBE solver is optimized for finding solutions fast, whereas the default (enumerative) solver is guaranteed to find the smallest solution.

Btw, one combination options that is worth noting here is `--sygus-stream --sygus-pbe`.  This enables the "streaming" option for solutions (finding multiple ones) using the PBE solver but will only print new solutions if they are smaller than all other previous solutions.  This combination of options can potentially allow the best of both worlds (seeing non-optimal solutions quickly, while finding optimal solutions later).

**Comment by BillHallahan** [comment] 2019-03-31 22:45
I see.  Thanks!

**Comment by 4tXJ7f** [comment] 2019-04-03 16:55
It looks like this issue has been resolved, so I am closing it.

**Closed by 4tXJ7f** 2019-04-03 16:55 UTC

**Comment by zhanghongce** [comment] 2019-04-24 00:00
Hi Andrew,

May I ask one more question on the option `--sygus-stream --sygus-pbe`? 

What I encountered is that if I use CVC4 (the latest one on master branch) without this option, the result is unknown (however I believe there exists at least one solution), but if I add the option `--sygus-stream --sygus-pbe`, it will first print a solution (in a relatively short time) and after a while it ends with unknown...

Because there are only finite number of possible expressions allowed by the given syntax (non-recursive). So when I saw `unknown` I thought it had already enumerated all possibilities, but it seems that it is not. I was wondering how I can make it enumerate all possibilities?

If needed I can attach the file (it is a bit long).

Thanks!

**Comment by ajreynol** [comment] 2019-04-24 00:18
Yes, please send me it and I can take a look.

**Comment by zhanghongce** [comment] 2019-04-24 00:33
Hi Andrew,
Here it is:
https://github.com/zhanghongce/inv-syn-examples/blob/master/aes-sygus/wrapper.smt2

Thank you very much!

**Comment by ajreynol** [comment] 2019-04-24 15:01
Thanks for the benchmark.
By default, if you use `--sygus-stream --sygus-pbe`, CVC4 will not print out all solutions. It will only print solutions that are smaller than all previous solutions (over the run).  So the behavior you are seeing regarding not seeing all solutions is expected.
To get all solutions, you should use `--sygus-stream` alone. However, as you may have noticed, CVC4 is a lot slower without the option `--sygus-pbe`.  The reason for this is that a certain optimization (fast evaluation) is enabled by default when the PBE solver is enabled. However, looking into this a bit, this optimization could be applied for your example when the option `--sygus-pbe` is not enabled.

I am going to open a separate issue for this. 

@4tXJ7f this may interest you.
