### ISSUE TITLE
Crash with --check-models 

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3441] opened 2019-11-05 14:07 UTC
Hi all, 

for the following formula, CVC4 will crash with `--check-models` option enabled

```
(set-logic QF_NIA)                                                              
(declare-fun a () Int)                                                          
(declare-fun b () Int)                                                          
(declare-fun c () Int)                                                          
(declare-fun d () Int)                                                          
(assert (and (>= (+ (* b c (- (-  4) d)) (- 1)) 0 (div a b))))                  
(check-sat)  
```

```
Fatal failure within void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool) at /home/windomin/solver_binaries/cache/CVC4/src/theory/theory_engine.cpp:2229
Internal error detectedTHEORY_ARITH has an asserted fact that the model doesn't satisfy.
The fact: (= kf_6 (+ (* 4 b) (* b d)))
Model value: false

Aborted
```
OS: Ubuntu 18.04
Revision: c547bd5

**Comment by ajreynol** [comment] 2019-11-05 15:13
This is a duplicate of #2153. The solution is in progress (see #3426).

**Closed by ajreynol** 2019-11-05 15:13 UTC
Labels: duplicate
