### ISSUE TITLE
Fatal failure at theory/theory_engine.cpp:1524 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4353] opened 2020-04-19 09:04 UTC
Hi,
For the following formula:
~~~~
(set-logic AUFNRA)
(set-option :proof true)
(declare-sort S0 0)
(declare-const arr (Array S0 Bool))
(declare-const S0-0 S0)
(assert false)
(assert (! (select (store arr S0-0 true) S0-0) :named IP_43))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within bool CVC4::TheoryEngine::propagate(CVC4::TNode, CVC4::theory::TheoryId) at /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:1524
Check failure

 d_propEngine->isSatLiteral(literal)

Aborted (core dumped)

~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:52
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:52 UTC
