### ISSUE TITLE
[SyGuS] UnhandledCaseException for String problem

### ISSUE THREAD

**Issue by iwob** [CVC4/CVC4#1345] opened 2017-11-09 15:56 UTC
Running the attached file ([phone_formal.txt](https://github.com/CVC4/CVC4/files/1458192/phone_formal.txt)) using the latest night build produces the following error:
```
CVC4 threw an "unexpected" exception.
terminate called after throwing an instance of 'CVC4::UnhandledCaseException'
  what():  Unhandled case encountered
static CVC4::theory::TypeEnumeratorInterface* CVC4::theory::TypeEnumerator::mkTypeEnumerator(CVC4::TypeNode, CVC4::theory::TypeEnumeratorProperties*)
../../../../src/theory/type_enumerator_template.cpp:51
The case was: No type enumerator for type `(String) String'
```

Run options:
```./cvc4-2017-11-09-x86_64-linux-opt --strings-exp --lang=sygus  phone_formal.sl```

I'm experimenting with formal specifications for String benchmarks, instead of test cases. I intend to compare approach I'm working on with CVC4, so if you have some suggestions with which options I should run CVC4 then I'd be grateful. :) Should I use the 1.5 official release, or rather some nightly build? After all, in months since the official release there certainly were many improvements.

**Comment by ajreynol** [comment] 2017-11-09 18:32
This is fixed in an open pull request (#1243).
The problem is unique to combining --strings-exp with sygus.  

(as an internal note here):
The problem was caused by the new representation of synthesis conjectures, introduced in #1244.
When we combine sygus techniques with finite model finding techniques (as required by --strings-exp), then we require that the domains of quantified formulas are non-empty. This means that model-building for fmf will initialize *function* domains to be non-empty since synthesis conjectures quantify over functions.  This means we need an enumerator for function values.

**Comment by iwob** [comment] 2017-11-09 21:04
Thank you for the quick fix!

**Comment by ajreynol** [comment] 2017-11-13 20:21
#1243 is now merged, master version of CVC4 now does not initially give up for this benchmark.  Btw, you can expect improvements on CVC4's performance for SyGuS + strings soon (see #1337 for instance).

**Closed** 2017-11-13 20:22 UTC
Labels: bug, normal
