### ISSUE TITLE
--strings-exp --sygus-inference Fatal failure at CVC4/src/theory/datatypes/sygus_extension.cpp:1144

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3636] opened 2020-01-22 14:43 UTC
Hi,
For this formula,
```
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun e () Real)
(assert
 (exists ((d Real))
  (and
   (or
    (and
     (and
      (and
       (or
        (and
         (or
          (or (< 0 d) (<= d e))
          (>= (/ 149 d b) 10))
         (> e 0))
        (< b 10))
       (= c 0))
      (>= b 1))
     (> b 12))
    (>= b (- 157 10 a)))
   (and (distinct c 3.0) (< (* 32 e b) 12)))))
(check-sat)
```
`cvc4 --strings-exp --sygus-inference` throws out a fatal failure:
```
Fatal failure within CVC4::Node CVC4::theory::datatypes::SygusExtension::registerSearchValue(CVC4::Node, CVC4::Node, CVC4::Node, unsigned int, std::vector<CVC4::NodeTemplate<true> >&, bool, bool) at CVC4/src/theory/datatypes/sygus_extension.cpp:1144
Check failure
 d_tds->getSygusTermSize(bad_val) == sz
Aborted
```
OS: Ubuntu 18.04
Revision: 3de5e8d

**Comment by ajreynol** [comment] 2020-01-30 20:08
How long does CVC4 take before returning this?  I can't reproduce this with a debug build.

**Comment by zhendongsu** [comment] 2020-01-30 23:14
Hi Andrew, here is what I see (configured the latest CVC4 with "./configure.sh --assertions"):  

```
[505] % time cvc4nofp --strings-exp --sygus-inference --quiet pr3636.smt2 
Fatal failure within CVC4::Node CVC4::theory::datatypes::SygusExtension::registerSearchValue(CVC4::Node, CVC4::Node, CVC4::Node, unsigned int, std::vector<CVC4::NodeTemplate<true> >&, bool, bool) at /home/suz/software/CVC4_nosymfpu/src/theory/datatypes/sygus_extension.cpp:1144
Check failure

 d_tds->getSygusTermSize(bad_val) == sz

Aborted

real	0m6.576s
user	0m6.545s
sys	0m0.016s
[506] % 
```

**Comment by ajreynol** [comment] 2020-03-11 20:40
I can't reproduce this in master, can you confirm whether or not this is still an issue?

**Comment by zhendongsu** [comment] 2020-03-15 14:02
Andrew, the following formula still triggers this crash (although on a slightly different line and using also the flag --produce-models): 
```
[1035] % time cvc4 --quiet --strings-exp --sygus-inference --produce-models small.smt2
Fatal failure within CVC4::Node CVC4::theory::datatypes::SygusExtension::registerSearchValue(CVC4::Node, CVC4::Node, CVC4::Node, unsigned int, std::vector<CVC4::NodeTemplate<true> >&, bool, bool) at /home/suz/software/CVC4/src/theory/datatypes/sygus_extension.cpp:1131
Check failure

 d_tds->getSygusTermSize(bad_val) == sz

Aborted

real	0m12.252s
user	0m11.144s
sys	0m0.036s
[1036] % 
[1036] % cat small.smt2
(declare-fun a () Real)
(declare-fun b () Real)
(declare-fun c () Real)
(declare-fun d () Real)
(assert (> a 103))
(assert (> b 234))
(assert (<= c 184))
(assert (< d 107))
(assert (or (>= a b) (>= b c) (>= c d)))
(assert (< (/ 115 a d) (/ 137 b c)))
(check-sat)
[1037] % 
```

**Comment by nafur** [comment] 2020-08-17 13:44
I've tried as well, and I've not managed to reproduce the error on any of the examples with `./configure.sh --assertions` on either 3de5e8d or the current master (where it is immediately found to be satisfiable). I thus close this issue, please come back to use if you see this issue again.

**Closed by nafur** 2020-08-17 13:44 UTC
