### ISSUE TITLE
Fatal failure at CVC4/src/expr/type_node.cpp:482

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3618] opened 2020-01-19 06:09 UTC
Hi,
For this formula,
```
(assert (= 0 (ite true 0 (ite true 0 ""))))
(check-sat)
```
CVC4 throws out a fatal failure:
```
Fatal failure within static CVC4::TypeNode CVC4::TypeNode::commonTypeNode(CVC4::TypeNode, CVC4::TypeNode, bool) at CVC4/src/expr/type_node.cpp:482
Check failure
 !t1.isNull()
Aborted
```

OS: Ubuntu 18.04
Revision: c3bc4ac

**Comment by ajreynol** [comment] 2020-01-22 20:49
In both production and debug, I get this:
```
(error "Both branches of the ITE must be a subtype of a common type.
then branch: 0
its type   : Int
else branch: """"
its type   : String
")
```
How did you configure cvc4?

**Comment by muchang** [comment] 2020-01-23 09:47
Hi Andrew,

I configured cvc4 with the command `./configure.sh production --assertions`.

**Comment by nafur** [comment] 2020-08-04 09:26
I can confirm that (as of c3bc4ac99c36029b78d866ffb89bd0d322821f34) we crashed with
```
Fatal failure within static CVC4::TypeNode CVC4::TypeNode::commonTypeNode(CVC4::TypeNode, CVC4::TypeNode, bool) at /home/gereon/cvc4_master/src/expr/type_node.cpp:482
Check failure

 !t1.isNull()
```
Since 5c844f064cf6394030918c32f42d0764703b9786, however, the proper error is printed:
```
(error "Parse Error: test.smt2:1.39: Both branches of the ITE must be a subtype of a common type.

  (assert (= 0 (ite true 0 (ite true 0 ""))))
                                     ^

then branch: 0
its type   : Int
else branch: ""
its type   : String
")
```
We thus close this issue as fixed.

**Closed by nafur** 2020-08-04 09:26 UTC
Labels: minor
