### ISSUE TITLE
Fatal failure at theory/arith/normal_form.h:768 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4344] opened 2020-04-19 08:34 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_AUFNRA)
(set-option :proof true)
(declare-const arr (Array Bool Bool))
(assert (! (select arr (= 0.0 5202974007.0 (- 0.0) 0.0)) :named IP_6))
(assert false)
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within CVC4::theory::arith::Polynomial::Polynomial(CVC4::TNode) at /home/peisen/test/tofuzz/CVC4/src/./theory/arith/normal_form.h:768
Check failure

 isMember(getNode())

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:53
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:53 UTC
