### ISSUE TITLE
Assertion failure with tlimit

### ISSUE THREAD

**Issue by mudathirmahgoub** [CVC4/CVC4#3040] opened 2019-06-05 00:52 UTC
[alloy.txt](https://github.com/CVC4/CVC4/files/3255025/alloy.txt)
```
cvc4-2019-05-26-win64-opt.exe --produce-models --incremental --lang smtlib2.6 alloy.txt
```
output
```
unsupported
unknown
unknown
(error "Assertion failure.
void CVC4::ResourceManager::beginCall()
/home/nightly/CVC4-master/src/util/resource_manager.cpp:216:

  d_cumulativeTimer.on()
")
```
[alloy2.txt](https://github.com/CVC4/CVC4/files/3255026/alloy2.txt)
when the tlimit option is changed from 30 seconds to 3 seconds in the second file here is the output
```
cvc4-2019-05-26-win64-opt.exe --produce-models --incremental --lang smtlib2.6 alloy2.txt
unsupported
unknown
unknown
unknown
```

**Comment by 4tXJ7f** [comment] 2019-06-05 09:28
Thanks for the report @mudathirmahgoub. I was able to reproduce this and will take a look.

**Comment by ajreynol** [comment] 2019-08-28 21:29
Marking duplicate of #2908.

**Closed by ajreynol** 2019-08-28 21:29 UTC
Labels: bug, duplicate
