### ISSUE TITLE
Fatal failure at theory/arith/constraint.cpp:1722 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4360] opened 2020-04-19 09:50 UTC
Hi,
For the following formula:
~~~~
(set-logic AUFLRA)
(set-option :proof true)
(declare-fun arr () (Array Bool Bool))
(declare-const r0 Real)
(declare-const r3 Real)
(assert false)
(assert (! (select (store arr (> r3 r0 0.0 r3 0.6491177755) true) true) :named IP_40))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within void CVC4::theory::arith::Constraint::setLiteral(CVC4::Node) at /home/peisen/test/tofuzz/CVC4/src/theory/arith/constraint.cpp:1722
Check failure

 !hasLiteral()

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
