### ISSUE TITLE
Fatal failure at proof/theory_proof.cpp:1364 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4341] opened 2020-04-19 08:23 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_AUFNRA)
(set-option :proof true)
(declare-const r2 Real)
(assert (! (= true true true (> 0.0 (/ 0.0 r2) 7175577.95)) :named IP_21))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
(% A0 (th_holds (and (iff true true) (and (iff true true) (iff true (and (>_Real (/_Real (term_int_to_real (a_int 0))  (term_int_to_real (a_int 1)) ) (ite _ Fatal failure within virtual CVC4::TypeNode CVC4::TheoryProof::equalityType(const CVC4::Expr&, const CVC4::Expr&) at /home/peisen/test/tofuzz/CVC4/src/proof/theory_proof.cpp:1364
Check failure

 left.getType() == right.getType()
TheoryProof::equalityType(r2, 0):
types disagree:
        left: Real
        right:Int
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:53
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:53 UTC

**Comment by rainoftime** [comment] 2020-04-19 13:57
Why duplicate? Do you mean they have the same root cause?
