### ISSUE TITLE
Fatal failure at proof/arith_proof.cpp:1053 (proof, cbqi-all)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4342] opened 2020-04-19 08:27 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_UFLIA)
(declare-fun _substvar_422_ () Bool)
(set-option :proof true)
(set-option :cbqi-all true)
(declare-const i1 Int)
(assert (! (= false false false false (distinct 24 i1)) :named IP_28))
(assert (! (or (= true true true true true (>= (div i1 701) 24) true true true) (distinct false true _substvar_422_)) :named IP_72))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
  (@ pf_aff.l155 Fatal failure within std::pair<CVC4::NodeTemplate<true>, std::__cxx11::basic_string<char> > CVC4::LFSCArithProof::printProofAndMaybeTighten(const Node&) at /home/peisen/test/tofuzz/CVC4/src/proof/arith_proof.cpp:1053
Unreachable code reached
Aborted (core dumped)

~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:53
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:53 UTC
