### ISSUE TITLE
Unknown on NRA formula without variables

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#3429] opened 2019-11-04 07:53 UTC
Hi, 

for the following formula without variables  CVC4 returns `unknown`.
```
(set-logic NRA) 
(assert (<= (* (/ 0 0) (/ (- (/ 1 2)) 0 (- (/ 1 2)))) (/ (- 1) 4))) 
(check-sat)
``` 

When using the `--sygus-inference` option CVC4 returns `sat`.

OS: Ubuntu 18.04
Revision: c547bd591891ffd9211ed3859b0a67423a708f25

**Comment by 4tXJ7f** [comment] 2019-11-04 15:38
This is a duplicate of #3428. See @ajreynol's [comment](https://github.com/CVC4/CVC4/issues/3428#issuecomment-549184675) for why we don't consider this to be a bug.

**Closed by 4tXJ7f** 2019-11-04 15:38 UTC
