### ISSUE TITLE
parse error on `match` expressions

### ISSUE THREAD

**Issue by c-cube** [CVC4/CVC4#5128] opened 2020-09-23 20:01 UTC
**Describe the bug**

A basic "match" expression fails to parse, and I think it is compliant with smtlib2.6 (z3 accepts it). The report says that `_` is an acceptable variable, and `A` is a nullary constructor so the first case seems well formed to me.

```
(set-logic ALL)
(declare-datatypes ((t 0)) (((A) (B) (C) (D))))
(define-fun f ((x t)) t (match x ((A B) (_ x))))
```

gets:

```sh
$ cvc4 foo.smt2
(error "Parse Error: foo.smt2:3.42: Unexpected token: '('.")
```

**Command line arguments**: Command line arguments passed to CVC4 if applicable
**CVC4 version/commit**: 

```
$ cvc4 --version
This is CVC4 version 1.8
compiled with GCC version 10.2.0
on Sep 14 2020 11:24:28
```

**Operating system**: archlinux

**Comment by ajreynol** [comment] 2020-09-23 20:06
Thanks for the report.

This conversation may be relevant here: https://github.com/CVC4/CVC4/pull/3258/files#r328762350

As I recall our parser does not accept `_` as a variable name when it should. I'll look into this.

**Comment by c-cube** [comment] 2020-09-23 20:21
Thank you. There's really no hurry there, I wanted to make sure I wasn't going crazy :)

**Comment by 4tXJ7f** [comment] 2020-09-23 20:55
The [standard](http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf) does not allow this. Page 25 says:

> A simple symbol is any non-empty sequence of elements [...] that does not start with a digit and is not a reserved word

And page 95 lists `_` as a reserved keyword. Page 96 requires the first argument of a `<match case>` to be a `<symbol>`. There examples (e.g. page 29) that use `_` in a `match` statement. I've confirmed with one of the SMT-LIB authors that the example is indeed wrong but it looks like it hasn't been fixed yet. One option may be to use `|_|` instead. Hope this helps!

**Comment by c-cube** [comment] 2020-09-23 21:12
Good catch. That's unfortunate that `_` is reserved, I'd rather have the standard accept a symbol **OR** `_` as it's a very common way of writing the default/catch-all case. A lot of languages use `_` as a wildcard/blank.

**Comment by 4tXJ7f** [comment] 2020-09-24 01:05
Yes, it would certainly possible to change the standard in that direction. I guess it would have to be reserved for the default/catch-all case though, since you can't use `_` in the second argument of `<match_case>`. If you are interested in starting a discussion about changing the standard, it would probably be best to do so on the [SMT-LIB mailing list](https://groups.google.com/g/smt-lib). I am closing the issue for now but please don't hesitate to reach out if you run into other issues.

**Closed by 4tXJ7f** 2020-09-24 01:05 UTC
