### ISSUE TITLE
Fatal failure at proof/arith_proof.cpp:1131 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4343] opened 2020-04-19 08:31 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_NRA)
(set-option :proof true)
(declare-const r1 Real)
(declare-const r3 Real)
(declare-const r7 Real)
(assert (! (= r1 (/ r3 67703.0) r7 r3 0.703) :named IP_82))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
  (@ pf_aff.l9 Fatal failure within virtual void CVC4::LFSCArithProof::printTheoryLemmaProof(std::vector<CVC4::Expr>&, std::ostream&, std::ostream&, const ProofLetMap&) at /home/peisen/test/tofuzz/CVC4/src/proof/arith_proof.cpp:1131
Unreachable code reached
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:53
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:53 UTC
