### ISSUE TITLE
Fatal failure at proof/theory_proof.cpp:421 (proof)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4357] opened 2020-04-19 09:29 UTC
Hi,
For the following formula:
~~~~
(set-logic QF_UFLIA)
(set-option :proof true)
(declare-const i0 Int)
(assert (! (or (distinct (+ (abs i0) i0 0) i0) (< 0 i0)) :named IP_1))
(assert (! (or (< (+ 0 i0 (abs i0)) i0) (= 0 i0)) :named IP_11))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
Fatal failure within void CVC4::LFSCTheoryProofEngine::printLemmaRewrites(CVC4::NodePairSet&, std::ostream&, std::ostream&) at /home/peisen/test/tofuzz/CVC4/src/proof/theory_proof.cpp:421
Check failure

 n1.toExpr() == utils::mkFalse() || theory::Theory::theoryOf(n1) == theory::Theory::theoryOf(n2)

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:51
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:51 UTC
