### ISSUE TITLE
Segfault with incremental unsat cores

### ISSUE THREAD

**Issue by daniel-larraz** [CVC4/CVC4#1349] opened 2017-11-10 16:25 UTC
The attached SMT2 problems result in segmentation faults when running cvc4 in incremental mode

[CVC4_Segfaults.tar.gz](https://github.com/CVC4/CVC4/files/1461966/CVC4_Segfaults.tar.gz)

**Comment by timothy-king** [comment] 2017-11-18 23:55
The issue seems to be a clause id gets popped from a CDHashMap within the sat proofs module and then later re-used after being popped. Not sure what the root cause of this happening is.

Details:
Digging into this a bit, it is fairly easy to trigger an assertion failure in debug mode. The issue is in the sat proof implementation. We can add some debugging to identify the failing id, the context & level of d_resolution chains being inserted.
```cc
--- a/src/proof/sat_proof_implementation.h
+++ b/src/proof/sat_proof_implementation.h
@@ -455,6 +455,11 @@ bool TSatProof<Solver>::hasResolutionChain(ClauseId id) const {
 template <class Solver>
 const typename TSatProof<Solver>::ResolutionChain&
 TSatProof<Solver>::getResolutionChain(ClauseId id) const {
+  if (Debug.isOn("getResolutionChain") && !hasResolutionChain(id))
+  {
+    Debug("getResolutionChain") << "getResolutionChain(" << id << ")"
+                                << " will fail" << std::endl;
+  }
   Assert(hasResolutionChain(id));
   const ResolutionChain* chain = (*d_resolutionChains.find(id)).second;
   return *chain;
@@ -727,10 +732,11 @@ void TSatProof<Solver>::registerResolution(ClauseId id, ResChain<Solver>* res) {
     ResChain<Solver>* current = (*d_resolutionChains.find(id)).second;
     delete current;
   }
-
   d_resolutionChains.insert(id, res);

   if (Debug.isOn("proof:sat")) {
+    Debug("proof:sat") << "@" << d_context << "." << d_context->getLevel()
+                       << " ";
     printRes(id);
   }
   if (d_checkRes) {
```
We can then run with `-d proof:sat -d pushpop -d getResolutionChain` to identify the issue. The offending clause will be `7795`. This was inserted into d_resolutionChains (CDHashMap) within context `0xae3730` at level 3 and after this insertion `0xae3730` is popped to level 2, `    } Pop [to 2] 0xae3730`.

**Comment by tinelli** [comment] 2018-04-11 03:09
Any progress on this?

**Comment by 4tXJ7f** [comment] 2018-04-16 05:39
Hi Cesare, sorry for the late reply. I do know what the issue is but the fix is fairly complicated. It is one of the top items on my list.

**Comment by 4tXJ7f** [comment] 2018-05-22 23:46
The current plan is to do some major refactoring of how resolution proofs are dealt handled. In the meantime, I have implemented a workaround in PR #1962. @daniel-larraz The workaround seems to work for the provided examples but it would be great if you could test it also.

**Comment by daniel-larraz** [comment] 2018-05-24 15:29
I ran Kind 2 over the original problem and I got another SMT file that results in a segmentation fault. Please see the attached file.
[CVC4_Segfault_2.zip](https://github.com/CVC4/CVC4/files/2036015/CVC4_Segfault_2.zip)

**Comment by 4tXJ7f** [comment] 2018-05-24 22:01
Ugh, it looks like this is not related to unsat cores, not good :/ I'll open a different issue for it.

**Comment by 4tXJ7f** [comment] 2018-05-25 17:41
@daniel-larraz I might have a fix for the issue on the following branch: https://github.com/4tXJ7f/CVC4/tree/fix_sat_solver (note the branch includes the fix for incremental unsat cores as well). If you have time, it would be great if you could test the fix. I am going to do some of my own testing in the meantime.

**Comment by daniel-larraz** [comment] 2018-05-25 20:22
I tested the last fix and I didn't find more segmentation faults. Thanks!

**Comment by 4tXJ7f** [comment] 2018-06-26 02:32
@daniel-larraz All the necessary fixes should be on master and part of the 1.6 release. If you find time, could you please double check?

**Comment by daniel-larraz** [comment] 2018-06-26 15:58
I found two new segmentation faults when testing the latest version of Kind 2 with [cvc4 1.6](http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.6-x86_64-linux-opt) :-(
See attached file: [CVC4_Segfault_3.tar.gz](https://github.com/CVC4/CVC4/files/2137887/CVC4_Segfault_3.tar.gz)

**Comment by 4tXJ7f** [comment] 2018-06-28 06:47
@daniel-larraz I have submitted a fix for the issue in PR #2113.

**Comment by 4tXJ7f** [comment] 2018-06-28 19:20
The fix has been merged to master. Please take a look when you get the chance.

**Comment by daniel-larraz** [comment] 2018-06-29 16:52
I ran Kind 2 benchmarks again, and I didn't get more segmentation faults. Thanks.

**Comment by 4tXJ7f** [comment] 2018-06-29 18:08
Great! I am closing this for now. Please let me know if you find any other issues.

**Closed by 4tXJ7f** 2018-06-29 18:08 UTC
Labels: bug, major
