### ISSUE TITLE
nl-ext-factor nl-ext-tplanes refine-conflicts fatal failure at src/theory/arith/nonlinear_extension.cpp:3330

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4091] opened 2020-03-15 04:41 UTC
Hi,
For this formula:
```
(set-option :nl-ext-factor false)       
(set-option :nl-ext-tplanes true)                                
(set-option :refine-conflicts true)                               
(assert (< (sin 51) 0.9)) 
(check-sat)
```
CVC4  throws out a fatal failure:
```
Fatal failure within bool CVC4::theory::arith::NonlinearExtension::checkTfTangentPlanesFun(CVC4::Node, unsigned int, std::vector<CVC4::NodeTemplate<true> >&, std::map<CVC4::NodeTemplate<true>, CVC4::theory::arith::NlLemmaSideEffect>&) at src/theory/arith/nonlinear_extension.cpp:3330
Check failure

 std::find( d_secant_points[tf][d].begin(), d_secant_points[tf][d].end(), c) == d_secant_points[tf][d].end()

Aborted
```

OS: Ubuntu 18.04
Commit: 442ab0c

**Comment by ajreynol** [comment] 2020-03-15 13:47
`refine-conflicts` will be deleted, duplicate of #4008.

**Closed by ajreynol** 2020-03-15 13:47 UTC
