### ISSUE TITLE
Fatal failure at theory/bv/bitblast/bitblast_strategies_template.h:848 (proof, decision-use-weight)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4347] opened 2020-04-19 08:44 UTC
Hi,
For the following formula:
~~~~
(set-logic ABV)
(set-option :proof true)
(set-option :decision-use-weight true)
(declare-const arr-147552388477323218_6218735561158255477-0 (Array (_ BitVec 27) Bool))
(assert false)
(assert (! (select arr-147552388477323218_6218735561158255477-0 (bvsmod (_ bv0 27) ((_ repeat 3) (_ bv0 9)))) :named IP_12))
(check-sat)
(get-proof)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
(check
 ;; Declarations
Fatal failure within void CVC4::theory::bv::DefaultRepeatBB(CVC4::TNode, std::vector<_RealType>&, CVC4::theory::bv::TBitblaster<T>*) [with T = CVC4::NodeTemplate<true>; CVC4::TNode = CVC4::NodeTemplate<false>] at /home/peisen/test/tofuzz/CVC4/src/./theory/bv/bitblast/bitblast_strategies_template.h:848
Unimplemented code encountered
Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ecf3e9c87409

**Comment by ajreynol** [comment] 2020-04-19 13:52
Duplicate of #4337.

**Closed by ajreynol** 2020-04-19 13:52 UTC
