### ISSUE TITLE
Fatal failure at src/theory/quantifiers_engine.cpp:720

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#4400] opened 2020-04-27 21:33 UTC
```
[515] % cvc4 -q small.smt2
unsat
[516] % cvc4 -q --fmf-fun small.smt2
Fatal failure within void CVC4::theory::QuantifiersEngine::check(CVC4::theory::Theory::Effort) at src/theory/quantifiers_engine.cpp:720
Check failure
 !d_conflict
Aborted
[517] % 
[517] % cat small.smt2
(declare-datatypes ((ap 0)) (((bp) (cp (p (_ BitVec 32)) (dp (_ BitVec 32)) (leftp ap) (aap ap)))))
(declare-datatypes ((ep 0)) (((fp (gp (_ BitVec 32)) (jp ep)) (kp))))
(declare-fun abp () Bool)
(declare-fun mp (ap) Bool)
(declare-fun op (ap) (_ BitVec 32))
(declare-fun abp6 () ap)
(declare-fun abp7 () ap)
(declare-fun abp1 () ap)
(declare-fun acp2 ((_ BitVec 32) ap) ap)
(declare-fun qp ((_ BitVec 32) ap ap) ap)
(declare-fun rp (ep ap) ap)
(declare-fun adp (ap ap) ap)
(declare-fun abp9 () ap)
(declare-sort sp 0)
(declare-fun mpae (sp) ap)
(declare-sort tp 0)
(declare-fun opu (tp) ap)
(declare-sort up2 0)
(declare-fun acp2v (up2) (_ BitVec 32))
(declare-fun acp2w (up2) ap)
(declare-sort afp 0)
(declare-fun qpag (afp) (_ BitVec 32))
(declare-fun qpah (afp) ap)
(declare-fun qpai (afp) ap)
(declare-sort ajp 0)
(declare-fun rpak (ajp) ep)
(declare-fun rpal (ajp) ap)
(declare-sort amp 0)
(declare-fun adpan (amp) ap)
(declare-fun adpao (amp) ap)
(assert (forall ((i sp)) (and (= (mp (mpae i)) (ite ((_ is bp) (mpae
 i)) true (ite ((_ is cp) (mpae i)) (and (mp (aap (mpae i)))) abp))
 true (ite ((_ is cp) (mpae i)) (and (not (forall ((z tp)) (not (=
 (opu z) (mpae i)))))) true)))))
(assert (forall ((i up2)) (and (= (acp2 (acp2v i) (acp2w i)) (adp (cp
 (_ bv1 32) (acp2v i) bp bp) (acp2w i))) (not (forall ((z amp)) (not
 (and (= (adpan z) (cp (_ bv1 32) (acp2v i) bp bp)) (= (adpao z)
 (acp2w i)))))))))
(assert (forall ((i afp)) (and (= (qp (qpag i) (qpah i) (qpai i)) (ite
 (not (bvslt (op (qpah i)) (op (qpai i)))) (cp (bvadd (op (qpai i))
 (_ bv1 32)) (qpag i) (qpah i) (qpai i)) (cp (bvadd (op (qpah i)) (_
 bv1 32)) (qpag i) (qpai i) (qpah i)))) (not (forall ((z tp)) (not (=
 (opu z) (qpah i))))) (not (forall ((z tp)) (not (= (opu z) (qpai
 i))))))))
(assert (forall ((i ajp)) (and (= (rp (rpak i) (rpal i)) (ite ((_ is
 kp) (rpak i)) (rpal i) (ite ((_ is fp) (rpak i)) (rp (jp (rpak i))
 (acp2 (gp (rpak i)) (rpal i))) abp6))) (ite ((_ is kp) (rpak i))
 true (ite ((_ is fp) (rpak i)) (and (not (forall ((z up2)) (not (and
 (= (acp2w z) (rpal i))))))) true)))))
(assert (forall ((i amp)) (and (= (adp (adpan i) (adpao i)) (ite ((_
 is bp) (adpan i)) (adpao i) (ite ((_ is cp) (adpan i)) (ite ((_ is
 bp) (adpao i)) (adpan i) (ite ((_ is cp) (adpao i)) (ite (bvslt (dp
 (adpao i)) (dp (adpan i))) (qp (dp (adpan i)) (leftp (adpan i)) (adp
 (aap (adpan i)) (adpao i))) (qp (dp (adpao i)) (leftp (adpao i))
 (adp (adpan i) (aap (adpao i))))) abp7)) abp1))) (ite ((_ is bp)
 (adpan i)) true (ite ((_ is cp) (adpan i)) (ite ((_ is bp) (adpao
 i)) true (ite ((_ is cp) (adpao i)) (ite (bvslt (dp (adpao i)) (dp
 (adpan i))) (and (not (forall ((z afp)) (not (and (= (qpag z) (dp
 (adpan i))) (= (qpah z) (leftp (adpan i))) (= (qpai z) (adp (aap
 (adpan i)) (adpao i)))))))) (and (not (forall ((z amp)) (not (and (=
 (adpao z) (aap (adpao i))))))))) true)) true)))))
(assert (exists ((hp ap) (lp ep)) (not (=> (and (mp hp) (not (forall
 ((z sp)) (not (= (mpae z) hp))))) (and (and (or (mp (ite ((_ is kp)
 lp) hp (ite ((_ is fp) lp) (rp (jp lp) (acp2 (gp lp) hp)) abp9)))
 (forall ((z sp)) (not (= (mpae z) (ite ((_ is kp) lp) hp (ite ((_ is
 fp) lp) (rp (jp lp) (acp2 (gp lp) hp)) abp9))))) (not (ite ((_ is
 kp) lp) true (ite ((_ is fp) lp) (and (not (forall ((z ajp)) (not
 (and (= (rpak z) (jp lp)) (= (rpal z) (acp2 (gp lp) hp)))))) (not
 (forall ((z up2)) (not (and (= (acp2v z) (gp lp)) (= (acp2w z)
 hp)))))) true)))) (or (mp (ite ((_ is kp) lp) hp (ite ((_ is fp) lp)
 (rp (jp lp) (acp2 (gp lp) hp)) abp9))) (forall ((z sp)) (not (=
 (mpae z) (ite ((_ is kp) lp) hp (ite ((_ is fp) lp) (rp (jp lp)
 (acp2 (gp lp) hp)) abp9))))) (not (ite ((_ is kp) lp) true (ite ((_
 is fp) lp) (and (not (forall ((z ajp)) (not (and (= (rpak z) (jp
 lp)) (= (rpal z) (acp2 (gp lp) hp)))))) (not (forall ((z up2)) (not
 (and (= (acp2v z) (gp lp)) (= (acp2w z) hp)))))) true))))))))))
(check-sat)
[518] %
```

OS: Ubuntu 18.04
Commit: dc9b11c

**Comment by nafur** [comment] 2020-08-18 10:17
This example works since 8b5ffcd602730db5bba135b557f60ca181b8af1f, though I'm somewhat suspicious that it merely hides the issue. A slightly smaller example that triggers this issue (until 8b5ffcd602730db5bba135b557f60ca181b8af1f):
```
(declare-datatypes ((ap 0)) (((bp) (cp (p (_ BitVec 2)) (dp (_ BitVec 2))
  (leftp ap) (aap ap)))))
(declare-datatypes ((ep 0)) (((kp) (fp (jp ep) (gp (_ BitVec 2))))))
(declare-fun mp (ap) Bool)
(declare-fun op (ap) (_ BitVec 2))
(declare-fun abp1 () ap)
(declare-fun acp2 ((_ BitVec 2) ap) ap)
(declare-fun qp ((_ BitVec 2) ap ap) ap)
(declare-fun rp (ep ap) ap)
(declare-fun adp (ap ap) ap)
(declare-fun abp9 () ap)
(declare-sort sp 0)
(declare-fun mpae (sp) ap)
(declare-sort tp 0)
(declare-fun opu (tp) ap)
(declare-sort up2 0)
(declare-fun acp2v (up2) (_ BitVec 2))
(declare-fun acp2w (up2) ap)
(declare-fun qpag (up2) (_ BitVec 2))
(declare-fun qpah (up2) ap)
(declare-fun qpai (up2) ap)
(declare-fun adpan (up2) ap)
(declare-fun adpao (up2) ap)
(assert (forall ((i sp)) (= (mp (mpae i)) (ite ((_ is bp) (mpae i)) true (mp
  (aap (mpae i)))) true (ite ((_ is cp) (mpae i)) (exists ((z tp)) (= (opu z)
  (mpae i))) true))))
(assert (forall ((i up2)) (and (= (acp2w i) (adp abp9 (cp (_ bv1 2) (acp2v i)
  bp bp))) (exists ((z up2)) (and (= (adpao z) (acp2w i)) (= (adpan z) (cp (_
  bv1 2) (acp2v i) bp bp)))))))
(assert (forall ((i up2)) (and (exists ((z tp)) (= (opu z) (qpah i))) (exists
  ((z tp)) (= (opu z) (qpai i))) (= (qp (qpag i) (qpah i) (qpai i)) (ite
  (bvslt (op (qpah i)) (op (qpai i))) (cp (bvadd (op (qpai i)) (_ bv1 2))
  (qpag i) (qpah i) (qpai i)) (cp (bvadd (op (qpah i)) (_ bv1 2)) (qpag i)
  (qpai i) (qpah i)))))))
(assert (forall ((i up2)) (and (exists ((z up2)) (and (= (qpag z) (dp abp1))
  (= (qpah z) (leftp (adpan i))))) (= (adpao i) (ite ((_ is bp) (adpao i))
  (adpan i) (qp (dp abp9) (leftp (adpan i)) (adpao i)))))))
(assert (exists ((hp ap) (lp ep)) (not (=> (exists ((z sp)) (= hp (mpae z)))
  (or (forall ((z up2)) (not (= hp (acp2w z)))) (mp (ite ((_ is kp) lp) hp (rp
  (jp lp) (acp2 (gp lp) hp)))) (forall ((z sp)) (not (= (mpae z) (ite ((_ is
  kp) lp) hp (rp (jp lp) (acp2 (gp lp) hp)))))))))))
(check-sat)
```

**Comment by ajreynol** [comment] 2021-04-05 19:58
Due to how minor this issue is and that is not replicated on master, I'm going to add the minimized regression and close this issue.

**Closed** 2021-04-08 10:05 UTC
Labels: minor
