### ISSUE TITLE
significant slowdown on linear problem with non-linear set-logic

### ISSUE THREAD

**Issue by florianschanda** [CVC4/CVC4#1276] opened 2017-10-25 13:41 UTC
Hi,

I know one should always use as tight a set-logic as is reasonable. But a) we don't in SPARK because of architectural reasons w.r.t. why3 and b) I found this one by accident.

On the below, I get an answer in ~2 seconds. If I change the "LIRA" to "NIRA" then it takes ~22 seconds. I found this because `cvc4 --no-cbqi` complains about a non-linear fact, despite the VC not containing any (as far as I can tell).

```
(set-info :smt-lib-version 2.5)
(set-info :license |https://www.gnu.org/licenses/gpl-3.0.html|)
(set-logic UFBVDTLIRA)
(set-info :source |Benchmarks generated by Florian Schanda from the public SPARK 2014 testsuite and post-processed with a script to set more precise logics.|)
(set-info :category industrial)
(set-info :status unknown)

(declare-datatypes () ((tuple0 (Tuple0))))
(declare-sort us_private 0)
(declare-fun private__bool_eq (us_private us_private) Bool)
(declare-const us_null_ext__ us_private)
(declare-sort us_type_of_heap 0)
(declare-datatypes () ((us_type_of_heap__ref (mk___type_of_heap__ref (us_type_of_heap__content us_type_of_heap)))))
(declare-sort us_image 0)
(declare-datatypes () ((int__ref (mk_int__ref (int__content Int)))))
(declare-datatypes () ((bool__ref (mk_bool__ref (bool__content Bool)))))
(declare-datatypes () ((real__ref (mk_real__ref (real__content Real)))))
(declare-datatypes () ((us_private__ref (mk___private__ref (us_private__content us_private)))))
(define-fun int__ref___projection ((a int__ref)) Int (int__content a))
(define-fun bool__ref___projection ((a bool__ref)) Bool (bool__content a))
(define-fun real__ref___projection ((a real__ref)) Real (real__content a))
(define-fun us_private__ref___projection ((a us_private__ref)) us_private (us_private__content a))
(declare-fun nth ((_ BitVec 64) Int) Bool)
(declare-fun lsr ((_ BitVec 64) Int) (_ BitVec 64))
(declare-fun asr ((_ BitVec 64) Int) (_ BitVec 64))
(declare-fun lsl ((_ BitVec 64) Int) (_ BitVec 64))
(declare-fun rotate_right1 ((_ BitVec 64) Int) (_ BitVec 64))
(declare-fun rotate_left1 ((_ BitVec 64) Int) (_ BitVec 64))
(declare-fun pow2 (Int) Int)
(define-fun to_int1 ((x (_ BitVec 64))) Int (ite (bvsge x (_ bv0 64)) (bv2nat x) (- (- 18446744073709551616 (bv2nat x)))))
(define-fun uint_in_range ((i Int)) Bool (and (<= 0 i) (<= i 18446744073709551615)))
(assert (forall ((x (_ BitVec 64)) (n (_ BitVec 64))) (= (bvlshr x n) (lsr x (bv2nat n)))))
(assert (forall ((x (_ BitVec 64)) (n (_ BitVec 64))) (= (bvashr x n) (asr x (bv2nat n)))))
(assert (forall ((x (_ BitVec 64)) (n (_ BitVec 64))) (= (bvshl x n) (lsl x (bv2nat n)))))
(assert (forall ((v (_ BitVec 64)) (n (_ BitVec 64))) (= (bvor (bvshl v (bvurem n (_ bv64 64))) (bvlshr v (bvsub (_ bv64 64) (bvurem n (_ bv64 64))))) (rotate_left1 v (bv2nat n)))))
(assert (forall ((v (_ BitVec 64)) (n (_ BitVec 64))) (= (bvor (bvlshr v (bvurem n (_ bv64 64))) (bvshl v (bvsub (_ bv64 64) (bvurem n (_ bv64 64))))) (rotate_right1 v (bv2nat n)))))
(declare-fun nth_bv ((_ BitVec 64) (_ BitVec 64)) Bool)
(assert (forall ((x (_ BitVec 64)) (i (_ BitVec 64))) (= (= (nth_bv x i) true) (not (= (bvand (bvlshr x i) #x0000000000000001) #x0000000000000000)))))
(assert (forall ((x (_ BitVec 64)) (i (_ BitVec 64))) (= (nth x (bv2nat i)) (nth_bv x i))))
(assert (forall ((x (_ BitVec 64)) (i Int)) (=> (and (<= 0 i) (< i 18446744073709551616)) (= (nth_bv x ((_ int2bv 64) i)) (nth x i)))))
(declare-fun eq_sub_bv ((_ BitVec 64) (_ BitVec 64) (_ BitVec 64) (_ BitVec 64)) Bool)
(assert (forall ((a (_ BitVec 64)) (b (_ BitVec 64)) (i (_ BitVec 64)) (n (_ BitVec 64))) (let ((mask (bvshl (bvsub (bvshl #x0000000000000001 n) #x0000000000000001) i))) (= (eq_sub_bv a b i n) (= (bvand b mask) (bvand a mask))))))
(define-fun eq_sub ((a (_ BitVec 64)) (b (_ BitVec 64)) (i Int) (n Int)) Bool (forall ((j Int)) (=> (and (<= i j) (< j (+ i n))) (= (nth a j) (nth b j)))))
(assert (forall ((a (_ BitVec 64)) (b (_ BitVec 64)) (i (_ BitVec 64)) (n (_ BitVec 64))) (= (eq_sub a b (bv2nat i) (bv2nat n)) (eq_sub_bv a b i n))))
(declare-datatypes () ((t__ref (mk_t__ref (t__content (_ BitVec 64))))))
(declare-fun power ((_ BitVec 64) Int) (_ BitVec 64))
(define-fun bv_min ((x (_ BitVec 64)) (y (_ BitVec 64))) (_ BitVec 64) (ite (bvule x y) x y))
(define-fun bv_max ((x (_ BitVec 64)) (y (_ BitVec 64))) (_ BitVec 64) (ite (bvule x y) y x))
(declare-sort natural 0)
(define-fun in_range ((x Int)) Bool (and (<= 0 x) (<= x 2147483647)))
(declare-fun attr__ATTRIBUTE_IMAGE (Int) us_image)
(declare-fun attr__ATTRIBUTE_VALUE__pre_check (us_image) Bool)
(declare-fun attr__ATTRIBUTE_VALUE (us_image) Int)
(declare-fun user_eq (natural natural) Bool)
(declare-const dummy natural)
(declare-datatypes () ((natural__ref (mk_natural__ref (natural__content natural)))))
(define-fun natural__ref___projection ((a natural__ref)) natural (natural__content a))
(define-fun dynamic_invariant ((temp___expr_33 Int) (temp___is_init_30 Bool) (temp___skip_constant_31 Bool) (temp___do_toplevel_32 Bool)) Bool (=> (or (= temp___is_init_30 true) (<= 0 2147483647)) (in_range temp___expr_33)))
(declare-sort modular 0)
(declare-const attr__ATTRIBUTE_MODULUS (_ BitVec 64))
(declare-fun attr__ATTRIBUTE_IMAGE1 ((_ BitVec 64)) us_image)
(declare-fun attr__ATTRIBUTE_VALUE__pre_check1 (us_image) Bool)
(declare-fun attr__ATTRIBUTE_VALUE1 (us_image) (_ BitVec 64))
(declare-fun user_eq1 (modular modular) Bool)
(declare-const dummy1 modular)
(declare-datatypes () ((modular__ref (mk_modular__ref (modular__content modular)))))
(define-fun modular__ref___8__projection ((a modular__ref)) modular (modular__content a))
(define-fun dynamic_invariant1 ((temp___expr_351 (_ BitVec 64)) (temp___is_init_348 Bool) (temp___skip_constant_349 Bool) (temp___do_toplevel_350 Bool)) Bool true)
(declare-sort bit_position 0)
(define-fun in_range1 ((x Int)) Bool (and (<= 0 x) (<= x 63)))
(declare-fun attr__ATTRIBUTE_IMAGE2 (Int) us_image)
(declare-fun attr__ATTRIBUTE_VALUE__pre_check2 (us_image) Bool)
(declare-fun attr__ATTRIBUTE_VALUE2 (us_image) Int)
(declare-fun user_eq2 (bit_position bit_position) Bool)
(declare-const dummy2 bit_position)
(declare-datatypes () ((bit_position__ref (mk_bit_position__ref (bit_position__content bit_position)))))
(define-fun bit_position__ref___7__projection ((a bit_position__ref)) bit_position (bit_position__content a))
(define-fun dynamic_invariant2 ((temp___expr_357 Int) (temp___is_init_354 Bool) (temp___skip_constant_355 Bool) (temp___do_toplevel_356 Bool)) Bool (=> (or (= temp___is_init_354 true) (<= 0 63)) (in_range1 temp___expr_357)))
(declare-sort mask_size 0)
(define-fun in_range2 ((x Int)) Bool (and (<= 1 x) (<= x 64)))
(declare-fun attr__ATTRIBUTE_IMAGE3 (Int) us_image)
(declare-fun attr__ATTRIBUTE_VALUE__pre_check3 (us_image) Bool)
(declare-fun attr__ATTRIBUTE_VALUE3 (us_image) Int)
(declare-fun user_eq3 (mask_size mask_size) Bool)
(declare-const dummy3 mask_size)
(declare-datatypes () ((mask_size__ref (mk_mask_size__ref (mask_size__content mask_size)))))
(define-fun mask_size__ref___7__projection ((a mask_size__ref)) mask_size (mask_size__content a))
(declare-fun shift_right ((_ BitVec 64) Int) (_ BitVec 64))
(declare-fun shift_right__function_guard ((_ BitVec 64) (_ BitVec 64) Int) Bool)
(declare-fun nth1 ((_ BitVec 8) Int) Bool)
(declare-fun lsr1 ((_ BitVec 8) Int) (_ BitVec 8))
(declare-fun asr1 ((_ BitVec 8) Int) (_ BitVec 8))
(declare-fun lsl1 ((_ BitVec 8) Int) (_ BitVec 8))
(declare-fun rotate_right2 ((_ BitVec 8) Int) (_ BitVec 8))
(declare-fun rotate_left2 ((_ BitVec 8) Int) (_ BitVec 8))
(define-fun to_int2 ((x (_ BitVec 8))) Int (ite (bvsge x (_ bv0 8)) (bv2nat x) (- (- 256 (bv2nat x)))))
(define-fun uint_in_range1 ((i Int)) Bool (and (<= 0 i) (<= i 255)))
(assert (forall ((x (_ BitVec 8)) (n (_ BitVec 8))) (= (bvlshr x n) (lsr1 x (bv2nat n)))))
(assert (forall ((x (_ BitVec 8)) (n (_ BitVec 8))) (= (bvashr x n) (asr1 x (bv2nat n)))))
(assert (forall ((x (_ BitVec 8)) (n (_ BitVec 8))) (= (bvshl x n) (lsl1 x (bv2nat n)))))
(assert (forall ((v (_ BitVec 8)) (n (_ BitVec 8))) (= (bvor (bvshl v (bvurem n (_ bv8 8))) (bvlshr v (bvsub (_ bv8 8) (bvurem n (_ bv8 8))))) (rotate_left2 v (bv2nat n)))))
(assert (forall ((v (_ BitVec 8)) (n (_ BitVec 8))) (= (bvor (bvlshr v (bvurem n (_ bv8 8))) (bvshl v (bvsub (_ bv8 8) (bvurem n (_ bv8 8))))) (rotate_right2 v (bv2nat n)))))
(declare-fun nth_bv1 ((_ BitVec 8) (_ BitVec 8)) Bool)
(assert (forall ((x (_ BitVec 8)) (i (_ BitVec 8))) (= (= (nth_bv1 x i) true) (not (= (bvand (bvlshr x i) #x01) #x00)))))
(assert (forall ((x (_ BitVec 8)) (i (_ BitVec 8))) (= (nth1 x (bv2nat i)) (nth_bv1 x i))))
(assert (forall ((x (_ BitVec 8)) (i Int)) (=> (and (<= 0 i) (< i 256)) (= (nth_bv1 x ((_ int2bv 8) i)) (nth1 x i)))))
(declare-fun eq_sub_bv1 ((_ BitVec 8) (_ BitVec 8) (_ BitVec 8) (_ BitVec 8)) Bool)
(assert (forall ((a (_ BitVec 8)) (b (_ BitVec 8)) (i (_ BitVec 8)) (n (_ BitVec 8))) (let ((mask (bvshl (bvsub (bvshl #x01 n) #x01) i))) (= (eq_sub_bv1 a b i n) (= (bvand b mask) (bvand a mask))))))
(define-fun eq_sub1 ((a (_ BitVec 8)) (b (_ BitVec 8)) (i Int) (n Int)) Bool (forall ((j Int)) (=> (and (<= i j) (< j (+ i n))) (= (nth1 a j) (nth1 b j)))))
(assert (forall ((a (_ BitVec 8)) (b (_ BitVec 8)) (i (_ BitVec 8)) (n (_ BitVec 8))) (= (eq_sub1 a b (bv2nat i) (bv2nat n)) (eq_sub_bv1 a b i n))))
(declare-datatypes () ((t__ref1 (mk_t__ref1 (t__content1 (_ BitVec 8))))))
(declare-fun power1 ((_ BitVec 8) Int) (_ BitVec 8))
(define-fun bv_min1 ((x (_ BitVec 8)) (y (_ BitVec 8))) (_ BitVec 8) (ite (bvule x y) x y))
(define-fun bv_max1 ((x (_ BitVec 8)) (y (_ BitVec 8))) (_ BitVec 8) (ite (bvule x y) y x))
(declare-fun nth2 ((_ BitVec 16) Int) Bool)
(declare-fun lsr2 ((_ BitVec 16) Int) (_ BitVec 16))
(declare-fun asr2 ((_ BitVec 16) Int) (_ BitVec 16))
(declare-fun lsl2 ((_ BitVec 16) Int) (_ BitVec 16))
(declare-fun rotate_right3 ((_ BitVec 16) Int) (_ BitVec 16))
(declare-fun rotate_left3 ((_ BitVec 16) Int) (_ BitVec 16))
(define-fun to_int3 ((x (_ BitVec 16))) Int (ite (bvsge x (_ bv0 16)) (bv2nat x) (- (- 65536 (bv2nat x)))))
(define-fun uint_in_range2 ((i Int)) Bool (and (<= 0 i) (<= i 65535)))
(assert (forall ((x (_ BitVec 16)) (n (_ BitVec 16))) (= (bvlshr x n) (lsr2 x (bv2nat n)))))
(assert (forall ((x (_ BitVec 16)) (n (_ BitVec 16))) (= (bvashr x n) (asr2 x (bv2nat n)))))
(assert (forall ((x (_ BitVec 16)) (n (_ BitVec 16))) (= (bvshl x n) (lsl2 x (bv2nat n)))))
(assert (forall ((v (_ BitVec 16)) (n (_ BitVec 16))) (= (bvor (bvshl v (bvurem n (_ bv16 16))) (bvlshr v (bvsub (_ bv16 16) (bvurem n (_ bv16 16))))) (rotate_left3 v (bv2nat n)))))
(assert (forall ((v (_ BitVec 16)) (n (_ BitVec 16))) (= (bvor (bvlshr v (bvurem n (_ bv16 16))) (bvshl v (bvsub (_ bv16 16) (bvurem n (_ bv16 16))))) (rotate_right3 v (bv2nat n)))))
(declare-fun nth_bv2 ((_ BitVec 16) (_ BitVec 16)) Bool)
(assert (forall ((x (_ BitVec 16)) (i (_ BitVec 16))) (= (= (nth_bv2 x i) true) (not (= (bvand (bvlshr x i) #x0001) #x0000)))))
(assert (forall ((x (_ BitVec 16)) (i (_ BitVec 16))) (= (nth2 x (bv2nat i)) (nth_bv2 x i))))
(assert (forall ((x (_ BitVec 16)) (i Int)) (=> (and (<= 0 i) (< i 65536)) (= (nth_bv2 x ((_ int2bv 16) i)) (nth2 x i)))))
(declare-fun eq_sub_bv2 ((_ BitVec 16) (_ BitVec 16) (_ BitVec 16) (_ BitVec 16)) Bool)
(assert (forall ((a (_ BitVec 16)) (b (_ BitVec 16)) (i (_ BitVec 16)) (n (_ BitVec 16))) (let ((mask (bvshl (bvsub (bvshl #x0001 n) #x0001) i))) (= (eq_sub_bv2 a b i n) (= (bvand b mask) (bvand a mask))))))
(define-fun eq_sub2 ((a (_ BitVec 16)) (b (_ BitVec 16)) (i Int) (n Int)) Bool (forall ((j Int)) (=> (and (<= i j) (< j (+ i n))) (= (nth2 a j) (nth2 b j)))))
(assert (forall ((a (_ BitVec 16)) (b (_ BitVec 16)) (i (_ BitVec 16)) (n (_ BitVec 16))) (= (eq_sub2 a b (bv2nat i) (bv2nat n)) (eq_sub_bv2 a b i n))))
(declare-datatypes () ((t__ref2 (mk_t__ref2 (t__content2 (_ BitVec 16))))))
(declare-fun power2 ((_ BitVec 16) Int) (_ BitVec 16))
(define-fun bv_min2 ((x (_ BitVec 16)) (y (_ BitVec 16))) (_ BitVec 16) (ite (bvule x y) x y))
(define-fun bv_max2 ((x (_ BitVec 16)) (y (_ BitVec 16))) (_ BitVec 16) (ite (bvule x y) y x))
(declare-fun nth3 ((_ BitVec 32) Int) Bool)
(declare-fun lsr3 ((_ BitVec 32) Int) (_ BitVec 32))
(declare-fun asr3 ((_ BitVec 32) Int) (_ BitVec 32))
(declare-fun lsl3 ((_ BitVec 32) Int) (_ BitVec 32))
(declare-fun rotate_right4 ((_ BitVec 32) Int) (_ BitVec 32))
(declare-fun rotate_left4 ((_ BitVec 32) Int) (_ BitVec 32))
(define-fun to_int4 ((x (_ BitVec 32))) Int (ite (bvsge x (_ bv0 32)) (bv2nat x) (- (- 4294967296 (bv2nat x)))))
(define-fun uint_in_range3 ((i Int)) Bool (and (<= 0 i) (<= i 4294967295)))
(assert (forall ((x (_ BitVec 32)) (n (_ BitVec 32))) (= (bvlshr x n) (lsr3 x (bv2nat n)))))
(assert (forall ((x (_ BitVec 32)) (n (_ BitVec 32))) (= (bvashr x n) (asr3 x (bv2nat n)))))
(assert (forall ((x (_ BitVec 32)) (n (_ BitVec 32))) (= (bvshl x n) (lsl3 x (bv2nat n)))))
(assert (forall ((v (_ BitVec 32)) (n (_ BitVec 32))) (= (bvor (bvshl v (bvurem n (_ bv32 32))) (bvlshr v (bvsub (_ bv32 32) (bvurem n (_ bv32 32))))) (rotate_left4 v (bv2nat n)))))
(assert (forall ((v (_ BitVec 32)) (n (_ BitVec 32))) (= (bvor (bvlshr v (bvurem n (_ bv32 32))) (bvshl v (bvsub (_ bv32 32) (bvurem n (_ bv32 32))))) (rotate_right4 v (bv2nat n)))))
(declare-fun nth_bv3 ((_ BitVec 32) (_ BitVec 32)) Bool)
(assert (forall ((x (_ BitVec 32)) (i (_ BitVec 32))) (= (= (nth_bv3 x i) true) (not (= (bvand (bvlshr x i) #x00000001) #x00000000)))))
(assert (forall ((x (_ BitVec 32)) (i (_ BitVec 32))) (= (nth3 x (bv2nat i)) (nth_bv3 x i))))
(assert (forall ((x (_ BitVec 32)) (i Int)) (=> (and (<= 0 i) (< i 4294967296)) (= (nth_bv3 x ((_ int2bv 32) i)) (nth3 x i)))))
(declare-fun eq_sub_bv3 ((_ BitVec 32) (_ BitVec 32) (_ BitVec 32) (_ BitVec 32)) Bool)
(assert (forall ((a (_ BitVec 32)) (b (_ BitVec 32)) (i (_ BitVec 32)) (n (_ BitVec 32))) (let ((mask (bvshl (bvsub (bvshl #x00000001 n) #x00000001) i))) (= (eq_sub_bv3 a b i n) (= (bvand b mask) (bvand a mask))))))
(define-fun eq_sub3 ((a (_ BitVec 32)) (b (_ BitVec 32)) (i Int) (n Int)) Bool (forall ((j Int)) (=> (and (<= i j) (< j (+ i n))) (= (nth3 a j) (nth3 b j)))))
(assert (forall ((a (_ BitVec 32)) (b (_ BitVec 32)) (i (_ BitVec 32)) (n (_ BitVec 32))) (= (eq_sub3 a b (bv2nat i) (bv2nat n)) (eq_sub_bv3 a b i n))))
(declare-datatypes () ((t__ref3 (mk_t__ref3 (t__content3 (_ BitVec 32))))))
(declare-fun power3 ((_ BitVec 32) Int) (_ BitVec 32))
(define-fun bv_min3 ((x (_ BitVec 32)) (y (_ BitVec 32))) (_ BitVec 32) (ite (bvule x y) x y))
(define-fun bv_max3 ((x (_ BitVec 32)) (y (_ BitVec 32))) (_ BitVec 32) (ite (bvule x y) y x))
(assert (forall ((v (_ BitVec 64))) (forall ((amount Int)) (! (=> (and (dynamic_invariant1 v true true true) (dynamic_invariant amount true true true)) (dynamic_invariant1 (shift_right v amount) true false true)) :pattern ((shift_right v amount))))))
(assert (forall ((v (_ BitVec 64))) (forall ((amount Int)) (! (=> (and (dynamic_invariant1 v true true true) (dynamic_invariant amount true true true)) (= (shift_right v amount) (ite (and (<= 1 64) (<= 64 8)) ((_ zero_extend 56) (ite (< amount 8) (bvlshr ((_ extract 7 0) v) ((_ int2bv 8) amount)) ((_ int2bv 8) 0))) (ite (and (<= 9 64) (<= 64 16)) ((_ zero_extend 48) (ite (< amount 16) (bvlshr ((_ extract 15 0) v) ((_ int2bv 16) amount)) ((_ int2bv 16) 0))) (ite (and (<= 17 64) (<= 64 32)) ((_ zero_extend 32) (bvlshr ((_ extract 31 0) v) ((_ int2bv 32) amount))) (bvlshr v ((_ int2bv 64) amount))))))) :pattern ((shift_right v amount))))))
(declare-fun shift_left ((_ BitVec 64) Int) (_ BitVec 64))
(declare-fun shift_left__function_guard ((_ BitVec 64) (_ BitVec 64) Int) Bool)
(assert (forall ((v (_ BitVec 64))) (forall ((amount Int)) (! (=> (and (dynamic_invariant1 v true true true) (dynamic_invariant amount true true true)) (dynamic_invariant1 (shift_left v amount) true false true)) :pattern ((shift_left v amount))))))
(assert (forall ((v (_ BitVec 64))) (forall ((amount Int)) (! (=> (and (dynamic_invariant1 v true true true) (dynamic_invariant amount true true true)) (= (shift_left v amount) (ite (and (<= 1 64) (<= 64 8)) ((_ zero_extend 56) (ite (< amount 8) (bvshl ((_ extract 7 0) v) ((_ int2bv 8) amount)) ((_ int2bv 8) 0))) (ite (and (<= 9 64) (<= 64 16)) ((_ zero_extend 48) (ite (< amount 16) (bvshl ((_ extract 15 0) v) ((_ int2bv 16) amount)) ((_ int2bv 16) 0))) (ite (and (<= 17 64) (<= 64 32)) ((_ zero_extend 32) (bvshl ((_ extract 31 0) v) ((_ int2bv 32) amount))) (bvshl v ((_ int2bv 64) amount))))))) :pattern ((shift_left v amount))))))
(declare-fun make_mask (Int) (_ BitVec 64))
(declare-fun make_mask__function_guard ((_ BitVec 64) Int) Bool)
(define-fun dynamic_invariant3 ((temp___expr_363 Int) (temp___is_init_360 Bool) (temp___skip_constant_361 Bool) (temp___do_toplevel_362 Bool)) Bool (=> (or (= temp___is_init_360 true) (<= 1 64)) (in_range2 temp___expr_363)))
(assert (forall ((num_bits Int)) (! (=> (dynamic_invariant3 num_bits true true true) (dynamic_invariant1 (make_mask num_bits) true false true)) :pattern ((make_mask num_bits)))))
(assert (forall ((num_bits Int)) (! (=> (dynamic_invariant3 num_bits true true true) (= (make_mask num_bits) (shift_right ((_ int2bv 64) 18446744073709551615) (- 64 num_bits)))) :pattern ((make_mask num_bits)))))
(declare-const value (_ BitVec 64))
(declare-const attr__ATTRIBUTE_ADDRESS Int)
(declare-const from Int)
(declare-const attr__ATTRIBUTE_ADDRESS1 Int)
(declare-const to__ Int)
(declare-const attr__ATTRIBUTE_ADDRESS2 Int)
(declare-const len Int)
(declare-const attr__ATTRIBUTE_ADDRESS3 Int)
(declare-const mask (_ BitVec 64))
(declare-const attr__ATTRIBUTE_ADDRESS4 Int)
(declare-const attr__ATTRIBUTE_ADDRESS5 Int)
(assert (= len (+ (- to__ from) 1)))
(assert (= mask (make_mask len)))
(declare-const result__ (_ BitVec 64))
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result (_ BitVec 64))
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__len__assume Int)
(declare-const o Int)
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__mask__assume (_ BitVec 64))
(declare-const o1 (_ BitVec 64))
(declare-const o2 (_ BitVec 64))
(declare-const result (_ BitVec 64))
(declare-const result__1 (_ BitVec 64))
(declare-const result1 (_ BitVec 64))
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result1 (_ BitVec 64))
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result2 (_ BitVec 64))
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result3 (_ BitVec 64))
(declare-const result__2 (_ BitVec 64))
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result4 (_ BitVec 64))
(declare-const result__3 (_ BitVec 64))
(declare-const bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result5 (_ BitVec 64))
(declare-const result2 (_ BitVec 64))
(assert (in_range1 from))
(assert (in_range1 to__))
(assert (<= from to__))
(assert (and (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__len__assume (+ (- to__ from) 1)) (in_range (+ (- to__ from) 1))))
(assert (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__len__assume len))
(assert (in_range len))
(assert (and (= o len) (in_range2 len)))
(assert (and (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__mask__assume (make_mask o)) (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__mask__assume (shift_right ((_ int2bv 64) 18446744073709551615) (- 64 o)))))
(assert (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__mask__assume mask))
(assert (and (= o1 (shift_right value from)) (= o1 (ite (and (<= 1 64) (<= 64 8)) ((_ zero_extend 56) (ite (< from 8) (bvlshr ((_ extract 7 0) value) ((_ int2bv 8) from)) ((_ int2bv 8) 0))) (ite (and (<= 9 64) (<= 64 16)) ((_ zero_extend 48) (ite (< from 16) (bvlshr ((_ extract 15 0) value) ((_ int2bv 16) from)) ((_ int2bv 16) 0))) (ite (and (<= 17 64) (<= 64 32)) ((_ zero_extend 32) (bvlshr ((_ extract 31 0) value) ((_ int2bv 32) from))) (bvlshr value ((_ int2bv 64) from))))))))
(assert (= o2 (bvand o1 mask)))
(assert (= (mk_t__ref result) (mk_t__ref result__)))
(assert (= result__1 o2))
(assert (bvule result__1 mask))
(assert (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result1 bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result2))
(assert (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result3 bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result1))
(assert (= (mk_t__ref result1) (mk_t__ref bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result)))
(assert (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result1 result__1))
(assert (= (mk_t__ref bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result4) (mk_t__ref bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result2)))
(assert (= result__1 result__2))
(assert (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result5 bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result3))
(assert (= result__3 result__1))
(assert (= result2 bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result4))
(assert (not (= bits_manipulation_unsigned__unsigned_64__functions__extract_bits_inline_always__result4 (bvand (shift_right value from) (make_mask (+ (- to__ from) 1))))))
(check-sat)
(exit)
```

**Comment by ajreynol** [comment] 2017-10-26 16:45
Hi Florian,
Thanks for the benchmark.

I have confirmed that the non-linear extension of the quantifier-free arithmetic solver is not to blame here.

The behavior is due to heuristics used for quantifier instantiation.  In particular, when non-linear arithmetic is enabled, CVC4's quantifier instantiation is applied slightly more aggressively (since non-linear arithmetic may be itself non-terminating and hence may be "unfair" to instantiation otherwise).  In this example, when the logic is non-linear, CVC4 is introducing a handful of instantiations, which lead to differences in behavior in the search.  

To make CVC4's quantifier instantiation less aggressive, you can try these options:
--inst-when-strict-interleave 
--inst-when=last-call 

Roughly speaking, these options tell CVC4 to apply quantifier instantiation more lazily. The first means instantiation is strictly interleaved with quantifier-free reasoning, and the second means it is applied only after the quantifier-free solvers terminate.  Either of these make CVC4 identical in linear vs. non-linear logics. However, I have found in my experience that --inst-when=last-call is generally not a good idea overall.

Hope this helps,
Andy

**Comment by ajreynol** [comment] 2017-10-26 16:50
Also regarding the logic exception, this is what I get with --no-cbqi:

(error "A non-linear fact (involving div/mod/divisibility) was asserted to arithmetic in a linear logic: (mod from 18446744073709551616)
if you only use division (or modulus) by a constant value, or if you only use the divisibility-by-k predicate, try using the --rewrite-divk option.
The fact in question: (>= (mod from 18446744073709551616) 9223372036854775808)
")

Is this what you are seeing? If so, you can try using --rewrite-divk to address this.

**Comment by florianschanda** [comment] 2017-10-27 11:21
Thank you for the fast answer, as usual :)

And yes, that is indeed the error I am seeing too. I am investigating if --inst-when-strict-interleave can be specified by default for SPARK.

**Comment by ajreynol** [comment] 2018-10-16 20:36
Closing this since it seems to be an expected consequence of changing the logic.
The benchmark in question solves in 8 seconds now.

**Closed by ajreynol** 2018-10-16 20:36 UTC
Labels: minor, performance
