### ISSUE TITLE
:refine-conflicts fatal failure at src/theory/sets/cardinality_extension.cpp:863

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4095] opened 2020-03-15 05:19 UTC
Hi,
For this formula:
```
(declare-fun a () (Set String)) 
(declare-fun b () (Set (Tuple Int Int))) 
(declare-fun c () (Set (Tuple Int Int))) 
(declare-fun d () Int)     
(assert (distinct c (tclosure b))) 
(assert (distinct d (card a))) 
(check-sat)
```
CVC4  throws out a fatal failure:
```
Fatal failure within void CVC4::theory::sets::CardinalityExtension::checkNormalForm(CVC4::Node, std::vector<CVC4::NodeTemplate<true> >&) at src/theory/sets/cardinality_extension.cpp:863
Check failure

 d_im.hasProcessed()

Aborted
```

OS: Ubuntu 18.04
Commit: 442ab0c

**Comment by ajreynol** [comment] 2020-03-15 13:46
`refine-conflicts` will be deleted, duplicate of #4008.

**Closed by ajreynol** 2020-03-15 13:46 UTC
