### ISSUE TITLE
CVC4 User manual and tutorials not available

### ISSUE THREAD

**Issue by Dosewalops** [CVC4/CVC4#2383] opened 2018-08-27 17:05 UTC
Home page and download page are available. But clicking on user manual link from the home page results in broken link.

Thanks

**Comment by 4tXJ7f** [comment] 2018-08-27 17:12
Thanks for the report. Are you referring to the link to http://cvc4.cs.stanford.edu/wiki/User_Manual? That link works for me. Can you please check again or let us know which URL you are referring to if it is not the one I mentioned?

Also, the User Manual currently only has some very basic information. How are you intending to use CVC4? Standalone or its API? Which theories? If you let us know more about your use case, we can point you to some additional resources.

**Comment by Dosewalops** [comment] 2018-08-27 23:47
Thanks for your prompt reply.

It appears to be an issue with Chrome and the CVC Manual and Tutorals site with “too many redirects”. No other sites except these two are affected. Even CVC Home page and download page work fine. I have used Chrome more than a decade and have never had this issue before.


Firefox does not have the issue and works fine, so please close my report.


I actually do have an issue you could help with, following up on your offer to help.

I am attempting to use Quantified BitVectors (UFBV) to do relational algebra with Z3’s Java adapter, in particular using Kleene algebras as a foundation to algebraic modal logic. Everything works except the performance of matrix multiplication as my only bottleneck. So it could be that I am trying to push Quantifed BitVectors more than it is designed for, or my attempt to code matrix multiplication with all its extracts is flawed. The code does produce the right answer. I have attached the Java code using Z3. It is less than one page and only encodes a standard interpretation of matrix multiplication. The only nonstandard feature is the use of Concat to assemble the product. Since there is no NIL element, the first inner product is special cased, which costs three lines of code.


The intent is simple. The domain size is vertexSize and we are encoding multiplication’s associative law. We interpret every BitVector as a row major matrix, which we then use “extracts” to deconstruct the matrix to yield the product of the two input BitVectors. This works, but there many extracts and the performance suffers.


int vertexSize = 20 // Using 20 as number of domain elements

int matrixSize = vertexSize * vertexSize;

BitVecExpr X = ctx.mkBVConst(“X”,matrixSize);

BitVecExpr Y = ctx.mkBVConst(“Y”,matrixSize);

BitVecExpr Z = ctx.mkBVConst(“Z”,matrixSize);


Expr multAssociativeBody = ctx.mkEq(mult(X,mult(Y,Z)), mult(mult(X,Y),Z));

BoolExpr multAssociative = ctx.mkForall(boundVariablesTernary,multAssociativeBody,

                                                                         0,null,null,null,null);

solver.add(multAssociative);


If I could get this to work with at least 100 elements in the domain, this will allow full Open World and Closed World reasoning using Modal Logic, not just the Closed World typical of Datalog derivatives.


Thanks very much for your attention.


The single page of Java code using Z3 for matrix multiplication,

BitVecExpr mult(BitVecExpr,BitVecExpr), is attached.



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by 4tXJ7f** [comment] 2018-09-04 02:49
> It appears to be an issue with Chrome and the CVC Manual and Tutorals site with “too many redirects”. No other sites except these two are affected. Even CVC Home page and download page work fine. I have used Chrome more than a decade and have never had this issue before.

Unfortunately we were not able to reproduce it from our side (with or without Chrome). We did have issues with our wiki website before and I wouldn't be surprised if we are having issues again. Do you have the issue only with that specific wiki page or also the [main page](http://cvc4.cs.stanford.edu/wiki/) of the wiki? Are you using a plugin like HTTPS Everywhere that tries to force an HTTPS connection?

> The single page of Java code using Z3 for matrix multiplication, BitVecExpr mult(BitVecExpr,BitVecExpr), is attached.

It looks like GitHub ate the attachment from the email. Could you either post it to the GitHub issue directly or make it available through some other means? Thanks!

**Comment by Dosewalops** [comment] 2018-09-04 22:44
The only link that fails using Chrome is:

http://cvc4.cs.stanford.edu/wiki/About_CVC4


The response is:

This page isn’t working

cvc4.cs.stanford.edu redirected you too many times.

  *   Try clearing your cookies<https://support.google.com/chrome?p=rl_error&hl=en-US>.

ERR_TOO_MANY_REDIRECTS

I actually cleared my cookies without effect. My version of Chrome is pure vanilla; I have never added extensions. Firefox has no problem for the same link.

Thanks
________________________________

**Comment by 4tXJ7f** [comment] 2019-03-16 00:37
Unfortunately, we were not able to reproduce this issue (neither when accessing the website form on-campus nor off-campus internet). Additionally, the wiki is being retired, so I am closing this issue for now. Please let us know if you have further issues accessing CVC4 resources.

**Closed by 4tXJ7f** 2019-03-16 00:37 UTC

**Comment by bdrodes** [comment] 2020-09-30 13:05
I noticed this issue today. ERR_TOO_MANY_REDIRECTS for http://cvc4.cs.stanford.edu/wiki/User_Manual (the link referenced on the cvc4 documentation page found here: https://cvc4.github.io/documentation.html)

**Comment by dmr05d** [comment] 2020-09-30 23:13
I am also experiencing this error on Chrome, Edge, and Firefox.

ERR_TOO_MANY_REDIRECTS
